### ISSUE TITLE
Creating a reusable component

### ISSUE THREAD

**Issue by yantakus** [smooth-code/loadable-components#100]
Is it possible to create a reusable component so that we don't have to repeat ourselves like this all the time:

```javascript
const One = Loadable({
  loader: () => import('./components/One'),
  loading() {
    return <Preloader />
  }
});
const Two = Loadable({
  loader: () => import('./components/Two'),
  loading() {
    return <Preloader />
  }
});
```

I tried to do it like this:

```javascript
import Loadable from 'loadable-components';

const Load = ({ loader, ...otherProps }) => {
  const LoadableComponent = Loadable(loader, { LoadingComponent: Preloader });
  return <LoadableComponent {...otherProps} />;
};
```

and then:

```javascript
<Route path="/one" render={props => <Load loader={() => import('components/One')} />} />
<Route path="/two" render={props => <Load loader={() => import('components/Two')} />} />
```

But I start getting into weird infinite loops with this approach. Any ideas?

**Comment by theKashey** [comment]
Not a good idea - Loadable will always produce a new Class and rerender it, and then again and again.
You could do it only if your `Load` will be `Component`, not SFC. Then - you will be able to construct "the right" Loadable once on component "first creation", and reuse it later.
Meanwhile - on route change it will die, and some 🙀could happens next.

What about just creating a small helper function for Loadable itself?
```js
const Load = ({ loader, ...otherProps }) => Loadable(loader, { LoadingComponent: Preloader });
```

PS: If you really wanna "component way" - take a look at https://github.com/theKashey/react-imported-component

**Comment by yantakus** [comment]
@theKashey actually I already tried to use it like you suggest and it throws the following error without rendering anything:

```
Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
```

So I don't think it can be used like this.

Thanks for mentioning your one, I'll definitely have a look at it.

**Comment by theKashey** [comment]
This should work on FrontEnd, but may fail SSR.
```js
const Load = ({ loader, ...otherProps }) => Loadable(loader, { LoadingComponent: Preloader });

const PageOne = Load({loader:() => import('components/One')});

<Route path="/one" render={props => <PageOne />} />
```

**Comment by yantakus** [comment]
Thanks for this, but tt is still very verbose. We have hundreds of routes and would like every one to take a single line to be readable and maintainable.

**Comment by yantakus** [comment]
We had it like this before migrating to react-router v4 and it is even more verbose, because you have to pass lots of parameters (private route, children and other stuff):

![image](https://user-images.githubusercontent.com/2179726/41641774-10ea187e-746f-11e8-97db-f7e33938a4d9.png)

So we realized component way is much better (for maintainability and readability) for stuff like this.

**Comment by theKashey** [comment]
Then you may do a terific thing - memoize element render.
```js
const createRoutes = () => (
 <Switch>
   <Route path="/one" render={props => <Load loader={() => import('components/One')} />} />
 </Switch>
);

const myRoutes = createRoutes();

export default () => myRoutes;
```
Thus "loadableComponent" will be called only once.

**Comment by yantakus** [comment]
Interesting, but still quite a little bit verbose and error-prone (if somebody forgets to add this intermediate step, he will get into a trouble with infinite loops). Is there a way to do it simpler with `react-imported-component`? What is the "component way" you mentioned earlier?

**Comment by theKashey** [comment]
https://github.com/theKashey/react-imported-component#component-loader
Ie `importedComponent` itself is a sugar around ComponentLoader - see https://github.com/theKashey/react-imported-component/blob/master/src/HOC.js

PS: Keep in mind, that it is far less popular library, and thus far less tested.

**Comment by neoziro** [comment]
@yantakus I don't have a good solution, I think I could solve it by adding a default option method:

```js
import { setDefaultOptions } from 'loadable-components'

loadable.setDefaultOptions()
```

It would also solve #91, @Aetherall what do you think?

**Comment by Aetherall** [comment]
I like the Idea of being able to reuse the component,
in my project I use different loaders depending on where the async component is used (on the admin panel or the public website)
So it may be a good Idea to be able to define multiple loaders

The Load component syntax is gorgeous *.*

```jsx
<Route path="/one" render={props => <Load loader={() => import('components/One')} />} />
```

**Comment by the0neWhoKnocks** [comment]
:+1: from me on this as well. I've been working on integrating dynamic imports with `react-loadable`. Their Babel plugin suffers from the same issue as yours (but they don't have an Issues board) and some of the replies to issues in that repo seem a bit stand-offish. So I started shopping around for a new module to use.

Here are working examples of what I've set-up which should translate to this module.
1. I [set up a component](https://github.com/the0neWhoKnocks/boilerplate.react.spa.full-server/blob/1395df878b4b9af32c6b1b4e1f540f18f2834e26/src/components/AsyncView/index.js#L31-L40) to remove duplication.
1. I then [implement that component](https://github.com/the0neWhoKnocks/boilerplate.react.spa.full-server/blob/1395df878b4b9af32c6b1b4e1f540f18f2834e26/src/data.js#L83-L88). This is the point when the Babel plugin breaks because it only allows for dynamic imports to come from itself.
1. So I duplicated the plugin, made a couple tiny edits, and now things are working as expected again, even when utilizing Webpack aliases.
   - [Plugin change](https://github.com/the0neWhoKnocks/boilerplate.react.spa.full-server/blob/1395df878b4b9af32c6b1b4e1f540f18f2834e26/.babel/plugins/appendChunkProps.js#L9-L13)
   - [Babel integration](https://github.com/the0neWhoKnocks/boilerplate.react.spa.full-server/blob/1395df878b4b9af32c6b1b4e1f540f18f2834e26/.babel/conf.babel.js#L12-L17)

**Comment by neoziro** [comment]
Loadable Components v3 has been released 🎉, please give a try.

Reusable components can be done easily.

👉 https://github.com/smooth-code/loadable-components

**Comment by sagar-gavhane** [comment]
`react-loadable` library given demonstrated on HOC component to avoid repetitions. 

https://github.com/jamiebuilds/react-loadable#how-do-i-avoid-repetition

**Comment by neoziro** [comment]
```js
// custom-loadable.js
import loadable from '@loadable/component'

export default fn => loadable(fn, { fallback: 'Loading...' })
```

```js
// app.js
import loadable from './custom-loadable'

const OtherComponent = loadable(() => import('./OtherComponent'))
```

> If you want to be compatible with SSR, using the `loadable` name is required.

**Comment by bertho-zero** [comment]
@neoziro This may have its place in the documentation?

**Comment by neoziro** [comment]
It is already, but maybe not in the good place? https://www.smooth-code.com/open-source/loadable-components/docs/babel-plugin/#loadable-detection

**Comment by bertho-zero** [comment]
I do not think to find that in the "babel plugin" section, I thought of a guide "Avoid repetition" or something like that.

**Comment by neoziro** [comment]
@bertho-zero yeah why not, feel free to add it if you want to contribute!
