### ISSUE TITLE
consider using react-walk-tree

### ISSUE THREAD

**Issue by alidcastano** [smooth-code/loadable-components#102]
Hey, is there a reason you didn't use react-walk-tree for this module?

The reason I ask is that I'm considering using this module for code splitting, but still need to implement some version of Nextjs `getInitialProps`.

By using same module, it results in less code to bundle and maintain so wondering if there's a reason you didn't use it

Thanks

**Comment by theKashey** [comment]
`react-walk-tree` was broken for a long time, and last _suspense_ related changes are not supported by it.

**Comment by neoziro** [comment]
I think about extracting the walk tree from this package, it should be the work of React Apollo (see https://github.com/apollographql/react-apollo/issues/1937) but they seem to not care about it.

**Comment by alidcastano** [comment]
oh wow just learned about React Suspense 

So would its release make Loadable components and other code splitting libraries unnecessary?

if not, @neoziro are you still considering extracting logic? I believe that's where you left off in React issue so not sure if anything has changed since

**Comment by theKashey** [comment]
> So would its release make Loadable components and other code splitting libraries unnecessary?

No, suspense is about "waiting" for some things to be done, and loadable components utilizes suspense underneath to wait for component to be loaded, or inform you about that event.

See https://twitter.com/acdlite/status/1007062696141787136

**Comment by alidcastano** [comment]
btw, as of 2 days ago react-walker-tree (v4.1.0) supports React.Context API

**Comment by neoziro** [comment]
I am thinking about a new version that will work without tree traversing. For now, I prefer to keep it like that but thanks for the suggestion!

**Comment by alidcastano** [comment]
@neoziro I'd love to know more. I'm working on a SSR framework for React that uses Parcel and loadable-components. I'll release it next week but repo is up at https://github.com/alidcastano/rogue. 

Right now I'm using `react-walk-tree` to `getInitialProps` but would be great to know how you plan on doing this to have a compatible solution on my end, thanks!
