### ISSUE TITLE
Add support for any webpack assets

### ISSUE THREAD

**Issue by sergeysolovev** [smooth-code/loadable-components#103]
Hello! Thanks for your great lib, it greatly simplified route-based code splitting with SSR for me.

I would like to use it not just for React components, but for any modules Webpack can import. In the code below I use it to load the texts of markdown files. Whereas it works fine client-side, I get empty string when rendering server-side.

Is it hard to implement? Or maybe you can suggest a workaround?

```javascript
if (useMarkdown) {
  const pathNoExt = sourcePath.replace(/\.md$/, '');
  return {
    component: loadable(() => import(`content/${pathNoExt}.md`), {
      render: ({ Component, loading, ownProps }) => {
        if (loading || !Component) return null;
        const { default: source } = Component;
        return (
          <MarkdownArticlePage {...ownProps} source={source} />
        );
      }
    })
  };
}
```

**Comment by theKashey** [comment]
How do you bundle serverside? What webpack-loader do you use for clientside?

In case you are using pure node.js for SSR - then you may have to specify custom extension handlers to convert files to the desired format.

**Comment by sergeysolovev** [comment]
@theKashey thanks for your quick reply!

> How do you bundle serverside?

I have a module with the only function which prerenders HTML by route’s url. This module uses `react-dom/server` and `loadable-components/server` internally. I transpile it with webpack prior to using. 

```javascript
export const prerender = url => {
  const app = (
    <StaticRouter location={url} context={{}}>
      <App />
    </StaticRouter>
  );
  return getLoadableState(app).then(loadableState => ({
    body: renderToString(app),
    scriptTag: loadableState.getScriptTag(),
    helmet: Helmet.renderStatic()
  }));
};
```

> What webpack-loader do you use for clientside?

I use [raw-loader](https://github.com/webpack-contrib/raw-loader) to import markdown contents as is and feed it as a `source` property to [react-markdown](https://github.com/rexxars/react-markdown) component.

I’m afraid I can not render markdown as react components directly using any webpack loader, as I use my existing components for that:

```javascript
import React from 'react';
import Heading from 'components/Heading';
import ReactMarkdown from 'react-markdown';

const isH1 = ({ type, depth }) => type === 'heading' && depth === 1;

const renderers = {
  root: React.Fragment,
  heading: ({ level, ...rest }) => <Heading {...rest} type={`h${level}`} />
};

const Markdown = props => (
  <ReactMarkdown
    {...props}
    renderers={renderers}
    allowNode={node => !isH1(node)}
  />
);

export default Markdown;
```

This thing is, it works fine client-side, which is why I would expect it to work server-side as well.

### Current workaround

My current workaround for now is to import markdown into JS modules and export wrapped markdown component out of there.

```javascript
import source from './index.md';
import { markdownArticle } from 'components/markdownArticle';

export default markdownArticle({ source });
```

It works but this way I need to have both JS and md files, whereas it would be nice to have md only and work with it directly.

**Comment by sergeysolovev** [comment]
@theKashey Thanks! It’s working as expected and it does work fine client-side, the only problem is when I’m pre-prendering it server-side – I get nothing in this case instead of component markup.

Your snippet will log to console `{ default: '... markdown contents ...' }`. If it was a react component (a function of props) then everything would work as expected server-side. The point of my initial question to make it work server-side even if it’s not a react component, but any module webpack can import.

**Comment by theKashey** [comment]
Loadable components does not carry about what to render, and how you load it (more or less).
If you want to render something, what is not a renderable (ie not a react component) - use `render` prop to wrap it with something renderable - https://github.com/smooth-code/loadable-components#custom-loading

**Comment by sergeysolovev** [comment]
I seem to found the reason. It’s inconsistency between implementations of dynamic imports. I use babel plugin **dynamic-import-node** server-side and webpack 4 build-in dynamic import client-side. 

In both cases `module.__esModule` is as expected `undefined` for markdown file, but webpack put markdown contents into the `module.default`, whereas _dynamic-import-node_ right into the module.

More info and workaround: https://github.com/airbnb/babel-plugin-dynamic-import-node/issues/47

To fix it locally I have to replace this code

```
const { default: source } = Component;
```

with this:

```
const source = Component.default || Component;
```

To avoid this hacks I suggest this PR to be merged: https://github.com/smooth-code/loadable-components/pull/104

**Comment by theKashey** [comment]
Yep, webpack is creating default exports even if they does not exists.
