### ISSUE TITLE
unit testing async component

### ISSUE THREAD

**Issue by mojilla** [smooth-code/loadable-components#106]
I'm very grateful for this great repo and so confident to utilizing it in a scaled app.
Please take a glimpse into this typical sample

```
import loadable from 'loadable-components';
import dashboardPagesLoading from '../../Common/dashboardPagesLoading';

export default loadable(
  () => import(/* webpackChunkName: "client.list" */ './list'),
  {
    LoadingComponent: dashboardPagesLoading
  }
);
```
Whats your approach to unit test it?

**Comment by theKashey** [comment]
dependency level __mocking__?

**Comment by mojilla** [comment]
Approaches could be mocking or even snapshot testing or whatever

**Comment by neoziro** [comment]
Please open a new issue about that for v3, everything has changed it is confusing.
