### ISSUE TITLE
warning against walking dom tree

### ISSUE THREAD

**Issue by alidcastano** [smooth-code/loadable-components#107]
Hey guys, I recently released [Rogue.js](https://github.com/alidcastano/rogue.js) which has built-in support for loadable components. Love the API / ease of use, it was easy to integrate into framework, so thanks for your work

Anyway, Just wanted to bring these two tweets to your attention about walking React tree:
https://twitter.com/dan_abramov/status/1021548632619790336
https://twitter.com/acdlite/status/1021579833459978241

Feel free to close this if you feel it's not a concern or can't be avoided, otherwise would be glad to discuss it

**Comment by theKashey** [comment]
Traversing the tree != rendering the tree.
As long as this is _suspense related_ - it's more about "hey, we are going to throw Promises from render and it will blow it your react-tree-walker, cos, you know, it __throw__".

Loadable-components are suspense ready, and uses "them"(mortals didn't see it yet) to SSR. Should not blowup.

**Comment by neoziro** [comment]
I am aware of this and I will probably drop the walk of the tree if possible.

I also [asked the React team about that](https://github.com/facebook/react/issues/12640), their answer is not satisfying: "just use Suspense".

But Suspense is experimental on client-side, and completely not ready server-side. I think we have to wait for Suspense to be released officially, then think about a new way to do thing more "React friendly".

**Comment by theKashey** [comment]
About doing things more React-friendly - take a look on idea around https://github.com/theKashey/react-prerendered-component, which removes need of waiting for all used chunks to be loaded up front. 
However, it's still a good idea to load them in parallel. However, that's not good for slow connections.
