### ISSUE TITLE
loadable-components and refs?

### ISSUE THREAD

**Issue by linkenneth** [smooth-code/loadable-components#108]
As it stands loadable-components doesn't handle refs (correct me if I'm wrong). Are there any plans to? My intended use case is to delay-load a component that needs a ref, and I don't really care about the ref until after it's loaded. (ie. I only care about the underlying component's ref, not the ref of the loadable or the loading component).

**Comment by neoziro** [comment]
Yes it actually doesn't handle refs but it is on feature list.

**Comment by linkenneth** [comment]
Would it be a lot of work to add? AFAICT would it just be adding ref forwarding ala React manual (https://reactjs.org/docs/forwarding-refs.html)? I'm not sure how server-side rendering would factor into this though.

**Comment by mojilla** [comment]
+1

**Comment by StefanoVuerich** [comment]
+1

**Comment by TrueMoein** [comment]
+1

**Comment by neoziro** [comment]
Refs are not supported in v3 but I plan to add support soon. Feel free to open a new issue. I close it because this one was about v2.

**Comment by linkenneth** [comment]
@neoziro is this supported now? It seems like it is from the code and trying it out.

**Comment by neoziro** [comment]
Yes ref are supported out of the box in v5, you can transparently use them.

**Comment by pdd-jiama** [comment]
> Yes refs are supported out of the box in v5, you can transparently use them.

hey,how can i use refs？I use a ref to loadable compents， but get 'null';

**Comment by silviubogan** [comment]
> > Yes refs are supported out of the box in v5, you can transparently use them.
> 
> hey,how can i use refs？I use a ref to loadable compents， but get 'null';

For others that need this, you can use `loadable.lib` instead of `loadable`. See https://loadable-components.com/docs/library-splitting/.
