### ISSUE TITLE
reload functionality

### ISSUE THREAD

**Issue by stereobooster** [smooth-code/loadable-components#115]
WDYT about reload functionality? Can look like this:

```js
import loadable from 'loadable-components'

const MyLoadableComponent = loadable(() => import('./MyComponent'), {
  ErrorComponent: ({ error, reload }) => <div><h1>Error</h1><a onClick={reload}>try again</a></div>,
  LoadingComponent: () => <div>Loading...</div>,
})
```

**Comment by theKashey** [comment]
👍 must have feature for `ErrorComponent`

**Comment by neoziro** [comment]
Thanks @stereobooster for this. I think it is an interesting feature and it is not difficult to implement.

**Comment by neoziro** [comment]
Loadable Components v3 has been released 🎉, please give a try.

👉 https://github.com/smooth-code/loadable-components

**Comment by superandrew213** [comment]
@neoziro did you ever add `reload`?

Is there a way to do this with the current version?

**Comment by neoziro** [comment]
@superandrew213 not yet, but I will soon. Stay tuned about new versions.
