### ISSUE TITLE
getLoadableState)(...).then is not a function

### ISSUE THREAD

**Issue by bnlb** [smooth-code/loadable-components#12]
First off, great work! I love the simplicity of this project.

### Expected behavior

`getLoadableState()` should return a promise.

### Actual behavior

`getLoadableState()` returns an instance of `DeferredState` if no queries are found.

### Steps to reproduce

1. From the root of an empty directory: `yarn add loadable-components`.
2. Open `node_modules/loadable-components/server/index.js`.

`getLoadableState` contains the following line:
```if (!queries.length) return new _DeferredState2.default([]);```

If I download the repo and run `yarn build`, this is output instead:
```if (!queries.length) return Promise.resolve(new _DeferredState2.default([]));```

Opening up the tarball listed on npm shows the line that isn't wrapped in Promise.resolve, so I think all that needs to be done is to update that.

**Comment by neoziro** [comment]
Thanks! I will fix it soon.

**Comment by neoziro** [comment]
It was already fixed, I published a new version: https://github.com/smooth-code/loadable-components/releases/tag/v0.2.1
