### ISSUE TITLE
getLoadableState doesn't work with Apollo

### ISSUE THREAD

**Issue by geiszla** [smooth-code/loadable-components#122]
At server-side rendering, one would use
```js
const loadableState = await getLoadableState(reactApp);
const content = await renderToString(reactApp);
```
However, I use Apollo for data management, therefore I need the app to be rendered with Apollo data:
```js
const content = await renderToStringWithData(reactApp);
```
In my app, I'm relying on `this.props.data.loading` to return `Loading...`, when the data is not available, so currently `getLoadableState` returns empty. Is there a way to use `getLoadableState()` with Apollo data, so that `this.props.data.loading` won't be true?

**Comment by neoziro** [comment]
Loadable Components v3 has been released 🎉, please give a try.

👉 https://github.com/smooth-code/loadable-components

**Comment by klarstrup** [comment]
Can confirm, having upgraded from v2 to v5 everything works nicely except Apollo `getDataFromTree` doesn't actually do anything, whereas it used to be able to work perfectly fine after a `await getLoadableState(components)`. What was wrong with that API?

**Comment by neoziro** [comment]
It is a problem in React Apollo, you need to upgrade it, see 
https://github.com/smooth-code/loadable-components/issues/30#issuecomment-438360242

**Comment by klarstrup** [comment]
Sweet, thanks!
