### ISSUE TITLE
TypeScript types are not correct for server module

### ISSUE THREAD

**Issue by ryardley** [smooth-code/loadable-components#124]
Using the following version:
```
    "loadable-components": "^2.2.3",
```

When trying to use loadable-components in a TypeScript project I am getting the following error:

```typescript
import { getLoadableState } from 'loadable-components/server';
```

```
error TS7016: Could not find a declaration file for module 'loadable-components/server'.
```

I suspect this is a missing export definition file.

Elsewhere this works fine: 

```typescript
import loadable from 'loadable-components';
```

**Comment by neoziro** [comment]
v3 has been release, no TypeScript support. Please add them to https://github.com/DefinitelyTyped/DefinitelyTyped if you want them.
