### ISSUE TITLE
Static mode cannot be used with Webpack devserver

### ISSUE THREAD

**Issue by geiszla** [smooth-code/loadable-components#126]
## 🐛 Bug Report

When using static mode on server, and Webpack dev server is enabled, the manifest file will be generated and served by the webserver and not written to the project directory, therefore the server cannot import it for server-side rendering.

## To Reproduce

1. Setup Webpack dev server and @loadable/webpack-plugin in the Webpack config
2. Start it with `webpack-dev-server --config`

The generated assets, including the manifest file, are not copied to the project directory, so cannot be used by the server.

## Expected behavior

Generated manifest file should be written to the project directory so that the server can use it for server-side rendering.

## Link to Repo

https://github.com/geiszla/react-website-starter/tree/loadable-components-static

Build it with `yarn dev` to run problematic Webpack config.

## Package versions
`envinfo` failed to run, so here's the version info of installed packages:
```json
"@loadable/babel-plugin": "^3.0.0",
"@loadable/component": "^3.0.0",
"@loadable/server": "^3.0.0",
"@loadable/webpack-plugin": "^3.0.0",
"webpack-dev-server": "^3.1.10"
```

**Comment by neoziro** [comment]
@geiszla thanks for the documentation, it will be fixed.

Yes static mode is complex and difficult and `webpack-dev-server` does not copy files on the disk.

If you want to use it you have to run a `webpack --watch` in order to have them loaded on the disk. You can also run webpack programatically, then you can access assets in the node process.

**Comment by marcneander** [comment]
Using razzle you won't be able to change this. Wouldn't it be easy to just have the webpack-plugin write to disk always? @neoziro

**Comment by neoziro** [comment]
I don’t know if it is even possible! But if it is, yes we should do it. Can you open a new issue?
