### ISSUE TITLE
Lazy loading from another host

### ISSUE THREAD

**Issue by Kmaschta** [smooth-code/loadable-components#138]
## 🚀 Feature Proposal

Allow to load JavaScript chunks from another domain.

## Motivation

Let's say, in development, we have two services:
- [front] A webpack dev server, which generate JS bundles
- [back] A web server, which runs the API and the SSR for the app

For the same app, say that the production will run both frontend and backend on the same host.

## Example

An idea would be to have a loadable config somewhere at the app start:

```js
import { setConfig } from '@loadable/component';

setConfig({ host: REACT_APP_BASE_URL }); 
```

This config would prefix the host before each lazy import, from the frontend or from the SSR part.

## Pitch

It happens quite often that the service responsible to the SSR is different from the frontend management (like a CDN for example)
A config key would make loadable even more awesome!

**Comment by theKashey** [comment]
See https://webpack.js.org/guides/public-path/ - it could be configured in runtime.

**Comment by Kmaschta** [comment]
Ah, you're right!
Thank you very much.

And thank you for making code splitting so simple :muscle:
