### ISSUE TITLE
loadableState.getPrefetchTags() returns empty string

### ISSUE THREAD

**Issue by marcneander** [smooth-code/loadable-components#139]
First of, thanks for a great lib. I much prefer this than react-loadable. Hope more people will find this.

## 🐛 Bug Report

`loadableState.getPrefetchElements()` or `loadableState.getPrefetchTags()` returns empty string even though I'm using `renderToString`

## To Reproduce

```js
const helmetContext = {};
const loadableState = new LoadableState(manifest);

const Root = () => (
    <HelmetProvider context={helmetContext}>
        <ServerLocation url={req.url}>
            <LoadableStateManager state={loadableState}>
                <App />
            </LoadableStateManager>
        </ServerLocation>
    </HelmetProvider>
);

const html = ReactDOM.renderToString(<Root />);
const { helmet } = helmetContext;

console.log(loadableState.getPrefetchElements());
```

## Expected behavior

Should work as documentation is stating?

Since I'm using renderToString I could just create my own prefetch tags:

```js
const bundles = loadableState.getChunks().map(chunk => loadableState.getChunkAsset(chunk));
const createPrefetchTag = ({ href }) => `<link rel="prefetch" href="${href}" as="script">`;

const html = `
<html>
    <head>
    ...
    ${bundles.map(href => createPrefetchTag({ href }))}
    </head>
`;
```

As a sidenote. If you have support for prefetch link tags you should probably also add support for preload. In my opinion, it might be best for this library to not have an opinion on how to format tags/elements. Rather just have an API for returning the chunks and let each individual create it's own solution.

Best,
Marc

**Comment by neoziro** [comment]
Hey @marcneander, SSR has been completely rebuild in v5. Can you please update and open a new issue if it does not fix it? Thank you 🙏
