### ISSUE TITLE
New SSR webpack aliases don't seem to be working

### ISSUE THREAD

**Issue by davidfloegel** [smooth-code/loadable-components#141]
Hey guys,

you're doing a fantastic job with this repo!

Last night I've upgraded our app to be server side rendered by following [your example](https://github.com/smooth-code/loadable-components/tree/master/examples/server-side-rendering).

However, I can't get it starting because we use webpack aliases. I believe the issue is that the routes file with the components gets picked up _before_ the webpack config is loaded and therefore can't resolve the aliases.

I have [created a small repo](https://github.com/davidfloegel/react-ssr) which represents our app in a much smaller scale. I have added [2 aliases](https://github.com/davidfloegel/react-ssr/blob/master/webpack.config.babel.js#L39) in the webpack config.

Are you guys able to give me a hand at all? That would be much appreciated!

Thanks

David

**Comment by neoziro** [comment]
Try to use [babel-plugin-module-resolver](https://www.npmjs.com/package/babel-plugin-module-resolver) instead of Webpack aliases, it should resolve your problem. I don’t know if there is really a solution for this problem.

**Comment by davidfloegel** [comment]
Thank you that helped :)
