### ISSUE TITLE
the library doesn't work with React v15

### ISSUE THREAD

**Issue by zetekla** [smooth-code/loadable-components#145]
## 🐛 Bug Report

I create a new React app with FB cli create-react-app and replace react 16.x with react 15.x due to corporate need of compatibility but the library cannot render, giving webpack error.

These are the dependencies I use to reproduce the issue.
    "react": "^15.6.2",
    "react-dom": "^15.6.2",

Was there a version release with breaking changes to only suit React v16 and v17 ?

Can you take a look to help fix?

Thanks, 
Pristine.

**Comment by neoziro** [comment]
Yes there is a lot of breaking changes that makes it incompatible with React v15. It’s time to move forward, sorry!

**Comment by neoziro** [comment]
You can’t fix them, the only way is to upgrade to the latest version of React. With hooks coming, all libraries will probably requires the latest soon. It is a very bad move to stay on React v15, if you have to, be prepared to code your own library or to stay on old version of library. But you will be exposed to security flaws, I insist, this is not a good strategy.

**Comment by zetekla** [comment]
I see. Thank you for your replies.

**Comment by peteromano** [comment]
Just posted the same issue on Twitter to smooth code last night.

@neoziro in github releases, looks like react 16 support was added after v1.2.0. If nothing else, would that version work with 15?

**Comment by neoziro** [comment]
This version requires React v16.3.0+, see https://github.com/smooth-code/loadable-components/blob/master/packages/component/package.json#L34
