### ISSUE TITLE
server-side-rendering example issue: babel-plugin not found

### ISSUE THREAD

**Issue by zetekla** [smooth-code/loadable-components#146]
## 🐛 Bug Report
After installing dependencies in server-side-rendering package, attempts to run `yarn build`, `yarn build:lib`, give the following error, thus, hindering app run with `yarn start`. 
`yarn dev` does give the same error too.
The error reads:
babel.config.js: Error while loading config - Cannot find module '../../packages/babel-plugin'

Node LTS v8.11.3, npm v6.2.0

**Comment by neoziro** [comment]
The examples runs the version of loadable compiled in this repository, to fix it:

- Run `yarn build` at the root of this repository
- Run `yarn dev` in the example

It should fix your issue!

**Comment by zetekla** [comment]
I see.

**Comment by royibernthal** [comment]
This is what I get when I run yarn build at the root of the repository:

> yarn build
> yarn run v1.13.0
> $ lerna run build
> lerna notice cli v3.10.5
> lerna info Executing command in 4 packages: "yarn run build"
> lerna ERR! yarn run build exited 1 in '@loadable/server'
> lerna ERR! yarn run build stdout:
> $ shx rm -rf lib
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> lerna ERR! yarn run build stderr:
> '**shx**' is not recognized as an internal or external command,
> operable program or batch file.
> error Command failed with exit code 1.
> 
> lerna ERR! yarn run build exited 1 in '@loadable/server'
> lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

What am I missing?

The first time it happened - lerna was not recognized, I installed it manually.
Then what you see above - I insalled shx manually.
Now babel is not recognized.

I have a feeling I'm not on the right path (figuratively). What am I missing?

**Comment by neoziro** [comment]
You should run `yarn` at the root of the repository first. So to resume:

**In the root**

```bash
yarn && yarn build
```

**In the example**

```bash
yarn dev
```

**Comment by mikehdt** [comment]
That works, but then there's a problem -- the server for this example goes kind of crazy.
```
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] starting `babel-node src/server/main.js`
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] starting `babel-node src/server/main.js`
```
(repeated, in varying forms of it 'restarting due to changes')

This is on Mac running Mojave 10.14.3. Checked out the repo, built the component, installed packages for the example and ran `yarn dev` to start it (yarn 1.13.0).

Are you able to also observe this behaviour?

**Comment by neoziro** [comment]
@mikehdt hmm no, I am sorry I didn't experience this kind of behaviour. Anyone could help?

**Comment by valorloff** [comment]
Hi!
I confirm it:
```
yarn build:lib
$ webpack
/home/............/node_modules/webpack-cli/bin/cli.js:235
                                throw err;
                                ^
Error: /home/........./babel.config.js: Error while loading config - Cannot find module '../../packages/babel-plugin'
```

**Comment by theKashey** [comment]
could you post `babel.config.js` content here?

**Comment by zetekla** [comment]
Hello,
Thank you for your replies. I don't have babel.config.js but have .babelrc,
see below:
I appreciate if you could help.

{
  "presets": ["@babel/preset-env", "@babel/preset-react"],
  "plugins": [
    [ "module-resolver", {
      "root": [
        "./src"
      ],
      "alias": {
        "@lib": "./src/lib",
        "@test": "./src/test"
      }
    }],
    ["@babel/plugin-syntax-dynamic-import"],
    ["dynamic-import-node-babel-7"],
    ["lodash", { "id": ["lodash", "recompose"] }],
    ["@babel/plugin-transform-runtime", { "regenerator": true }]
  ]
}

**Comment by zetekla** [comment]
and these are devDependencies:

"@babel/core": "^7.3.3",
"@babel/node": "^7.0.0",
"@babel/plugin-syntax-dynamic-import": "^7.0.0",
"@babel/plugin-transform-runtime": "^7.2.0",
"@babel/preset-env": "^7.1.0",
"@babel/preset-react": "^7.0.0",
"babel-core": "^7.0.0-bridge.0",
"babel-eslint": "^10.0.1",
"babel-loader": "^7.1.5",
"babel-plugin-dynamic-import-node-babel-7": "^2.0.7",
"babel-plugin-lodash": "^3.3.4",
"babel-plugin-module-resolver": "^3.1.1",
"babel-plugin-transform-runtime": "^6.23.0",
"babel-preset-env": "^1.7.0",
"babel-preset-react": "^6.24.1",

**Comment by theKashey** [comment]
I mean - `/home/........./babel.config.js` contain an error. Could you should the source of exactly this file with an incorrect call to `require('../../packages/babel-plugin')` ?

**Comment by theKashey** [comment]
If you are using example from https://github.com/smooth-code/loadable-components/blob/4e99a97c5ae958c4f18ac82b7e1a3566bc81c912/examples/server-side-rendering/babel.config.js - probably you shall not do it, but require `@loadable/babel-plugin`

**Comment by neoziro** [comment]
Outdated.
