### ISSUE TITLE
Load a component from external server/CDN

### ISSUE THREAD

**Issue by zetekla** [smooth-code/loadable-components#147]
## 🚀 Feature Proposal
Perhaps, there have been questions from many SO threads about the ability to load and render React component from external host/servers

https://stackoverflow.com/a/44452714/5828821 (not sure as per faceyspacey suggested, how implementation willl be with their repo https://github.com/faceyspacey/universal-demo)
https://github.com/smooth-code/loadable-components/issues/138

## Motivation

The point is that, we encounter use cases, where we need to allow Library users to be able to specify a JSON schema including many key fields whose value contain the path to a component.
We use proxy but that simply is not enough to solve problem importing over wire.

Also, we try not to use eval(), dangerouslyInnerHTML and other dirty hacks to load and render the script. Babel loader is also another pain to get it resolved.

Any chance this library supports ? or interact with other library to achieve ? Thanks in advance.

**Comment by theKashey** [comment]
Is this different from https://github.com/smooth-code/loadable-components/issues/138?

**Comment by neoziro** [comment]
I close it, it will not happen any time soon.
