### ISSUE TITLE
@loadable/babel-plugin does not work with razzle (babel 6)

### ISSUE THREAD

**Issue by marcneander** [smooth-code/loadable-components#150]
Hello again! I'm super stoked about this lib and really want to use it. We're running our build tasks with `razzle` which is slightly behind, using babel 6 in current stable. If I'm adding `@loadable/babel-plugin` in my `.babelrc` I'm getting this:

```
ERROR in ./src/client.js
Module build failed (from ./node_modules/razzle/node_modules/babel-loader/lib/index.js):
TypeError: template.ast is not a function
    at isReadyProperty (/Users/marc/src/with-react-loadable/node_modules/@loadable/babel-plugin/lib/properties/isReady.js:9:29)
```

Not sure what it would mean to support both babel 6 and 7 but I think it would be a huge improvement to the lib.

```
npx create-razzle-app razzle-loadable-test
cd razzle-loadable-test
echo "{\"presets\": [\"razzle/babel\"],\"plugins\": [\"@loadable/babel-plugin\"]}" > .babelrc
yarn start
```

**Comment by lucasterra** [comment]
Try `razzle@3.0.0-alpha.0` it has Babel 7

**Comment by neoziro** [comment]
Hello @marcneander, I am sorry but Babel 6 will not be supported. As @lucasterra said, you should try to upgrade to razzle v3 or just wait for v3 to be stable.

**Comment by neoziro** [comment]
I am very sorry, but we have to move forward, I prefer to work on new features than supporting old version! I hope you understand!

**Comment by marcneander** [comment]
@neoziro It's fine. Been trying for a couple of hours to get @loadable ssr to work with razzle 3 without success. It seems like the loadable-stats.json file is somehow not generated properly. I'm getting `SSR requires `@loadable/babel`, please install it` even though I'm using the babel-plugin. Somehow the chunkExtractor is undefined inside `@loadable/component`.

Might have time to get you an example during the day. I think this repo would benefit from having an example with razzle since so many people are using it.

**Comment by neoziro** [comment]
@marcneander OK, if someone succeeded running it with Razzle, feel free to add an example!

**Comment by valorloff** [comment]
without success:
```
Failed to compile.
./src/App.js 17:11
Module parse failed: Unexpected token (17:11)
You may need an appropriate loader to handle this file type.
|   },
|   requireAsync: function requireAsync() {
>     return import(
|     /* webpackChunkName: "NotFound" */
```

**Comment by wagnerjsilva** [comment]
Just wanted to flag a similar issues with tests is still happening today.

https://github.com/smooth-code/loadable-components/issues/396
