### ISSUE TITLE
SSR Example with HMR

### ISSUE THREAD

**Issue by davidfloegel** [smooth-code/loadable-components#151]
Hello again,

I'm wondering if it's possible to get a working example for @loadable/component with SSR and HMR? (For example [update the existing example](https://github.com/smooth-code/loadable-components/tree/master/examples/server-side-rendering))
We've been trying for days now but nothing seems to work...

That would be amazing. Thanks a lot!

**Comment by kennethlmartin** [comment]
Not sure if this is of help to you but this is what I have been doing to implement SSR with HMR in v4.
https://github.com/kennethlmartin/react-archetype

I attempted to upgrade to the latest v5 but ran into an issue #153. Until that's resolved I'll be sticking with v4.
https://github.com/kennethlmartin/react-archetype/tree/loadable-v5

**Comment by davidfloegel** [comment]
@kennethlmartin thanks dude I'll have a look at it :)

**Comment by valorloff** [comment]
+ 100 
to HMR update SSR example!

**Comment by zeppelinen** [comment]
If anyone googling for HMR/SSR example will come across this page, here's my example:

**loadableStats.js**
```
const axios = require('axios');
const fs = require('fs');
const path = require('path');
const assetsPath = '/assets/loadable-stats.json';

// eslint-disable-next-line consistent-return
async function loadableStats(origin) {
  if (!module.hot) {
    try {
      fs.readFile(
        path.resolve(`./build/public/assets/loadable-stats.json`),
        'utf-8',
        (err, data) => {
          if (err) throw err;
          return JSON.parse(data);
        }
      );
    } catch ({ err }) {
      throw new Error(err);
    }
  } else {
    try {
      console.debug(`Using loadable-assets.json from: ${origin}${assetsPath}`);
      const { data } = await axios.get(`${origin}${assetsPath}`);
      return data;
    } catch ({ err }) {
      throw new Error(err);
    }
  }
}

export default loadableStats;
```
**whatever.js**
```
import loadableStats from './loadableStats';

const origin = 'http://localhost:3000';      // adapt to your dev environment
const extractor = new ChunkExtractor({
      stats: await loadableStats(origin),
      entrypoints: ['client'],
    });
```
