### ISSUE TITLE
Add option to emit file in @loadble/webpack-plugin

### ISSUE THREAD

**Issue by marcneander** [smooth-code/loadable-components#158]
## 🚀 Feature Proposal

Using `@loadable` in server rendered apps using webpack-dev-server that keeps output in memory is not working very well right now. One way to solve this would be to have an option to emit the file to disk.

I don't have any knowledge regarding the webpack API and if it's safe or not to do this. However I know there are atleast two webpack plugins that does this today already.

- https://github.com/danethurber/webpack-manifest-plugin
- https://github.com/ztoben/assets-webpack-plugin

## Motivation

I think think library is awesome and I've spent a couple of days implementing `@loadable` into our frontend platform. It works great but we also were in the process of switching build-system to `razzle` and that's where I ran into a wall.

Razzle runs two instances of webpack (one for the server and one for the client). The client side of webpack generates the `loadable-stats.json` file and is kept in memory during development (`razzle start`). It's currently very hard for the server to get a hold of this file...
 
## Example

I've forked the `@loadable/webpack-plugin` and made some quick changes that seems to work well for us. As previously stated, I don't know the implications of doing it like I have. I would need to get familiar with the webpack plugins API to tackle this issue. 

Here's a gist of the changes I've done: https://gist.github.com/marcneander/2bddd49fd3bd8c6065d8e51b221168a4

Right now I'm not capable of doing much coding outside of work. I might be able to convince my manager to let me spend a few hours on this.

**Comment by dlebedynskyi** [comment]
@marcneander  I mostly copied code from react-lodable-ssr-addon. we can check for file already exist. I don't think it will be a problem anyways. 

@neoziro I think behavior as is, don't write to disk by default is fine. 
We can add just option for writeToDisk (default: false) and do that by user request. This is way that [webpack-assets-manifest does it](https://github.com/webdeveric/webpack-assets-manifest#writetodisk). 

Imo: 
```
 new LoadablePlugin({writeToDisk: true, filename: path.resolve(absoluteFilePath)})
``` 
work fine.

Not much of webpack expert myself. 
But have been digging quite a bit throw lodable-* packages. I can open PR if needed.

**Comment by marcneander** [comment]
@dlebedynskyi Atleast when using `razzle`. If we don't write the file even though it already exists we will get bugs if we do `razzle build` before `razzle start`. Since `razzle start` won't cleanup build directory but would use the `loadable-stats.json` file from `razzle build` output.

**Comment by dlebedynskyi** [comment]
Open PR https://github.com/smooth-code/loadable-components/pull/161

@marcneander  I tested without clean up on our build process and have not seen any issues around writing over old file after build.  
Please feel free to test on your razzle setup.

**Comment by neoziro** [comment]
Already done!
