### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by grydstedt** [smooth-code/loadable-components#16]
Is there a way you could do a to show the component right away if it's there, but delay showing the loading spinner only for at least some time if still loading?

**Comment by neoziro** [comment]
There is an example of delay in the readme: https://github.com/smooth-code/loadable-components#delay

It defines a minimum delay to avoid loader blinking. If you want to delay the appearance of the loader, you can do it in the loader component itself, an example:

```js
import React from 'react'

class Loader extends React.Component {
  state = { show: false }

  componentDidMount() {
    // Wait 300ms before showing it
    this.timeout = setTimeout(() => this.setState({ show: true }), 300)
  }

  componentWillUnmount() {
    clearTimeout(this.timeout)
  }

  render() {
    return this.state.show ? 'Loading' : null
  }
}
