### ISSUE TITLE
Named imports from icon library

### ISSUE THREAD

**Issue by cezarcarvalhaes** [smooth-code/loadable-components#160]
Had an issue regarding importing named components from fortawesome's icon library. I scoured the README, and found a previous answer regarding named imports in issues, but still couldn't get it to work. Any assistance would be greatly appreciated.

A static import works like so (this works): 
```javascript
import {  faTwitter, faFacebookMessenger } from '@fortawesome/free-brands-svg-icons';
```

However, I'd like to reduce bundle size and lazy load these icons, yet can't get them to render. I've tried the code below, and the icons can't be found. 

```javascript
const TwitterIcon = loadable(async () => {
const { faTwitter } = await import('@fortawesome/free-brands-svg-icons')
return (props) => <faTwitter {...props} />
});
```

I've also tried (not expecting it to work) with no luck: 
```javascript
const twitterIcon = loadable(()=> import('@fortawesome/free-brands-svg-icons'));
```

**Comment by neoziro** [comment]
Hello @cezarcarvalhaes, icons from '@fortawesome/free-brands-svg-icons' are not meant to use with React. It is just SVG icons. That's why it does not work.

**Comment by cezarcarvalhaes** [comment]
Thanks for the quick reply @neoziro, (and if you're in the US, Happy Thanksgiving!). I'm actually using [react-fontawesome](https://github.com/FortAwesome/react-fontawesome), which is meant to work with react. Here's some sample syntax: 

```javascript
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faStroopwafel } from '@fortawesome/free-solid-svg-icons'

export const Food = () => (
  <div>
    Favorite Food: <FontAwesomeIcon icon= {stroopwafel} />
  </div>
)

```

Using static imports as described above works great, however, when using loadable to import the icon, the icons aren't found.

**Comment by neoziro** [comment]
You can do it using `loadable.lib`:

```js
import loadable from '@loadable/component'

const Fontawesome = loadable.lib(() => import('@fortawesome/react-fontawesome')

const Food = () => (
  <Fontawesome>
    ({ FontAwesomeIcon }) => <FontAwesomeIcon />
  </Fontawesome>
)
```
