### ISSUE TITLE
Error when using react-router with SSR example in production

### ISSUE THREAD

**Issue by WingmanImd** [smooth-code/loadable-components#169]
Hello,
So I have cloned the SSR example and added a basic react router in my <App/>.
The example works in dev mode but after building the app when I try to change the page I get the error "Uncaught SyntaxError: Unexpected token <". This seems to be caused by the fact that the "server" component is loaded(the one containing the HTML) instead of the the client one.

Any ideas? Thanks!

The pages are loaded using loadable()

**Comment by neoziro** [comment]
Hello @WingmanImd, I am sorry I don't have enough information to help you, please provide a repro repository.

**Comment by WingmanImd** [comment]
You can check the code here: [https://github.com/WingmanImd/test-ssr-with-loadable-components-and-router](url) Thanks! As you can see I both tried using loadable inside the route components and as a route component.

**Comment by neoziro** [comment]
Hello @WingmanImd, I found the issue:

In your `webpack.config.babel.js`, replace:

```
publicPath: `/dist/${target}`,
```

by

```
publicPath: `/dist/${target}/`,
```

Everything works now!

**Comment by WingmanImd** [comment]
Thanks a lot. Didn't expect that to be from the publicPath.
