### ISSUE TITLE
Thank you for this library!

### ISSUE THREAD

**Issue by antonybudianto** [smooth-code/loadable-components#17]
Hi, I just want to thank you for this awesome library, this is actually the only one lib that worked perfectly with my https://github.com/antonybudianto/cra-universal which used react 16 and `renderToNodeStream`.
I tried many other solutions but they didn't work well despite their setup being very complicated.
I'll mention and recommend this repo in my repo wiki for Code-splitting solution

Keep it up! 👍

**Comment by neoziro** [comment]
@antonybudianto thank you! There is still several issues to solve. Will try to make it better as soon as I have enough time to work on.

**Comment by neoziro** [comment]
Thanks! v1 should fix all SSR issues!
