### ISSUE TITLE
named and multiple entry points

### ISSUE THREAD

**Issue by xFloooo** [smooth-code/loadable-components#172]
## 💬 Questions and Help

Can I use named entry points?
Can I use multiple entry points?
```javascript
// webpack.conf
entry: {
    app: `./src/client/main-${target}.js`
}
```

```javascript
// express render middleware
...
nodeExtractor.requireEntrypoint()
```
loadable throw error `Invariant Violation: loadable: cannot find main in stats`

**Comment by neoziro** [comment]
Hello @xFloooo, you forgot the name!

```js
nodeExtractor.requireEntrypoint('app')
```

See [the documention](https://github.com/smooth-code/loadable-components/blob/master/packages/server/README.md#chunkextractorrequireentrypoint) for more information.
