### ISSUE TITLE
Rules for valid full dynamic imports?

### ISSUE THREAD

**Issue by chacestew** [smooth-code/loadable-components#175]
I'm adding this to a codebase incrementally, and running into trouble compiling when using full dynamic imports. I haven't been able to find more info in these docs or webpack's (webpack only states that `import(foo)` is impossible).

Example importer:

```js
const Loader = loadable(props => import (`./Pages/${props.path}`)
```

Example folder:

```
Pages /
  - Home /
    - index.js
  - Login /
    - index.js
  - Account /
    - Settings /
      - index.js
    - Permissions /
      - index.js
```

My questions:

1. Can full dynamic imports have different nesting inside the indicated directory? e.g. `import('./Pages/{path}')` can eval to `import('./Pages/Login')` or `import('./Pages/Account/Settings')`?

2. Is it possible to import statically from `./Pages` at the same time or would this create conflicts with dynamic imports? I've run into broken compilations due to `There are multiple modules with names that only differ in casing` errors on every file nested in `Pages` - I think it might be because some pages are imported statically, some dynamically.

Appreciate your time.

**Comment by neoziro** [comment]
Hello @chacestew,

1. Yes it should work for nested directories.

2. Yes you can import statically and dynamically, to avoid duplicates be careful of having the same "chunkName". `@loadable/babel-plugin` generates chunkName for you. To be able to know the way it is generated, you can run babel on your file and examine the code generated. You will see how the chunkName is determined.

I hope it answers your questions!
