### ISSUE TITLE
@loadable/babel-plugin doesn't work with declared functions

### ISSUE THREAD

**Issue by lfantone** [smooth-code/loadable-components#188]
## 🐛 Bug Report

I have a case where I need to pass a `loader` function to a `@loadable/component` and the `@loadable/babel-plugin` do not work as expected. The function passed as an argument, won't be capture by the babel plugin, making the `InnerComponent` fail on SSR with a
> SSR requires `@loadable/babel`, please install it

## To Reproduce
Running the following will produce the above error when trying to render on server-side:

```jsx
// react-router v4 route.js file

const loadBuses = () =>
  import(/* webpackChunkName: "buses" */ './components/BusesContainer/BusesContainer.page');

export default [
  {
    path: '/',
    exact: true,
    component: asyncComponent({
      loader: loadBuses
    })
  }];
```

```jsx
// asyncComponent.js
export function asyncComponent({ loader }) {
  const LoadableComponent = loadable(loader);

  const AsyncRouteComponent = props => {
    return <LoadableComponent {...props} />;
  };

  return AsyncRouteComponent;
}
```

After running babel with the `@loadable/babel-plugin` outputs:

```js
var loadBuses = function loadBuses() {
  return import(
  /* webpackChunkName: "buses" */
  './components/BusesContainer/BusesContainer.page');
};
```

## Expected behavior

I'll expect that the `@loadable/babel-plugin` transpiles the **loader** function with the right methods so It can be used by `@loadable/component`:

```js
var loadBuses = function loadBuses() {
  return {
      chunkName: function chunkName() {
        return "buses";
      },
      isReady: function isReady(props) {
        if (typeof __webpack_modules__ !== 'undefined') {
          return !!__webpack_modules__[this.resolve(props)];
        }

        return false;
      },
      requireAsync: function requireAsync() {
        return import(
        /* webpackChunkName: "buses" */
        './components/BusesContainer/BusesContainer.page');
      },
      requireSync: function requireSync(props) {
        var id = this.resolve(props);

        if (typeof __webpack_require__ !== 'undefined') {
          return __webpack_require__(id);
        }

        return eval('module.require')(id);
      },
      resolve: function resolve() {
        if (require.resolveWeak) {
          return require.resolveWeak("./components/BusesContainer/BusesContainer.page");
        }

        return require('path').resolve(__dirname, "./components/BusesContainer/BusesContainer.page");
      }
    }
```

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

```bash
## System:
 - OS: macOS 10.14.1
 - CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
 - Memory: 555.12 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 8.10.0 - /usr/local/bin/node
 - Yarn: 1.12.3 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/.npm-packages/bin/npm
## npmPackages:
 - @loadable/babel-plugin: ^5.2.2 => 5.2.2
 - @loadable/component: ^5.2.2 => 5.2.2
 - @loadable/server: ^5.2.2 => 5.2.2
 - @loadable/webpack-plugin: ^5.2.2 => 5.2.2
```

**Comment by theKashey** [comment]
This is the reason why I don’t like full dynamic imports. 

I am not sure that current way is the right way - too many magic. 

Proposal - simplify. Keep only import, and let the system, nodejs or Webpack, manage the rest. Almost as I did in imported. 

More details: using Babel plugin find all imports with placeholders and do the Webpacks job - unroll one import to the multiple. Or find files by a glob pattern and replace one import by a ‘switch’

Then - you will be able to load the “right” page for the props, more correct name chunks, and make things much simpler.

Does it sounds doable?

**Comment by lfantone** [comment]
Hi @neoziro, thanks for the response.
Actually in my case I can't solved it that way, because the use of the `@loadable/component` is not in the same library than the import and I should pass it function as an argument that will be later used by `loadable`. Also, the project that is running under babel doesn't include the `@loadable/component`.

I was thinking that a way of solving this will be to parse those _imports function_ if they have some kind of predefined comment. Something similar like the way that _webpackChunkName_ comment works, for example:
```js
/* babelLoadableFunction /*
const loader = () => import('./component/BusesContainer/BusesContainer.page');
```
After babel:
```js
var loader = function loadBuses() {
  return {
      chunkName: function chunkName() {
        return "buses";
      },
      isReady: function isReady(props) {
        if (typeof __webpack_modules__ !== 'undefined') {
          return !!__webpack_modules__[this.resolve(props)];
        }

        return false;
      },
      requireAsync: function requireAsync() {
        return import(
        /* webpackChunkName: "buses" */
        './components/BusesContainer/BusesContainer.page');
      },
      requireSync: function requireSync(props) {
        var id = this.resolve(props);

        if (typeof __webpack_require__ !== 'undefined') {
          return __webpack_require__(id);
        }

        return eval('module.require')(id);
      },
      resolve: function resolve() {
        if (require.resolveWeak) {
          return require.resolveWeak("./components/BusesContainer/BusesContainer.page");
        }

        return require('path').resolve(__dirname, "./components/BusesContainer/BusesContainer.page");
      }
    }
```

And then the `loader` function could be use in any place with `loadable(loader)`.
Is that even possible?

**Comment by neoziro** [comment]
Yes it is a good idea! Let's do it with `/* #__LOADABLE__# */`. Any PR is welcome!

**Comment by neoziro** [comment]
Done in #192

**Comment by lfantone** [comment]
Amazing!! 🎊
