### ISSUE TITLE
requireEntrypoint returns undefined value

### ISSUE THREAD

**Issue by killiansc** [smooth-code/loadable-components#189]
Hello,

I am running into troubles with SSR + multiple entry points. None of the issues already solved seem to have the same problem.

My issue is that on the server-side, when doing:

```javascript
const nodeExtractor = new ChunkExtractor({
    statsFile: './public/build/js/node/loadable-stats.json',
    entrypoints: ['MyPage'],
});
const { default: App } = nodeExtractor.requireEntrypoint('MyPage');
```

`App` comes as `undefined`, even though `loadable-stats.json` does contain the name of the entrypoint as a key with the right file as a value. Even if I do not give an argument to `requireEntrypoint`, it comes as undefined - same if I don't give `entrypoints` to instantiate `ChunkExtractor` and keep the argument.

If I replace the last line with:

```javascript
const App = nodeExtractor.requireEntrypoint('MyPage');
```

`App` does not come as a string, a class or a function but an object. `React.createElement` therefore fails.

My webpack configuration is as follow:

```javascript
// ...
// ... define some variables that we'll use in the configuration below
// ...

// The object that'll hold webpack configuration
const getConfig = (target) => ({
    entry: {
        MyPage: ['MyPage'],
        MyOtherPage: ['MyOtherPage'],
    },

    mode,

    name: target,

    target,

    module: {
        rules: [{
            test: /\.jsx?$/,
            exclude: /(node_modules)/,
            use: {
                loader: 'babel-loader',
                options: {
                    caller: { target },
                },
            },
        }],
        noParse: [/aws-sdk/],
    },

    resolve: {
        extensions: ['.js', '.jsx'],
    },

    externals: target === 'node' ? ['@loadable/component', nodeExternals()] : undefined,

    output: {
        filename,
        chunkFilename,
        path: path.resolve(__dirname, 'public', 'build', 'js', target),
        publicPath: `/build/js/${target}`,
        libraryTarget: target === 'node' ? 'commonjs2' : undefined,
    },

    plugins: [
        // Define global constants to be used in the JS files
        new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: JSON.stringify(process.env.NODE_ENV || 'local'),
            },
        }),

        new webpack.NamedChunksPlugin((chunk) => {
            if (chunk.name) {
                return chunk.name;
            }

            const n = [];
            chunk.forEachModule((m) => n.push(path.relative(m.context, m.request)));
            return n.join('_');
        }),
        // Name all modules because adding a new page will bust all cache
        new NameAllModulesPlugin(),

        // Add versioning to files with a manifest files as basis
        new Versioning({
            manifestPath: path.join(__dirname, './public/build/rev-manifest.json'),
            basePath: `js/${target}/`,
            cleanup: false,
        }),

        new LoadablePlugin(),
    ],

    devtool,

    optimization: {
        namedModules: true,
        providedExports: true,
        usedExports: true,
        concatenateModules: true,
        noEmitOnErrors,
        minimizer,
        splitChunks: {
            cacheGroups: {
                chunks: CHUNKS,
                // No vendor chunk on the server-side
                ...target !== 'node' && {
                    vendors: {
                        test: (module) => !skip(module) && isExternal(module),
                        name: 'vendor',
                        filename: filenameVendor,
                        chunks: 'all',
                        minChunks: 3,
                    },
                },
                commons: {
                    test: (module) => !skip(module) && !isExternal(module),
                    name: 'common',
                    filename: filenameCommon,
                    chunks: 'initial',
                    minChunks: 3,
                },
            },
        },
    },

    performance: {
        hints: false,
    },

    ...target !== 'node' && {
        resolveLoader: {
            modules: ['node_modules'],
        },
    },

    // Bail out on the first error
    bail: true,

    watchOptions: {
        aggregateTimeout: 100,
        poll: 1000,
        ignored: /node_modules/,
    },
});
```

I can give more details if necessary, but I find myself completely stuck here. I followed the example we can find [here](https://github.com/smooth-code/loadable-components/tree/master/examples/server-side-rendering).

I am running:
* **webpack** 4.23.1
* **loadable** 5.2.2

**Comment by killiansc** [comment]
I got it working, mixing both the official documentation and the server-side rendering code example. Maybe the documentation should be updated? The solution was to do as follow:

```
        const nodeExtractor = new ChunkExtractor({
            statsFile: './public/build/js/node/loadable-stats.json',
            entrypoints: [pageName],
        });

        const webExtractor = new ChunkExtractor({
            statsFile: './public/build/js/web/loadable-stats.json',
            entrypoints: [pageName],
        });

        // Render page
        const html = ReactDOMServer.renderToString(
            React.createElement(
                ChunkExtractorManager,
                {
                    extractor: nodeExtractor,
                },
                React.createElement(Page)
            )
        );
```

And return something like:

```
        return `<div id="redux-page-container">${html}</div>${webExtractor.getScriptTags()}`;
```

So the node extractor is used for the server-side rendering, and the web extractor is used to get the browser-side compiled files.

**Comment by killiansc** [comment]
Running into some other problems. Whenever I use `const MyComponent = loadable(() => import('./MyComponent'));`, the browser-side does not match the  server-side for a short period of time and I have a `Did not expect server HTML to contain a <div> in <div>`. So the component disappears for a little time. Then, I can see a request to get `MyComponent` is done in the network tab, and when it is fetched, everything is back to normal.

It would be great to have full examples with the expected output of `loadable-stats.json` for example. Now I have no clue what the problem is. Maybe the problem is that `window.__LOADABLE_REQUIRED_CHUNKS__` is an empty array, but should contain `MyComponent`? Maybe the chunk that is made for `MyComponent` should be a dependency of the main app in `loadable-stats.json`? If someone can give help, that would be highly appreciated :-)

**Comment by dlebedynskyi** [comment]
@killiansc  it look like you hydration process if failing.  

Could there be some sort of logic that makes server don't match client? like setState in componentDidMount? In my experience this kind of issues have nothing to do with loadable.

To help resolve problem
1. try replace MyComponent.js code with `export default () => <div>test</div>`. 
 if issue is gone, then it is a problem with your code in component
2. if remains 
 - make sure that you have `loadableReady` on client entry 
 - are doing `getScriptTags` on server side. 

Regarding `loadable-stats.json` it is basically webpack stats  with something like  
 ```
- hash
- publicPath
- assetsByChunkName
- assets
- entrypoints
- ...
```  

as example in my build I have `commons~agree~fullTerms` chunk in assetsByChunkName, 
so on ssr page in page source I will see 
```
<script>window.__LOADABLE_REQUIRED_CHUNKS__ = ["commons~agree~fullTerms~glPortal", ...
```

**Comment by killiansc** [comment]
@dlebedynskyi thanks for your answer,

Without loadable, I do not have this hydratation problem. So I guess it is unlikely the problem comes from a `setState` in a `componentDidMount`.

I tried your solutions:

1. Same problem, `Warning: Expected server HTML to contain a matching <div> in <div>`
2. I already have that on the client and server side

Client-side
```javascript
        loadableReady(() => {

            // Redux stuff
            const initialState = window.__INITIAL_STATE__;
            const currentPage = window.__PAGE__;

            delete window.__INITIAL_STATE__;

            if (initialState && currentPage) {
                let middleware;

                if (process.env.NODE_ENV === 'production') {
                    middleware = applyMiddleware(thunkMiddleware);
                } else {
                    const devTools = typeof window.__REDUX_DEVTOOLS_EXTENSION__ === 'function' ? window.__REDUX_DEVTOOLS_EXTENSION__() : (f) => f;
                    const middles = [thunkMiddleware];

                    middleware = compose(
                        applyMiddleware(...middles),
                        devTools
                    );
                }

                const store = createStore(reducers, initialState, middleware);

                const provider = (
                    <Provider store={store}>
                        <Master pageName={currentPage}>
                            <Page />
                        </Master>
                    </Provider>
                );

                hydrate(provider, document.getElementById('redux-page-container'));
            }
        });
```

Server-side

```javascript
return `<div id="redux-page-container">${html}</div>${webExtractor.getScriptTags()}`;
```

About `loadable-stats.json`, if `MyPage` uses `const MyComponent = loadable(() => import('./MyComponent'));`

* does it means I should have, on the server-side, `<script>window.__LOADABLE_REQUIRED_CHUNKS__ = ["MyComponent", ...`? If yes, that is not the case.
* if not, does that mean I should have an async script returned by `getScriptTags` linking `MyComponent`? Because that is neither the case. 

Anyway, `MyComponent` is actually somehow fetched - I wonder how but that's loadable-components internals I guess - but there is this hydration problem I detailed in the second post...

**Comment by killiansc** [comment]
Fixed it. I used only the `webExtractor` and ditched the `nodeExtractor` to get it working. Thanks!

**Comment by gabsprates** [comment]
Hi @killiansc. At https://github.com/smooth-code/loadable-components/issues/189#issuecomment-448616635, how did get the `Page` component?

I'm having a similar issue here, the return of my `nodeExtractor.requireEntrypoint()` is:

```json
{
  ids: [ 'styles~._assets_j' ],
  modules: {
    './a/lot/of/files/index.scss': [Function: ./a/lot/of/files/index.scss],
    // ...
  }
}
```

It doesn't have an `default` prop, but I have that in `loadable-stats.json`:

```json
// ...
"entrypoints": {
  "main": {
    "chunks": [
      "styles~._assets_j",
      "main~._a"
    ],
    "assets": [
      "styles~._assets_jc3e9311.css",
      "styles~._assets_j8d9f6b8eb8310464fbf9.js",
      "main~._ab028a8a6f037782e0c52.js"
    ],
    "children": {},
    "childAssets": {}
  }
},
// ...
```

I'm using TypeScript with SASS and I only have the entrypoint `main` in files (as below) and the  `js/main-web.tsx` and `js/main-node.tsx`, just like the [example here](https://github.com/smooth-code/loadable-components/tree/master/examples/server-side-rendering/src/client); and I only `import` my `import "../sass/main.scss";` in my `js/App.tsx` file.

```js
entry: [
    "core-js/stable",
    "regenerator-runtime/runtime",
    path.resolve(__dirname, `./js/main-${isNode ? "node" : "web"}.tsx`)
],
```

I also have a cache group on webpack config to group my styles and extract that with MiniCssExtractPlugin:

```js
optimization: {
    splitChunks: {
        cacheGroups: {
            styles: {
                name: "styles",
                test: /\.s?css$/,
                maxSize: 5000000,
                chunks: "all",
                enforce: true
            }
        }
    }
},
```

If anyone else can help, I'll be thankfully.

**Comment by theKashey** [comment]
```js
requireEntrypoint(entrypoint) {
    entrypoint = entrypoint || this.entrypoints[0] <---
    // this.entrypoints[0] should be "main"
```
Please try `requireEntryPoint("main")`, and could you please add debug information (directly in node_modules) to shred some light about what is actually in all required variables, and why it's `undefined`?
