### ISSUE TITLE
Component is rendered twice

### ISSUE THREAD

**Issue by alexseitsinger** [smooth-code/loadable-components#191]
It seems that upon initially loading a page when using `@loadable/component` and `@loadable/server` the component is rendered twice. The first render loads correctly, using the proper initial state from the server, then the component instantly re-renders (without any state as its wiped from the DOM once its used), and the component doesn't produce the correct output. 

You can notice the double-rendering by referring to the `console.log` output which contains two `@@router/LOCATION_CHANGE` events in a row.  This stops happening as soon as loadable components is not used any longer for the route.

An example project that has the double rendering can be found [here](https://github.com/alexseitsinger/double-rendering-example).

**Comment by neoziro** [comment]
Hello @alexseitsinger, right now I don't have time to investigate it. Maybe someone could give a look?

**Comment by neoziro** [comment]
Closed for inactivity.
