### ISSUE TITLE
Not getting chunks SSR

### ISSUE THREAD

**Issue by yyynnn** [smooth-code/loadable-components#193]
Hi, got a problem here.

Using ssr with ts-node ts server, and not getting any loadable chunks. Getting this in extactor:

```
​get -> scriptTags <script>window.__LOADABLE_REQUIRED_CHUNKS__ = [];</script>
<script async data-chunk="app" src="/bundle.app.js"></script>
​get -> linkTags <link data-chunk="app" rel="preload" as="script" href="/bundle.app.js">
​get -> scriptTags <script>window.__LOADABLE_REQUIRED_CHUNKS__ = [];</script>
<script async data-chunk="app" src="/bundle.app.js"></script>
​get -> linkTags <link data-chunk="app" rel="preload" as="script" href="/bundle.app.js">
```

but app loads fine and loadable components load fine too.

**Comment by neoziro** [comment]
Hello @yyynnn are you sure to correctly render all the tree server-side before calling `getScriptTags` ?

**Comment by yyynnn** [comment]
First issue was resolved just by setting a function with loadable import outside of map.
```javascript

const getLoadableComponent = name => {
  return loadable(() => import(`lazies/${name}.lazy`))
}

export const PageGenerator = ({ data }) => {
  return (
    <React.Fragment>
      {data.map(({ name, id }: ComponentProps, i) => {
        const Component = getLoadableComponent(name)
        return (
          <React.Fragment key={i}>
            <Component id={id} />
          </React.Fragment>
        )
      })}
    </React.Fragment>
  )
}
```

With second issue - how to force getScriptTags to get main bundle out of itself?

**Comment by neoziro** [comment]
Hello @yyynnn, thanks for precision, I have better comprehension of your issue.

You are creating a dynamic component inside another one, this is an anti-pattern in React, when you do that, React will remount component each time because it is a new instance. All your components must be define statically.

I see what you want to achieve and there is an easy way to do it properly with Loadable Components:

```js
const Loadable = loadable(props => import(`lazies/${props.name}.lazy`))

export const PageGenerator = ({ data }) => {
  return (
    <React.Fragment>
      {data.map(({ name, id }: ComponentProps) => <Loadable key={id} name={name} />)}
    </React.Fragment>
  )
}
```

I hope it will solve your problem!

**Comment by yyynnn** [comment]
That one works client-side, but not while SSR. it cant find module yet path to that module is ok.

`{ Error: Cannot find module 'path/to/module/'`

**Comment by hemmxwxsoo** [comment]
Thank you @neoziro.

I have the same problem. Nothing in `__LOADABLE_REQUIRED_CHUNKS__.`, mark-up is rendered very well. I think I have to render somthing before getting HTTP request. but I don't know how to do that. Do I have to use some functions?


```
// ./src/app_for_server_side_rendering.tsx
export default class App extends React.Component {
    render () {
        return (
            <StaticRouter context={{}} location={this.props.location}>
                <Something/>
            </StaticRouter>
        );
    }
};
```

```
// Server
import App from 'Public/dist/static/js/app_for_server_side_rendering';
import stats from 'Public/dist/loadable-stats.json';

const chunk_extractor = new Chunk_extractor({ stats, entrypoints:['app'] });
let stream:NodeJS.ReadableStream; 

stream = render_to_node_stream(chunk_extractor.collectChunks(
    <App location={request.url} />
));
response.write(this.templates.template_up_to_start_body_element!);
stream.pipe(response, { end:false });
stream.on('end', () => {
    response.end(`{chunk_extractor.getScriptTags()}${this.templates.template_after_start_body_element}`);
});
```

**Comment by bertho-zero** [comment]
I currently have the same problem, I think the Context is not the same.
Each takes one of its node_modules.

**Comment by bertho-zero** [comment]
https://github.com/smooth-code/loadable-components/blob/0d3e7dee3045737be1709ffa300aca083aef457c/packages/server/src/ChunkExtractor.js#L274-L276

`collectChunks` should be able to take a context as a second parameter, which would be passed in props to ChunkExtractorManager and used in place of the Context if defined.

https://github.com/reduxjs/react-redux/blob/ab7745062b2249e3914400452a9c114b2007e969/src/components/Provider.js#L64

**Comment by bertho-zero** [comment]
I managed to get around the problem by doing:
```js
//app.js
import { __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED as LoadableSecret } from '@loadable/component';

const { Context: LoadableContext } = LoadableSecret;

const element = (
  <LoadableContext.Provider value={extractor}>
    {/* */}
  </LoadableContext.Provider>
);
```

I use the Context directly in my apps and I pass the extractor from the server.

**Comment by neoziro** [comment]
I understand your issue. Be careful of building your app correctly, server-side modules must be externals. I think we should document it. See https://github.com/smooth-code/loadable-components/blob/master/examples/server-side-rendering/webpack.config.babel.js#L40

I created an issue: https://github.com/smooth-code/loadable-components/issues/231

**Comment by bertho-zero** [comment]
I think it's enough to export the context, as react-redux does. My problem does not come from webpack but because in my monorepo I have several packages with a @loadable/components for each, and therefore a different context.

**Comment by neoziro** [comment]
You should try to have a single version of the package. You will likely have some bugs with other libraries.. Are you sure to not have any workaround?

**Comment by bertho-zero** [comment]
I have no problem with other libraries since they expose their Context. The workaround is to monitor the versions to have only one, the ideal would be to use the Context and have a stable code in all cases.

**Comment by neoziro** [comment]
@bertho-zero the context is exposed (https://github.com/smooth-code/loadable-components/blob/master/packages/component/src/index.js#L16), if you want to use it, you can use it, you will not be fired 😉.

**Comment by neoziro** [comment]
I don't want to expose it, I want to keep the library as simple as possible for users. I don't want to expose something that is not necessary and that encourage bad practices like duplicating libraries.

**Comment by bertho-zero** [comment]
Yes I use it like that but I do not really want to be fired. 😕

An application can be split into several parts, and if there is no lerna or yarn workspace then the problem is inevitable, it depends on the organizations.

**Comment by neoziro** [comment]
OK, you got a point, I understand that it could be difficult with multiple repositories. I will expose it for advanced use cases.

**Comment by neoziro** [comment]
Hmm I remember why I choose to do it like that. It is the method used by `styled-components`: https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/secretInternals.js#L6

If a library widely used like styled-components choose this strategy, I think there is probably a reason. For now I will not expose it, maybe in future. Feel free to use the "dangerous" context if you want, it will not likely change. I think you should try to migrate your base code to avoid duplicated modules. Loadable Components is not the only library that will give you issues.
