### ISSUE TITLE
Loadable extracted component window is not defined

### ISSUE THREAD

**Issue by bramvdpluijm** [smooth-code/loadable-components#194]
Hi There!

Today I managed to get loadable-components implemented into my React SSR project. In dev mode it works like a charm, but in production mode -when it runs on a server- I get a `ReferenceError: window is not defined`. 

I looked in the dist folder and saw that my loadable component's first rule looks like this: `(window.webpackJsonp=window.webpackJsonp||[]`. 

Does anyone know where the window.webpackJsonp comes from, maybe I'm missing something? Any help is appreciated.

**Comment by neoziro** [comment]
Hello @bramvdpluijm, hmm I think your setup is wrong but I don't have enough informations to help you! Do you have a repo example?

**Comment by neoziro** [comment]
Closed for inactivity.

**Comment by afsan007** [comment]
i have the same issue, my set up::
client/router.js::::
`
import React from 'react';
import Loadable from 'react-loadable';
export default [
    {
    ...Root,
    path: '/',
    routes:[{
            path:'/',
            component: Loadable({
                    loader: () => import('./containers/home'),
                    loading: ()=> <div>Loading...</div>
                })
        }]
}]
`
server/index.js :::
`
const Loadable = require('react-loadable');

require('@babel/register')({
        plugins: ["dynamic-import-node"]
})
const httpsServer = https.createServer({ key: privateKey, cert: certificate }, server)

Loadable.preloadAll().then(()=>{
        httpsServer.listen(process.env.PORT, () => {
                console.log(`server is running on port ${process.env.PORT}`)
                // console.log('Listening on port %d', server.address().port);
        });
})
`

i also use @babel/plugin-syntax-dynamic-import in side babelrc plugin

i use :
webpack
react 
redux
express
babel
