### ISSUE TITLE
Comparison with other libraries

### ISSUE THREAD

**Issue by oyeanuj** [smooth-code/loadable-components#2]
Hi @neoziro @vvo! This library looks great - thank you for open sourcing this! 

Its probably on your list, but if not, do consider providing a more indepth comparison with `react-loadable`, and `react-async-components`. 

Personally, I am curious to understand if SSR is the main difference, or are there other differences, as well, as how you approach SSR differently from those libraries. 

It'd be super helpful to folks, like me, trying to pick a library!

Thank you!

**Comment by neoziro** [comment]
@oyeanuj thank you!

I tried to [explain it in the readme](https://github.com/smooth-code/loadable-components/blob/master/README.md#other-solutions).

I also documented [how to implement a delay](https://github.com/smooth-code/loadable-components#delay) and [how to implement a timeout](https://github.com/smooth-code/loadable-components#timeout).

**Comment by dickenwong** [comment]
@neoziro I saw this in the documentation.
> react-loadable was the recommended way for React code splitting for a long time. However, today it is not maintained any more and it is not compatible with Webpack v4+ and Babel v7+.

I'm confused because I see commits on `react-loadable`, and it runs perfectly with webpack v4.
Except it is not real "open source", I'm curious to see currently any main difference from that library?

Thank you!

**Comment by theKashey** [comment]
"Commits"
<img width="402" alt="screen shot 2018-12-17 at 3 52 09 pm" src="https://user-images.githubusercontent.com/582410/50067157-c7b9fd80-0213-11e9-9ba8-db7a9b26a9df.png">

**Comment by theKashey** [comment]
Better - compare [this react-loadable fork](https://github.com/jaybe78/react-loadable/commits/master), with react-loadable. That's the answer.

**Comment by neoziro** [comment]
Since september, just a readme commit. Issues disabled, tons of PR not merged. For me it means « unmaitained ». It does not handle all webpack 4 stuff (agressive code splitting), it is not compatible with React Strict Mode.

Also it is just facts, if you are confident about it feel free to use it!

**Comment by dickenwong** [comment]
@oyeanuj  @theKashey  thanks!!

You're right. i didn't really pay attention to how "unmaintained" it is already.

Surely will try this library from now!
