### ISSUE TITLE
Migration from react-loadable to loadable-components

### ISSUE THREAD

**Issue by ogarich89** [smooth-code/loadable-components#200]
Hello!
Recently decided to abandon the react-loadable and go to use loadable-components.
The migration was successful, but there was a small problem. 
On the server side, when using the `getScriptTags()` and `getStyleTags()` methods, I only get entrypoints without chunks.

I don't know if this is a bug, but react-loadable was giving away all the chunks that were linked to the page.

Implementation using both libraries can be viewed https://github.com/ogarich89/iso

branch [master] - react-loadable
branch [feature/loadable-components] - loadable-components

Thank you in advance!

**Comment by neoziro** [comment]
Hello @ogarich89, I tried to run your project and I don't see any problem, I can see the bundle in html source. What is the problem?

**Comment by ogarich89** [comment]
I solved this problem on my side

> /src/server/index.jsx

    if (matchPath(pathname, route)) {
      if(route.initialAction) {
        acc.push(Promise.resolve(store.dispatch(route.initialAction(ctx.api, ctx.request))));
      }
      if(!extractor.chunks.length) {
        extractor.addChunk(route.chunkName);
      }
    }

When I insert a component, I check its chunkName and add it using the method `addChunk`

**Comment by neoziro** [comment]
Normally it collects all `import` made into a `loadable` components. Anyway if your problem is fixed good!

**Comment by ogarich89** [comment]
Is it normal that I define what chunk to add?

**Comment by neoziro** [comment]
No it is not normal, but your project is a bit complicated. I didn't dive completely into it.

**Comment by ogarich89** [comment]
Thanks, I will wait for an answer.

**Comment by jhornby** [comment]
https://github.com/smooth-code/loadable-components/issues/216 had a similar problem which he solved by ordering the @loadable/babel-plugin before the dynamic syntax import plugin.  Could you try that?

**Comment by ogarich89** [comment]
@jhornby 
Hi bro! You gave me an idea. Everything worked after deleting this line.
`nodeModules['@loadable/server'] =  'commonjs @loadable/server';`
in the file `config/webpack/server.config.babel.js`;

https://github.com/ogarich89/iso/blob/master/config/webpack/server.config.babel.js 
//11 feature/loadable-components

**Comment by ogarich89** [comment]
@jhornby I do not want to describe what was the problem (it will take a lot of time), but it is connected with the library update. Thanks again @jhornby @neoziro
