### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by ilgianfra** [smooth-code/loadable-components#204]
## 💬 Questions and Help

I am following the guide for the SSR, I arrived at the moment to split in chunks my views.
```
import loadable from '@loadable/component';
const App = loadable(() => import('../components/App'));
const Home = loadable(() => import('../components/Home'));
const About = loadable(() => import('../components/About'));

export default [
  {
    ...App,
    routes: [
      {
        ...Home,
        path: '/',
        exact: true
      },
      {
        ...About,
        path: '/about'
      }
    ]
  }
];

```
My first doubt was if I need to install @babel/plugin-syntax-dynamic-import or it is not needed. But I get a runtime error in both cases

> return import(... SyntaxError: Unexpected token import 

I guess it is because babel is not working well, but if i remove this the loadable components is creating just one build (like it should be).

Above my .babelrc
```{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    "@loadable/babel-plugin",
    // "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-transform-runtime",
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-export-namespace-from"
  ]
}
```
My pacakeges:
```
     "@babel/cli": "^7.2.3",
    "@babel/core": "^7.2.2",
    "@babel/node": "^7.2.2",
    "@babel/plugin-proposal-export-default-from": "^7.2.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.2.0",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/plugin-transform-runtime": "^7.2.0",
    "@babel/preset-env": "^7.2.3",
    "@babel/preset-react": "^7.0.0",
    "@loadable/babel-plugin": "^5.2.2",
    "@loadable/component": "^5.2.2",
    "@loadable/webpack-plugin": "^5.2.2",
    "@loadable/server": "^5.3.0",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^8.0.5",
```
I run my server like this: `"serve": "NODE_ENV=development nodemon --exec babel-node --inspect src/server/index.js",`

Any ideas?

thanks!

**Comment by ilgianfra** [comment]
It looks like if I install babel-plugin-dynamic-import-webpack, it works. But it shouldn't because it should be the old version of @babel/plugin-syntax-dynamic-import, no?

**Comment by ilgianfra** [comment]
If I run `babel src/client/routes/routes.js` it seems working, it transpile the file correctly. 
Babel config should be applied because if I remove one plugin from the .babelrc (ex: @babel/plugin-proposal-export-default-from) it crashes.
It looks like it does not perform the `loadable/babel-plugin`.

I tried to remove `@babel/plugin-syntax-dynamic-import` and `babel-plugin-dynamic-import-webpack` from my package.json and run `npm install` but I still get the same error.

**Comment by neoziro** [comment]
If it works with `babel yourfile.js`, it is relative to your babel configuration, maybe you have something that prevent it to run with `babel-node`.

**Comment by ilgianfra** [comment]
But if I install `babel-plugin-dynamic-import-webpack` it works.
I have posted my package.json and babelrc, do you have one example project settings?
I just started mine so it has just fews packages, how can I check if something is preventing to run that plugin with babel-node?
thanks

**Comment by ilgianfra** [comment]
Yes I did, many times :)
In fact in the example you are using `@babel/plugin-syntax-dynamic-import` in the babel [configuration](https://github.com/smooth-code/loadable-components/blob/master/examples/server-side-rendering/babel.config.js), also you are using webpack 3 ( I don't know if it impacts something). 
Btw adding the `babel-plugin-dynamic-import-webpack` it works.

thanks anyway for the support!

**Comment by neoziro** [comment]
OK good if it works, I close it.

**Comment by neoziro** [comment]
I gave a look, I see an error. You are getting script tags before collecting chunks. https://github.com/ilgianfra/boilerpalte-ssr-react/blob/master/src/server/helpers/renderer.js#L18

You must first collect chunks, then get the script tags. This is probably the origin of your issue.

**Comment by ilgianfra** [comment]
thanks for taking a look!
I have updated and pushed as you said but I still get the flickering, also I notice if I console.log `scriptsTags` I get:
```
scriptTags <script>window.__LOADABLE_REQUIRED_CHUNKS__ = [];</script>
<script async data-chunk="client" src="/vendor.js"></script>
<script async data-chunk="client" src="/client.js"></script>
```
I don't see the `0.js` that is supposed to be the home page which is downloaded in the client side and maybe this is the origin of the issue. In fact if I remove 
`component: loadable(() => import('../components/Home')),` in the routes file the page works fine.
What do you think?

**Comment by ilgianfra** [comment]
I think it is a problem of the famous babel plugin, I also tried to run your example SSR and If I run `yarn build` it returns the same `SyntaxError: Unexpected token import`

**Comment by joacub** [comment]
same error heere with the latest version of all

**Comment by essential-randomness** [comment]
I think you might be running into this: https://github.com/webpack/webpack/issues/8656

**Comment by joacub** [comment]
Yes is that... is solved right now

**Comment by ilgianfra** [comment]
Can you both copy your package.json?

**Comment by ericgio** [comment]
I had a similar issue while trying to use SSR and the problem for me was that node couldn't handle dynamic imports. I tried a few solutions, including adding `babel-plugin-dynamic-import-webpack` to my `.babelrc`. That sort of worked, but caused other problems. What finally worked for me was adding [`babel-plugin-dynamic-import-node`](https://github.com/airbnb/babel-plugin-dynamic-import-node) *only* to my @babel/register call:

```js
// In my index.js, which is called by node...
require('@babel/register')({
  plugins: [
    'dynamic-import-node',
  ]
});
```
Note that adding this plugin to my `.babelrc` did not work, since both my server- and client-side code call that. With the above, only node is affected.

I'm honestly kind of surprised more people haven't run into this, though I see at least [one other issue](https://github.com/smooth-code/loadable-components/issues/254) mentioning the problem and solution. @neoziro: it might be worth mentioning this plugin in the SSR docs?

**Comment by neoziro** [comment]
As I said, if you have to add [babel-plugin-dynamic-import-node](https://github.com/airbnb/babel-plugin-dynamic-import-node), it is because your dynamic import is called server-side. It should not be the case with Loadable Components, on server-side it does a synchronous call.

**Comment by fatemab** [comment]
I also get same issue when my node version is 8 but when I switch to 10, I don't get that error any more.  And also about `@babel/plugin-syntax-dynamic-import`, I had to use this plugin for dynamic import support but when I moved to `@loadable/components`, It works without adding this plugin. But I need my node version >= 10.
