### ISSUE TITLE
No compatibility w/ react-helmet in prod

### ISSUE THREAD

**Issue by Chrischuck** [smooth-code/loadable-components#205]
## 🐛 Bug Report

When building a Razzle app that uses loadable-components and react-helmet, any component with the react-helmet (Helmet) component is merged in the build folder. Components are split correctly in dev mode.

<img width="1196" alt="screen shot 2019-01-16 at 10 04 14 pm" src="https://user-images.githubusercontent.com/13311268/51299291-cfb8b900-19dc-11e9-8cb4-cce9d79c0fd0.png">

In the image above you can only the `pages-home` chunk when there should be multiple page chunks.

## To Reproduce

1. Create two components that use react-helmet's Helmet component
2. Use both components together in a single component

## Expected behavior

Components are chunked properly even though they contain the Helmet component

## Link to repl or repo (highly encouraged)

https://github.com/Chrischuck/loadable-component-helmet

**Comment by neoziro** [comment]
I think it is a webpack issue, probably in razzle, Loadable doesn't do any magic on bundle splitting. I cannot help you sorry...
