### ISSUE TITLE
Apollo's getDataFromTree does not fetch data for a Loadable component's children queries

### ISSUE THREAD

**Issue by jdmoody** [smooth-code/loadable-components#206]
## 💬 Questions and Help

I'm using @loadable/component along with react-apollo. For SSR, I have used @neoziro's [SSR middleware solution](https://github.com/smooth-code/loadable-components/issues/30#issuecomment-438360608) in issue  https://github.com/smooth-code/loadable-components/issues/30 and it works great.

However, I'm encountering an issue while trying to preload pages for client-side navigation. 

When navigating, we call react-apollo's `getDataFromTree` function on **client side** to preload all the data from GraphQL queries in the tree. `getDataFromTree` does not know to wait for loadable-components, though, so it immediately renders a loading screen instead of keeping the user on the initial page until all the loadable-components and their children queries have finished loading.

Here's a more concrete example:
1. User clicks a link on the Home page to a Profile page, which starts a client-side navigation.
2. getDataFromTree begins walking the Profile page React tree and fetching data for Query components
3. Eventually, getDataFromTree tries to render a loadable-component, which immediately renders a loading component while the loadable chunk is asynchronously loaded in.
4. Once all other queries have fetched data, getDataFromTree resolves without waiting for the js chunk to load in.
5. Once the JS chunk loads in, loadable-component will render its component. Any children queries within the loadable-component now start to fetch their data.

**Expected:** User clicks Profile page link, Profile page loads in with all data already fetched.
**Actual:** User clicks Profile page link, sees loading screen while Profile chunk loads in, then sees additional loading screen while Profile chunks' Queries are loaded, then finally sees Profile page with all data.

How can I get around this problem?

My initial thought was to pass the InnerLoadableComponent's this.promise to getDataFromTree via a wrapper component, but I don't have access to the InnerLoadable due to Ref Forwarding.

Any other thoughts, solutions, or discussion would be greatly appreciated. Thanks!

**Comment by neoziro** [comment]
Hello @jdmoody, You must run `jsx = extractor.collectChunks()`, then `getDataFromTree(jsx)`. The collectChunks will take care of loading all modules.

**Comment by neoziro** [comment]
Oh.. You want to use it on client-side. I didn't get it. For now it is not possible. It would require to use the same strategy as `getDataFromTree` (recursive rendering). We will not work on it because Suspense should be able to solve our issues soon. I don't want to invest time on it. For now the best thing to do is "prefetch" + "loader".

**Comment by jdmoody** [comment]
Got it, thanks again. Makes sense not to invest time in something soon to be solved by Suspense.

By "prefetch" + "loader", do you mean use the prefetching functionality described in the [docs](https://www.smooth-code.com/open-source/loadable-components/docs/prefetching/) and adding a loader component as a fallback?

**Comment by neoziro** [comment]
Yes it is what I mean.

**Comment by jdmoody** [comment]
Thank you! This answers my question. Closing.

**Comment by lauterry** [comment]
Hi @neoziro 

You said that 

> The collectChunks will take care of loading all modules.

How can I gather the data to load server side before calling `ReactDOMServer.renderToString` ?

Can I somehow rely on `collectChunks` ?

**Comment by lauterry** [comment]
@neoziro Thx for the clarification

**Comment by masihjahangiri** [comment]
> Hello @jdmoody, You must run `jsx = extractor.collectChunks()`, then `getDataFromTree(jsx)`. The collectChunks will take care of loading all modules.

not work for me!

**Comment by theKashey** [comment]
Just update to the latest version. That's all you have to do.
