### ISSUE TITLE
Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by lzr900515** [smooth-code/loadable-components#208]
Version
webpack: ^3.5.5
@loadable/component : ^5.2.2
@loadable/babel-plugin: ^5.2.2,
@loadable/server: ^5.2.2,
@loadable/webpack-plugin:^5.2.2

webpack plugins config:
![image](https://user-images.githubusercontent.com/15673574/51455947-bf129500-1d86-11e9-8244-42c4239b68b9.png)

Error info:
![image](https://user-images.githubusercontent.com/15673574/51455744-f03e9580-1d85-11e9-85d8-f84e32da03fd.png)

**Comment by theKashey** [comment]
🤷‍♂️ webpack should be 4+ 🤷‍♂️

**Comment by lzr900515** [comment]
> 🤷‍♂️ webpack should be 4+ 🤷‍♂️

Ok, i think so , but not for sure.  thanks a lot.
