### ISSUE TITLE
Using styled-components 

### ISSUE THREAD

**Issue by diemate** [smooth-code/loadable-components#209]
## 💬 Questions and Help

I'm using loadable components with styled-components for css. 
But if I want to use SSR, I have to implement streaming rendering, because otherwise, the components are loaded once the app is running in the browser and it re-render's the content. 

Is there any other option for using styled-components but without using node streams? If no, does node streams actually makes an impact on the performance? 

Thank you!

**Comment by neoziro** [comment]
Hello @diemate, you can use the API described in the documentation, it works fine! https://www.styled-components.com/docs/advanced#example

You can also run `renderToStaticMarkup` before the stream to traverse the tree before rendering the application in stream mode. But you will have two renders.
