### ISSUE TITLE
SSR Not Consistently Working with Redux

### ISSUE THREAD

**Issue by squibbleFish** [smooth-code/loadable-components#211]
Having an odd issue where I am not consistently seeing SSR work in a redux environment. 

In a main components file, I have a simple fetch script that does something like this

```javascript
class MyComponent extendend Component {
  static fetch({ store }) {
    store.dispatch(someAction)
  }
}
```
My routes file uses loadable as such
```javascript
routes = [
  {
     name: MyComponent
     component: loadable () => import('../path/to/component')
  }
]
```
The server does a simple match on using the react-router-config
```javascript
const { route, match } = matchedRoutes.find((branch) => {
    // if no route, throw a 404
    if (!branch.route) {
      return next(new URIError());
    }
    /**
     * @type {{route, match}}
     */
    return branch;
  });

  const { component } = route;
  const { params = {}, url = '' } = match;
  
  if (!component.fetchData) {
    component.fetchData = () => new Promise(resolve => (resolve()));
  }
```

If I do a console log without loadable, `component.fetchData` is always present. However; using `loadable` I see that on initial render `component.fetchData` will be `undefined`. If I do a hard refresh, I can once again see `component.fetchData` returning a function as it should.

Any help you can offer would be appreciated.

**Comment by ilgianfra** [comment]
I think it's because that component is already in one chunks so it is not in the `main.js` so it is not loaded in the SSR because the extractor is sending just the `main.js`, try to put that static method in another file and using some other matching.

I am facing a similar issue and I think the best way is to include the requested view in the main script and then lazy loading all the others (but I don't know how :D )

**Comment by squibbleFish** [comment]
That's what I was thinking as well. Moved the `fetchData` call forward to the router config and that actually seems to fix the issue.

**Comment by ilgianfra** [comment]
Glad to hear!

don't you have a flickering during the first loading? 
Because when the js of the current page get loaded in the header it run a re-render and i get a strange flickering

**Comment by wudoem** [comment]
> ```js
> class MyComponent extendend Component {
>   static fetch({ store }) {
>     store.dispatch(someAction)
>   }
> }
> ```

I do struggle with same thing. Static method from Component is just being removed once it get wrapped with loadable.

**Comment by neoziro** [comment]
@wudoem it is very weird, I thought statics were hosted: https://github.com/smooth-code/loadable-components/blob/master/packages/component/src/resolvers.js#L3

Maybe we need to add a test on this.
