### ISSUE TITLE
Flickering effect and SSR example not working

### ISSUE THREAD

**Issue by ilgianfra** [smooth-code/loadable-components#213]
## 🐛 Bug Report

Hi again! 

I have created this [repo](https://github.com/ilgianfra/boilerplate-ssr-react) as an example with styled components and Apollo. But it looks like when the chunk of the requested page is added to the header of the page, it makes a blinking effect, like it was re-rendering.

Also I tried to run the example in this repo and it look like it is not working.

```
    "@loadable/component": "^5.5.0",
    "@loadable/server": "^5.5.0",
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.2.2",
    "@babel/node": "^7.2.2",
    "@babel/plugin-proposal-export-default-from": "^7.2.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.2.0",
    "@babel/plugin-transform-runtime": "^7.2.0",
    "@babel/preset-env": "^7.2.3",
    "@babel/preset-react": "^7.0.0",
    "@babel/runtime": "^7.3.1",
    "@loadable/babel-plugin": "^5.5.0",
    "@loadable/webpack-plugin": "^5.5.0",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^8.0.5",
    "babel-plugin-dynamic-import-webpack": "^1.1.0",
```

![flickering](https://user-images.githubusercontent.com/11957418/51683547-65aaa000-1fea-11e9-9582-86a7330da9ed.gif)

thanks!

**Comment by rafaalb** [comment]
Hi @ilgianfra have you tried adding the prop to Apollo Query: <Query ssr={false} {...props} /> ?

**Comment by ilgianfra** [comment]
Hi!
But if I will add that it will be rendered just in the client,no? 
the docs says:

> If you want to intentionally skip a query during SSR, you can pass ssr: false in the query options. Typically, this will mean the component will get rendered in its loading state on the server

**Comment by Volkovskiy** [comment]
Same issue with blinding on client side when chunk loaded, but I don't use Apollo. Any ideas?

**Comment by mciastek** [comment]
I'm noticing the same issue. Is use SSR and `loadable-components`. It loads proper chunk, so page is rendered properly even with disabled JavaScript in browser. Markup is the same for server side rendered and client rendered. Rehydrate works fine, because I don't get any errors in console. I guess that `loadable` causes somehow a full re-render.

**Comment by theKashey** [comment]
> I guess that loadable causes somehow a full re-render.

Yes, it does

> it makes a blinking effect

Is everything ok with `__APOLLO_STATE__`?

**Comment by neoziro** [comment]
I also experienced the little blink, I think it is related to styled-components in dev mode. Do you have this blink in production? Loadable makes a full re-rendering yes, but you should be able to re-render the React application without a blink.

**Comment by ilgianfra** [comment]
Hi @neoziro!
I will try on production mode with styled components and without styled components at all (I don't remember if I have tried already).

I will let you know!

**Comment by neoziro** [comment]
Looks like it is fixed.

**Comment by ilgianfra** [comment]
Actually I didn't have time to try it out! but I will get back to you as soon as possible, I hope with good news and we can keep the issue closed :)

**Comment by neoziro** [comment]
On my side, I don't have any problem relative to Loadable Components. The blink effect is from styled-components.

**Comment by nesbtesh** [comment]
I have the same issue, did you guys manage to find a fix?

**Comment by theKashey** [comment]
@nesbtesh - there are many ways you can get this flickering. Without knowing your particular case there is no way to understand what went wrong.

**Comment by SchneiderOr** [comment]
Same issue, Im using components + ssr + loadable, when i recently moved some of my modals to be lazy loaded (those modal needed only on client) on every chunk load, i dont think it relates to styled-component honestly it sounds more like a problem with loadable, would love to hear if anyone overcome this issue

**Comment by theKashey** [comment]
You are using it with Suspense/async/lazy or with the older `LoadingComponent` API?
Suspense is not working for React > 16.10
