### ISSUE TITLE
require.ensure is not a function

### ISSUE THREAD

**Issue by shunxing** [smooth-code/loadable-components#214]
Hi I'm using loadable-components@2.2.3 but I'm struggling with it. I'm trying to figure it out how SSR works with the library. I followed step by step the following tutorial (https://www.smooth-code.com/articles/code-splitting-react-loadable-components) for the SSR. 

I know it's quite old right now but I haven't upgraded the application to babel 7, so it cannot work with @loadable libraries.

The problem with the SSR is that when I call getLoadableState on my server before rendering the html string, my console display `require.ensure is not a function`. However, I already added these plugins `		"loadable-components/babel",
		"babel-plugin-dynamic-import-node",
		"dynamic-import-webpack"` in babel

The problem is that I use loadable to configure my routes, meaning that i use dynamic imports.

Have you ever encountered this kind of problem?

**Comment by neoziro** [comment]
Hello @shunxing, I am sorry but loadable-components v2.2.3 is not maintain any more. I can't help you on your problem. Two choices: upgrade to babel 7, or use react-loadable, it should work with babel 6.
