### ISSUE TITLE
Extractor gets incorrect chunk name

### ISSUE THREAD

**Issue by wbobeirne** [smooth-code/loadable-components#216]
## 🐛 Bug Report

I've just setup loadable components, and I think I'm quite close to getting it right, but I get the following error when I try to get the tags from my extractor:
```
loadable: cannot find pages-index in stats
```

This seems to be trying to load the chunk that's a result of the following loadable component:
```ts
const Home = loadable(() => import('pages/index'), opts);
```

The problem here is that my chunks don't follow the naming convention that would cause this chunk to be called `pages-index`. My chunks come out named numerically, e.g. `0.chunk.js`, `1.chunk.js` and so on. This appears to be correctly output in `loadable-stats.json`, but the `ChunkExtractor` keeps getting these "named" chunks.

I'm probably missing a key step to setting this up, so I won't go through the process of setting up a MVP example of the issue. But if that's needed for more information, I'll gladly do it.

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS 10.14.2
 - CPU: (4) x64 Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
 - Memory: 106.79 MB / 4.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.13.0 - ~/.nvm/versions/node/v8.13.0/bin/node
 - Yarn: 1.12.3 - /usr/local/bin/yarn
 - npm: 6.4.0 - ~/Documents/zcash-grant-system/frontend/node_modules/.bin/npm
 - Watchman: 4.1.0 - /usr/local/bin/watchman
## npmPackages:
 - @loadable/babel-plugin: 5.5.0 => 5.5.0
 - @loadable/component: 5.5.0 => 5.5.0
 - @loadable/server: 5.5.0 => 5.5.0
 - @loadable/webpack-plugin: 5.5.0 => 5.5.0
```

**Comment by wbobeirne** [comment]
I've inspected the output bundle, and it looks like the babel component is correctly doing its thing and setting the chunkName:
```js
var Home = Object(_loadable_component__WEBPACK_IMPORTED_MODULE_3__["default"])({
  chunkName: function chunkName() {
    return "pages-index";
  },
  ...
});
```

So it looks like this is very likely a webpack issue with not putting out the right chunk names.

**Comment by jhornby** [comment]
How did you construct your ChunkExtractor?

**Comment by wbobeirne** [comment]
```
    const statsFile = path.join(
      paths.clientBuild,
      paths.publicPath,
      'loadable-stats.json',
    );
    extractor = new ChunkExtractor({ statsFile, entrypoints: ['bundle'] });
```
The entrypoints config is because my entry point is named bundle, not main. And I've confirmed that the statsFile path points to the right place, and that the resulting ChunkExtractor instance seems to have all of its properties correctly populated from the data of the stats file.

**Comment by wbobeirne** [comment]
Ah, I knew it would be something like this: I had a conflicting Babel plugin (`babel-plugin-dynamic-import-webpack`) that was working on imports that occurred before loadable's plugin. Removing that fixed it right up.

Sorry for the false report!

**Comment by nandosangenetto** [comment]
How did you solve that issue @wbobeirne? I have the same problem and I cannot get rid of `babel-plugin-dynamic-import-webpack`.
