### ISSUE TITLE
Babel plugin does not work with Storybook

### ISSUE THREAD

**Issue by bertho-zero** [smooth-code/loadable-components#227]
## 🐛 Bug Report

I have an error that comes and goes randomly when I use the babel plugin with storybook, the error is:
```
react.development.js:228 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `InnerLoadable`.
    in InnerLoadable (created by Context.Consumer)
    in Unknown (created by ForwardRef)
    in ForwardRef (created by Route)
    in Route (created by App)
    in Switch (created by App)
    in div (at App.js:101)
    in div (at App.js:88)
    in div (at App.js:87)
    in div (at App.js:86)
    in App (created by Context.Consumer)
    in Connect(App) (created by InnerLoadable)
    in InnerLoadable (created by Context.Consumer)
    in Unknown (created by ForwardRef)
    in ForwardRef (created by Route)
    in Route
    in Switch
    in Provider (at app.js:83)
    in Route (at RouterRedialTrigger.js:82)
    in RouterRedialTrigger (created by Route)
    in Route (created by withRouter(RouterRedialTrigger))
    in withRouter(RouterRedialTrigger) (at app.js:82)
    in Unknown (created by Route)
    in Route (created by withRouter())
    in withRouter() (at app.js:81)
    in ScrollToTop (created by Route)
    in Route (created by withRouter(ScrollToTop))
    in withRouter(ScrollToTop) (at app.js:92)
    in Router (at app.js:91)
```

The object contains `{ __esModule: true, default: undefined }` when I have the error.
I made some refreshments and the error disappears, to return soon after.

I can counter this problem by using `@babel/plugin-syntax-dynamic-import` instead.

### Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: Linux 4.4 Ubuntu 16.04.5 LTS (Xenial Xerus)
 - CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
 - Memory: 234.49 MB / 11.61 GB
 - Container: Yes
 - Shell: 5.1.1 - /bin/zsh
## Binaries:
 - Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
 - Yarn: 1.13.0 - /usr/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
## npmPackages:
 - @loadable/babel-plugin: ^5.6.0 => 5.6.0
 - @loadable/component: ^5.6.0 => 5.6.0
```

**Comment by bertho-zero** [comment]
This is due to something other than Storybook because I also have the problem outside. This is probably due to another babel plugin, I would do more tests to clarify.

**Comment by bertho-zero** [comment]
![image](https://user-images.githubusercontent.com/8525267/52476388-bac7e380-2b9e-11e9-87fa-dbfc85572a44.png)

The first log comes from here: https://github.com/smooth-code/loadable-components/blob/0d3e7dee3045737be1709ffa300aca083aef457c/packages/component/src/createLoadable.js#L99

In storybook I can not wait for preloading, and the error happens when rendering is done before having the chunks, and it's random.

**Comment by bertho-zero** [comment]
`{ __esModule: true, default: undefined }` is the result of `loadSync`, I realize I have the error only when `ctor.isReady` returns true and `loadSync` is used.

**Comment by bertho-zero** [comment]
If I replace
https://github.com/smooth-code/loadable-components/blob/0d3e7dee3045737be1709ffa300aca083aef457c/packages/component/src/createLoadable.js#L100-L101
with
```js
if (result) {
  this.state.result = result 
  this.state.loading = false
}
```

And
https://github.com/smooth-code/loadable-components/blob/0d3e7dee3045737be1709ffa300aca083aef457c/packages/component/src/resolvers.js#L5-L7
with
```js
if (Component) {
  hoistNonReactStatics(Loadable, Component, { 
    preload: true, 
  })
}
```

I can bypass the errors and get a webpack error inside my loadable component, on an `import ... from ...`.

**Comment by bertho-zero** [comment]
This is a problem with the storybook webpack configuration.

**Comment by zackphilipps** [comment]
@bertho-zero how did you solve it?

**Comment by bertho-zero** [comment]
The response is in the referenced issue: https://github.com/storybookjs/storybook/issues/5524#issue-408200164

In your `.storybook/webpack.config.js` try to add the following line:
```js
defaultConfig.optimization.splitChunks.chunks = 'initial';
```
