### ISSUE TITLE
is it possible to name the bundle?

### ISSUE THREAD

**Issue by mulmulovich** [smooth-code/loadable-components#23]
i never saw it works but i saw implementation of dynamic import using this syntax to give meaningful names to the bundles (unlike 1.lib.bundle. ):

for example:
`import('./pages/About' /* webpackChunkName = 'about' */)`

i've tried it using loadable-component with no success...
`loadable(() => import('./pages/About' /* webpackChunkName = 'about' */))`

please advise if it is supported or planned

best regards and thanks for this useful library

**Comment by neoziro** [comment]
Yeah you can safely use webpack chunk names:

```js
import loadable from 'loadable-components'

const About = loadable(import(/* webpackChunkName: "about" */ './pages/About'))
```
