### ISSUE TITLE
Getting Unexpected token error.

### ISSUE THREAD

**Issue by plxity** [smooth-code/loadable-components#233]
## 💬 Questions and Help
Can anyone help why am I getting this "Unexpected Token" error?
![capture](https://user-images.githubusercontent.com/28510494/52590571-a407e200-2e67-11e9-8dc0-87ae97dcc6e4.PNG)

**Comment by essential-randomness** [comment]
Possibly related to https://github.com/webpack/webpack/issues/8656

**Comment by neoziro** [comment]
Hello @plxity. You should use `webpack` to build your app and have the correct babel configuration, please follow code splitting guides on React or webpack documentation.
