### ISSUE TITLE
style tags are in reverse order

### ISSUE THREAD

**Issue by seeden** [smooth-code/loadable-components#235]
When you use getStyleTags you get styles in wrong order. That means chunks are first and main css is last. This will cause bad css visualisation because order must be correct.

Here is temporary workaround
```js
    const styleTags = appContext
      .getStyleTags()
      .split('\n')
      .reverse()
      .join('\n');
```

**Comment by neoziro** [comment]
Hello @seeden. Since style tags must be included in `head` because it's blocking. The order is currently not an issue. Isn't it?

**Comment by seeden** [comment]
I have it in the head and it is an issue.

**Comment by neoziro** [comment]
How can your body be displayed without all styles being loaded?

**Comment by theKashey** [comment]
The problem is not with a head, but with styles. Styles defined "below" could override the styles defined "above". 
Look like @seeden styles are quite CSS-ish and rely on the right overriding "order". That's a smell of a very bad code style, or very complicated technology (like BEM redefinition layers).

In short - it's quite important to preserve a style order.

**Comment by seeden** [comment]
@theKashey I am using bootstrap and css-modules. With current order I will get chunks with css-modules first and bootstrap last.

**Comment by neoziro** [comment]
We have to be sure to insert styles in the correct order. But we have to investigate what is the correct order first.

**Comment by FlorinSenoner** [comment]
> The problem is not with a head, but with styles. Styles defined "below" could override the styles defined "above".
> Look like @seeden styles are quite CSS-ish and rely on the right overriding "order". That's a smell of a very bad code style, or very complicated technology (like BEM redefinition layers).
> 
> In short - it's quite important to preserve a style order.

I agree that you should not relay on the css order and either use a convention like BEM or namespace your css (CSS Modules). But there might be cases where you want to include some files first i.e. normalize.css, that is loaded from node_modules and therefore included in the vendors chunk

**Comment by theKashey** [comment]
:nods: `normalize.css` case is quite valid.

**Comment by neoziro** [comment]
I agree, the order should be the good one, but I would like to be sure that we fix it correctly, I have to check if the order is correct before fixing it. If someone want to fix it, he is welcome!

**Comment by theKashey** [comment]
Probably the best way is to inject stuff like `normalize.css` manually in a `header template`.
I am almost sure, that you can't get "right" CSS order from `stats.json`, and observing calls to style-loaders is not possible with stream rendering.
Personally, I've solved it using [used-styles](https://github.com/theKashey/used-styles), but `normalize.css` is not used. And "use-order" does not reflect "import-order". So, yet again, the best way is to solve the problem by hand - place `normalize.css` where it should be.
