### ISSUE TITLE
Better "plain" CSS support.

### ISSUE THREAD

**Issue by theKashey** [smooth-code/loadable-components#236]
## 🚀 Feature Proposal

Improve streaming render support to "eject" used `scripts` and `css` once they are detected, not after the whole render.

## Motivation

Improve TTFB. Remove FOUC.

## Example

- styled-components SSR interleave `styles` with rendering content, next hoisting them to the head __before__ hydration (https://github.com/styled-components/styled-components/blob/c3eedbeb79621acd668e15ed2d63107528ed81c3/packages/styled-components/src/models/ServerStyleSheet.js#L58)
- `used-styles` are doing the same for plain CSS on "used-classes" basic.

## Pitch

Right now streaming support is not quite "streaming". It would add used styles and links only __at the end__, leading to a Flash Of Unstyled Content.
It should be doable to emit all known chunks using a transform stream, as soon as they got discovered.

**Comment by neoziro** [comment]
I don't want to invest a lot on styles, if you want a good user experience, use styled-components, emotion or the new one linaria.

**Comment by theKashey** [comment]
> or the new one linaria
> Write CSS in JS, but with zero runtime, CSS is __extracted to CSS files__ during build

And emotion is also capable to extract styles to static files during the build. Result - FOUC in a streaming mode, as long as styles have to be loaded prior to the main content.

**Comment by neoziro** [comment]
I don't understand. Streaming mode is not currently supported (until Suspense will be ready).

**Comment by theKashey** [comment]
I mean renderToNodeStream

**Comment by neoziro** [comment]
I close it, for now we will not support more. Let's wait for Suspense for it.

**Comment by 7rulnik** [comment]
@neoziro 
I prefer to use css-in-js solutions as you said, but many people still use css-modules.
I'm sure you already saw [this tweet](https://twitter.com/mxstbr/status/1139112381810925568).
I think it would be cool if we could extract styles with loadable-components.

You mentioned Suspense: do you expect some breaking changes? If no, so why we can't implement interleave extracting of CSS?

**Comment by neoziro** [comment]
Hello @7rulnik, I am open for a better support. On my side, I will not do it, I don't use CSS modules, so I don't need this in the library. Feel free to work on it, I am open to it!

**Comment by neoziro** [comment]
Hello @7rulnik, I am open for a better support. On my side, I will not do it, I don't use CSS modules, so I don't need this in the library. Feel free to work on it, I am open to it!
