### ISSUE TITLE
Template.ast is not a function

### ISSUE THREAD

**Issue by glgarrettsherm** [smooth-code/loadable-components#238]
I am currently getting an error using the '@loadable/babel-plugin'.

```
ERROR in ./src/web/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: template.ast is not a function
    at isReadyProperty (.../node_modules/@loadable/babel-plugin/lib/properties/isReady.js:9:29)
```

I saw this other issue that seemed similar #150 but it didn't apply to my specific case because I am currently using webpack 4.28.4, @babel/core 7.1.2 and not using razzle in my project at all. 

Any insight you could give me would be much appreciated. Thanks!

**Comment by neoziro** [comment]
Hello @glgarrettsherm, you are probably running Babel 6 instead of Babel 7, maybe a global installation or something like it. It is a problem about your Babel configuration, not about this project.

You should try to investigate which Babel version you are running.

**Comment by garrettsherm** [comment]
@neoziro Ya you are right my babel-loader wasn't up to date and was relying on an older version of Babel, so updating babel-loader seemed to fix the issue. 

I appreciate you taking the time to answer!
