### ISSUE TITLE
Support hot module replacement

### ISSUE THREAD

**Issue by marcosun** [smooth-code/loadable-components#24]
Is there a way to support HMR on development mode? I’ve cloned your Website project but have no idea why changes have been made to components, and new chunk files pushed to browser successfully, however DOM does not reflect those changes unless I give page a total refresh?

**Comment by neoziro** [comment]
At this time no, but i could be done. [react-imported-component](https://github.com/theKashey/react-imported-component) by @theKashey is focusing on that specific problem.

**Comment by neoziro** [comment]
The new version of [React Hot Loader (v4)](https://github.com/gaearon/react-hot-loader/tree/next) will support it out of the box. This is currently in beta, if you are interested give a try!
