### ISSUE TITLE
Pass loadable-stats.json to ChunkExtractor ?

### ISSUE THREAD

**Issue by revskill10** [smooth-code/loadable-components#242]
Currently, `statsFile` is the path to `ChunkExtractor`.
Is there anyway for us to pass the json content to `ChunkExtractor` instead ?

I'd like to do like this
```js
const statsJson = require('loadable-stats.json')
const extractor = new ChunkExtractor({statsJson})
```

**Comment by neoziro** [comment]
Hello @revskill10, yes of course, see h-code/loadable-components/blob/master/packages/server/src/ChunkExtractor.js#L151

Use `stats` instead of `statsFile`.
