### ISSUE TITLE
Error message still shows "@loadable/babel" rather than "@loadable/babel-plugin"

### ISSUE THREAD

**Issue by Terry-Su** [smooth-code/loadable-components#253]
## 🐛 Bug Report

Just a tiny spelling problem. Found following error message while using typescript to conduct SSR:
```bash
loadable: SSR requires `@loadable/babel`, please install it
```

## Expected behavior
```bash
loadable: SSR requires `@loadable/babel-plugin`, please install it
```

**Comment by neoziro** [comment]
Hello @Terry-Su, thanks for spotting this bug. Anyone wants to fix it?
