### ISSUE TITLE
Is it possible to load many libraries at the same time with loadable.lib ?

### ISSUE THREAD

**Issue by luishdz1010** [smooth-code/loadable-components#260]
Nesting loadable.lib components seems to work but requests happen in a waterfall-like fashion, which is not optimal. Can something like this be supported?

```js
loadable.lib(() => Promise.all[import('moment'), import('somthing-else')])
```

**Comment by theKashey** [comment]
I think it's already supported
```js
const TwoAtOnce = loadable.lib(() => Promise.all(import('moment'), import('somthing-else')]))
<TwoAtOnce>
{([{default:moment}, {default:somthing}]) => moment(somthing(date)).fromNow()}
</TwoAtOnce>
```

PS: Year, default is not cool.

**Comment by BowlingX** [comment]
If I try this I'm getting `loadable: multiple import calls inside `loadable()` function are not supported.`

**Comment by neoziro** [comment]
Hello @BowlingX, you can create another file:

```js
export { default as moment } from 'moment'
export { default as something } from './something'
```

**Comment by revskill10** [comment]
How about loading multiple React Components at the same time ?

**Comment by neoziro** [comment]
You can load them using `loadable.lib` and use the previous tip if you want.
