### ISSUE TITLE
Set different attributes on tags based on chunk

### ISSUE THREAD

**Issue by salzhrani** [smooth-code/loadable-components#261]
## 🚀 Feature Proposal

allow `getScriptTags` and similar to take a function as an argument which allows for setting different attributes to different chunks/scripts

## Motivation

currently there is now way to set different attributes values based on the chunk, which is needed to utilize Subresource Integrity. 

## Example
```
const tags = getScriptTags( chunk => {
  if (chunk.id === 'foo') return { integrity: 'SHA-foo' }
} );

```

## Pitch

Subresource Integrity is a very useful feature. I imagine other uses for this feature will be requested.

**Comment by neoziro** [comment]
Hello @salzhrani, good idea, I am open to the suggestion! Feel free to make a PR to implement it!

**Comment by odensc** [comment]
Why was this closed? @salzhrani Have you figured out how to implement SRI?

**Comment by neoziro** [comment]
@odensc thanks for referencing it!
