### ISSUE TITLE
Typescript + SSR after build throws error: "loadable: SSR requires `@loadable/babel`, please install it"

### ISSUE THREAD

**Issue by krishnaglick** [smooth-code/loadable-components#263]
I've scoped down my project into the following: https://github.com/krishnaglick/prod-build-test

Running the server with `yarn start` works fine, but if I build and run (`yarn serve`) then the error shows up. Any insight would be appreciated as to why things are working correctly within typescript, but not built-javascript.

**Comment by EvgeniyKumachev** [comment]
having same issue

**Comment by neoziro** [comment]
Hello @krishnaglick, thanks for the report. Unfortunately I am not very good with Typescript stuff. Maybe @theKashey has an idea?

**Comment by krishnaglick** [comment]
Just chiming in again, still encountering the issue.
If I run the app in the typescript it works fine. The issue arises when I try to boostrap the transpiled code.

**Comment by theKashey** [comment]
👀

**Comment by revskill10** [comment]
In my `razzle` setup, i only use `LoadablePlugin` in web target, not `node` target:
```js
if (!isServer) {
      const filename = path.resolve(__dirname, 'build')
      appConfig.plugins = [
        ...appConfig.plugins,
        new LoadableWebpackPlugin({
          outputAsset: false,
          writeToDisk: { filename },
        }),        
      ]
    }  
```
This is copy and pasted from the razzle example. You might try out this.

**Comment by krishnaglick** [comment]
We're doing server-side rendering so I don't think that'll help us.
Is there some logic in the plugin that prevents functionality if you're taking actions within a `dist` folder or something? I really am at my wits end as to why this code will function fine through typescript but not javascript.

**Comment by mciastek** [comment]
I have the same issue. I tried to combine TypeScript and Babel loaders (as showed here - https://github.com/smooth-code/loadable-components/issues/173), but I'm still getting the same error. Does anyone succeeded in launch SSR in TypeScript?

**Comment by krishnaglick** [comment]
@mciastek Are you having issues running the app with Typescript + Babel, or Transpiled Typescript to Javascript, and babel?

**Comment by mciastek** [comment]
I have issue both with only babel-loader (babel-typescript preset) and with ts-loader + babel-loader.

**Comment by krishnaglick** [comment]
If you look at my sample repo, the app should be running fine with
typescript.
It's post-transpile that's the issue. Looking through it might help ya

**Comment by mciastek** [comment]
@krishnaglick I launched you demo app and indeed SSR in TypeScript doesn't work with `loadable-components`.

@theKashey have you succeeded in running SSR written in TypeScript with `loadable-components`? I tried to use you solution, so compile code with ts-loader and then transpile it with babel-loader, but it didn't work. I still get the same error `"loadable: SSR requires `@loadable/babel`, please install it"`.

**Comment by krishnaglick** [comment]
I was able to get this issue solved by setting JSX within my server's tsconfig build to `preserve`, and targeting `esnext`. I'm going to close this now but pings are welcome if someone gets stuck along a similar vein.

**Comment by gupnee81** [comment]
Hi guys, I am using razzle for SSR using typescript and facing similar issue. would like to check how did you manage to hook tsconfig.json file separately for server and for client. Mine project has one and I keep it on root of a project. Please suggest.

**Comment by mciastek** [comment]
I managed to solve the issue. The problem was my wrapper for `loadable` function. In order to fix this issue I needed to add [Magic Comment](https://www.smooth-code.com/open-source/loadable-components/docs/babel-plugin/#magic-comments).

**Comment by gupnee81** [comment]
@mciastek - I tried using magic comments and they don't work for me. Here is my code - 
`
import loadable from '@loadable/component';

const loadHomePg = /* #__LOADABLE__ */ () => import('containers/HomePage');
export const HomePage = loadable(loadHomePg);
`

**Comment by neoziro** [comment]
You don't use the good comment, see https://www.smooth-code.com/open-source/loadable-components/docs/babel-plugin/

**Comment by chen86860** [comment]
I have the same issue while wrap `@loadable-component` as a function call, like so:
```jsx
// Loadable component
import React from 'react'
import loadable from '@loadable/component'

export default loader => loadable(loader, { fallback: <p> Loading...</p> })
``` 
and call it from routes definition:
```jsx
// routes.js
import Loadable from 'components/Loadable'

const Index = Loadable(() => import('@/pages/Index'))
```
after remove this wrap and import `@loadbale/component` directly, errors was gone:

```jsx
// routes.js
import loadable from '@loadbale/component'

const Index = loadable(() => import('@/pages/Index'))
```
Hope to be helpful :)

**Comment by srinisoundar** [comment]
I was facing the same issue. I added typescript support on top of [server-side-rendering](https://github.com/gregberge/loadable-components/tree/main/examples/server-side-rendering) example. hope it helps someone. [Server Side Rendering with TS](https://github.com/srinisoundar/loadable-server-side-rendering)
