### ISSUE TITLE
Usage with create-react-app + SSR

### ISSUE THREAD

**Issue by Dakkers** [smooth-code/loadable-components#268]
Hi! My setup is a combination of `create-react-app` (to build the client code) and SSR.

`npm run build` builds the client code and this does its own code-splitting, which works completely fine.

I also have `npm run build-server` which uses Webpack to build my server code. This works but it does its own code splitting. I'm not serving the static files from my server build directory, but from the client build directory. However, the `getScriptTags` scripts all reference the server build dir.

I had this working with `react-loadable` but since that lib has been deprecated, I'd rather use this. Does anyone have any thoughts on this? 🙏

**Comment by neoziro** [comment]
Hello @Dakkers, I think you should use the good target to build your webpack server build. It should not code split with node. You should follow this example https://github.com/smooth-code/loadable-components/tree/master/examples/server-side-rendering.

**Comment by Dakkers** [comment]
Hi @neoziro , what do you mean by the "good target"? I'll also take a look at that example.

**Comment by neoziro** [comment]
https://github.com/smooth-code/loadable-components/blob/master/examples/server-side-rendering/webpack.config.babel.js#L45

**Comment by Dakkers** [comment]
@neoziro I've changed my webpack to be similar to that of the webpack config you linked. However, those changes did not end up resolving my issue. My issue is that I'm importing my routes in my server code because I need to fetch data for those routes before rendering ( https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/server-rendering.md#data-loading ). This file (`routes.js`) imports my routes lazily, and importing this routes.js file in my server code causes the code-splitting on the server. Do you have any ideas? 😭

**Comment by neoziro** [comment]
I am sorry I can't help you more without a complete repro example. What you are trying to achieve is tricky and need a complete view of the problem.

**Comment by lauterry** [comment]
Hi Dakkers

Does my repo helps you ?

https://github.com/lauterry/perfect-react-app

Bests

**Comment by neoziro** [comment]
Seems resolved or stuck. I close it.
