### ISSUE TITLE
Using loadable-components with Razzle

### ISSUE THREAD

**Issue by mbrochh** [smooth-code/loadable-components#270]
Hi everyone. I think I got pretty far with using loadable-components with the popular boilerplate repo "Razzle". I have created an issue on their repo here: https://github.com/jaredpalmer/razzle/issues/954

If anyone here in the community is using loadable-components with Razzle in production, I would love to get your input on that thread :)

**Comment by neoziro** [comment]
Seems good, thanks for your work!
