### ISSUE TITLE
Do not resolve files with webpack@4.29.1

### ISSUE THREAD

**Issue by dianaabv16** [smooth-code/loadable-components#272]
## 👉 [Please follow one of these issue templates](https://github.com/smooth-code/loadable-components/issues/new/choose) 👈

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

**Comment by dianaabv16** [comment]
You may need an appropriate loader to handle this file type.
|   },
|   requireAsync: function requireAsync() {
>     return import(
|     /* webpackChunkName: "index" */
|     './index');



worked only after downgrading to webpack@4.23.1


my babel.config.js
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        modules: false,
      },
    ],
    '@babel/preset-react',
  ],
  plugins: [
    'styled-components',
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-syntax-dynamic-import', '@loadable/babel-plugin'
  ],
  env: {
    production: {
      only: ['app'],
      plugins: [
        'lodash',
        'transform-react-remove-prop-types',
        '@babel/plugin-transform-react-inline-elements',
        '@babel/plugin-transform-react-constant-elements',
      ],
    },
    test: {
      plugins: [
        '@babel/plugin-transform-modules-commonjs',
        'dynamic-import-node',
      ],
    },
  },
};


webpack.babel.js
      {
        test: /\.js$/, // Transform all .js files required somewhere with Babel
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: { plugins: [  '@loadable/babel-plugin' ] }
          // options: options.babelQuery,
        },
      },

**Comment by theKashey** [comment]
https://github.com/webpack/webpack/issues/8656

it's a known issue, coming from `acorn`, used by `webpack`.

**Comment by neoziro** [comment]
Hello @dianaabv16, please clean the issue before posting, it is a crap. Feel free to open a new one correctly formatted.
