### ISSUE TITLE
node\web loadable-stats.json <- what is for?

### ISSUE THREAD

**Issue by valorloff** [smooth-code/loadable-components#275]
> - Read carefully the README of the project

Yes
> - Search if your answer has already been answered in old issues

Yes

Based on SSR example, I have questions:
what is for two identical loadable-stats.json in dist/node/web ?
If i need to use `CleanWebpackPlugin` for clean dists?
How to output to another location?

`new LoadablePlugin({filename: "./another/path/loadable-stats.json",writeToDisk: true})`
> (like react-loadable)

don't help.
Thanks!

**Comment by neoziro** [comment]
Hello @valorloff, are you looking for this option: https://github.com/smooth-code/loadable-components/blob/master/packages/webpack-plugin/src/index.js#L10

This option will prevent the plugin from emitting it with assets. So you will only have one `loadable-stats.json`.

**Comment by valorloff** [comment]
Thanks, It needs investigated..

**Comment by valorloff** [comment]
You did not answer, where is used server chunks?
```
/public/dist/node/main.js
public/dist/node/main-bundle-ce5564e0.js
...........
```
Can you answer please?

**Comment by neoziro** [comment]
Node chunks are used server-side, in fact you build your code twice, one for client, and one for server.
