### ISSUE TITLE
Unexpected token < on collectChunks(<App />)

### ISSUE THREAD

**Issue by annelin07** [smooth-code/loadable-components#278]
## 💬 Questions and Help

Loadable Components project is young, but please before asking your question:

- Read carefully the README of the project
YES
- Search if your answer has already been answered in old issues
YES - it's not the issue with missing `/` at end of `publicPath`

After you can submit your question and we will be happy to help you!

I followed the SSR example, when it gets to 
```
  const jsx = webExtractor.collectChunks(<App />);
```
I'm getting
```
    Unhandled rejection SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)

```

Can you please help?  Thanks!

**Comment by theKashey** [comment]
Babel React/JSX plugin didn't work. Sometimes you have to use `jsx` to make it work - it depends on the settings.
Double check __babel__, not loadable components.

**Comment by annelin07** [comment]
thanks, use `React.createElement(App,{},null) solves it.
