### ISSUE TITLE
warnForDeletedHydratableElement: Warning: Did not expect server HTML to contain a <h1> in <div>

### ISSUE THREAD

**Issue by nreoch25** [smooth-code/loadable-components#28]
Hello, this is an awesome solution. Thanks a lot for this.

I've ran into an issue that I cannot solve and I spent a good 2 -3 hours trying to figure it out.
I'm using the full SSR solution with getLoadableState server side and loadComponents before using ReactDOM.hydrate on the client.
I cannot get rid of this warning:

Warning: Did not expect server HTML to contain a h1 in div
It comes from warnForDeletedHydratableElement function in React.

the h1 is the root element in the code splitted bundles.

For whatever reason when I hydrate the markup is not matching, even though I'm using loadComponents() before I hydrate. The loadComponents promise is resolving and this warning still occurs.

When I remove the code splitting this warning is gone so there's something going on that I can't figure out.

Any ideas would be much appreciated.

The code can be found here:  https://github.com/nreoch25/mern-boilerplate
Any help would be very much appreciated.

thanks

**Comment by nreoch25** [comment]
Something I notced for this:

When loadComponents() is called this is undefined:  window.__LOADABLE_COMPONENT_IDS__

So this line in loadComponents.js returns an empty array: var ids = window[_constants.COMPONENT_IDS] || [];

When that is an empty array it triggers the above warning/issue.

I was able to get around this by wrapping the loadComponents() call in a:

`setTimeout(() => {
   loadComponents().then(() => {
     "REACT APP"
   });
}, 0)`;

Am I doing something wrong? This is using webpack HMR which I read in another issue thread isn't working well with this.

**Comment by neoziro** [comment]
Thank you!

You should put `getScriptTag` before your `bundle.js` https://github.com/nreoch25/mern-boilerplate/blob/master/server/server.js#L97

**Comment by nreoch25** [comment]
Thanks bud! Really appreciate the reply.
