### ISSUE TITLE
Why SSR docs are so leak of information?!

### ISSUE THREAD

**Issue by pouyajabbarisani** [smooth-code/loadable-components#281]
I'm trying to add code splitting to my existing SSR react app. but provided information in this link is so limited!

https://www.smooth-code.com/open-source/loadable-components/docs/server-side-rendering/

For example, there isn't any details and descriptions about loadable-stats.json, what is it doing exactly, what is ChunkExtractor, how is it looks like in a "simple" real world example. just some complex codes without any info!

**Comment by revskill10** [comment]
@pouyajabbarisani Because it's enough ! The code that works is just like the docs:

```js
const extractor = new ChunkExtractor({
      statsFile: path.resolve(__dirname, 'loadable-stats.json'),
      entrypoints: ['client'],
    });
const markup = renderToString(
<ChunkExtractorManager extractor={extractor}><App /></ChunkExtractorManager>
);
```

**Comment by pouyajabbarisani** [comment]
What is the ChunkExtractor and loadable-stats.json and exactly what they do?! 
what is the loadable-stats.json's content?!

**Comment by pouyajabbarisani** [comment]
I got it. It's Webpack automatically making that.  :)
