### ISSUE TITLE
Make loadable.preload() return a promise

### ISSUE THREAD

**Issue by luishdz1010** [smooth-code/loadable-components#285]
## 🚀 Feature Proposal
Make loadable.preload() return a promise

## Motivation

I'm implementing a "prefetcher" that will, depending on some conditions, request a bunch of known loadable components from an "index" object whose keys are strings and values loadable-components. At some point, I call preload on a bunch of these and I need a way to await on the loading promise of all components, seems like the only change necessary is to add a `return` statement at the end of the `preload()` function.

## Pitch

To be honest, I kind of expected this to work, I was surprised `preload()` returns undefined.

**Comment by theKashey** [comment]
There is a long discussion, and the solution you are looking for - https://github.com/smooth-code/loadable-components/pull/226

**Comment by neoziro** [comment]
Hello @luishdz1010, `.preload()` is a "preload" action so it can't return a promise. If we expose this API, it will be under `.load()`. But I think it is not the good approach to take, with "Suspense" you will not be able to wait for component to be loaded this way. I suggest you to create your own load method if you want to do it. I prefer to wait for Suspense before adding this kind of API.

**Comment by luishdz1010** [comment]
My bad for not looking hard enough 🤦‍♂️, thanks for the quick reply.
