### ISSUE TITLE
async get loadable-stats.json

### ISSUE THREAD

**Issue by Pecking** [smooth-code/loadable-components#286]
When I get the loadable-stats.json file asynchronously,

For example: webStats = await axios. get('http://127.0.0.1:4000/public/loadable-stats.json');

Get an error, Unhandled PromiseRejection Warning: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object

**Comment by neoziro** [comment]
Hello @Pecking? I am sorry but it looks not related to loadable at all, I suggest you to load it synchrously by reading file instead of loading it using axios. I can’t help you more, I am sorry, please refer to examples and documentation.

**Comment by Pecking** [comment]
OK,thanks,
