### ISSUE TITLE
Is it only possible to import modules relative to __dirname on server without webpack?

### ISSUE THREAD

**Issue by gazs** [smooth-code/loadable-components#293]
## 💬 Questions and Help

Apologies for this question, I am not sure if this is a bug/limitation of loadable-components or if I am simply using it incorrectly.

I am trying to load a module from node_modules, which works fine on clientside, but compiles into code that tries to require() an incorrect absolute path when it is run through node.

Using `@loadable/babel-plugin`, the following code:

```js
const LocaleData = loadable.lib(() => import('react-intl/locale-data/de'))
```

is compiled into:

```js
const LocaleData = _component.default.lib({
  chunkName() {
    return `react-intl-locale-data-de`.replace(/[^a-zA-Z0-9_!§$()=\-^°]+/g, "-");
  },

  isReady(props) {
    if (typeof __webpack_modules__ !== 'undefined') {
      return !!__webpack_modules__[this.resolve(props)];
    }

    return false;
  },

  requireAsync: () => Promise.resolve().then(() => _interopRequireWildcard(require(`react-intl/locale-data/de`))),

  requireSync(props) {
    const id = this.resolve(props);

    if (typeof __webpack_require__ !== 'undefined') {
      return __webpack_require__(id);
    }

    return eval('module.require')(id);
  },

  resolve() {
    if (require.resolveWeak) {
      return require.resolveWeak(`react-intl/locale-data/de`);
    }

    return require('path').resolve(__dirname, `react-intl/locale-data/de`);
  }

});

```

It looks like on the server the `resolve()` method is called (via [InnerLoadable#loadSync](https://github.com/smooth-code/loadable-components/blob/master/packages/component/src/createLoadable.js#L54)), which in turn calls:

```js
require('path').resolve(__dirname, "react-intl/locale-data/de");
```

Which gives me the error:
```text
Cannot find module '/Users/gazs/[my-project]/src/app/components/Intl/react-intl/locale-data/de'
```

What am I doing wrong?

**Comment by neoziro** [comment]
Hello @gazs, I think it is a problem in Loadable Components yes. But I think you could use `import(require.resolve('...'))` as a workaround. Tell me if it works.

**Comment by gazs** [comment]
hi @neoziro thanks for your help. Unfortunately that doesn't work as babel fails to compile:

```
Babel compilation error TypeError: Property value expected type of string but got null
```

Do you think putting the require.resolve() bit into the loadable babel-plugin could work?

**Comment by gazs** [comment]
I've worked around the issue by having relative-path accessible js files that in turn import the npm module:

```js
const LocaleData = loadable.lib(() => import('./locales/de'))
```

and then in `./locales/de`:
```js
export {default as de} from 'react-intl/locale-data/de'
```

In practice this is not as clumsy as it first seems as we needed to conditionally import multiple locale-related files anyway...

Thanks for your work on this library!

**Comment by neoziro** [comment]
Yeah I think we should be able to support it. I let it opened to track it.

**Comment by neoziro** [comment]
Fixed in last version.
