### ISSUE TITLE
Documentation about minimum supported versions of React and Webpack

### ISSUE THREAD

**Issue by TheSisb** [smooth-code/loadable-components#294]
Could you add some documentation to the README or website to indicate which version of React and Webpack is required to use this library please?  

Looks like the minimum required React is listed in https://github.com/smooth-code/loadable-components/issues/145 at 16.x now, an easier way to view this information would be appreciated.  

Great lib btw!

**Comment by neoziro** [comment]
Hello, yeah of course. The requirement is React v16.3+ and Webpack v4+. A PR to update documentation is welcome!
