### ISSUE TITLE
TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by Nasirilahi** [smooth-code/loadable-components#296]
I am maintaining a react library. In this library i have one entry file from which i am exporting my two main component. If i am importing them in regular way then it is working fine but my bundle size is going above required bundle size. 

So i tried importing dynamically those two components which i am exporting from main entry file and i can see that **chunks** are being created for bundle but after publishing my library to _npm_ and installing it in another project i am getting `TypeError: Cannot read property 'bind' of undefined`. I have gone through the docs and have configured the projects properly with respect to code splitting but still getting error every time.

**Comment by theKashey** [comment]
Just double check browser console. This error should have an exact location and an exact reason.

PS: Please don't use any sort of code-splitting inside a library, delegate it to the user code base. You __can not__ ship untranspiled `import`, required for code splitting, among es5 compatible library code.

**Comment by Nasirilahi** [comment]
@theKashey  in console i am getting above specified error. for error location, since i am using it in another project which is using minified version of my code and that is why i am not able to track it.  
And yes i am doing it in my code base. may be you didn't get my use correctly. So i have one react project which is basically a react library in which i am doing code splitting but when i am installing this library after publishing in to another project then in that project i am getting above error. 

Hope you got my issue now

**Comment by theKashey** [comment]
Yep, I've got your issue. No code splitting is possible on the `library` side. The `another project` should handle it.
Anyway - there a magic button in Chrome DevTools - `pretty print`, it should help you figure out what is the problem.
__Nobody except you__ could do it. Nobody.

**Comment by Nasirilahi** [comment]
Yes @theKashey  i have tried tracking the issue in formatted by printing it in` pretty print`  but still it is not depicting exact location of this error that is why i am not able to track it. 

And can you please explain me why i can not achieve this at library side. As i can see chunks are being created for all dynamic imported components so i think we can do code splitting for library type project. CMIIMW @theKashey

**Comment by Nasirilahi** [comment]
@theKashey  can you please better suggest me how can i achieve this ?  It will be helpful if you can tell me an example if there exist. 

What about this your library [https://github.com/theKashey/react-imported-component](https://github.com/theKashey/react-imported-component) ?  Can i achieve library level code splitting using this library?

**Comment by theKashey** [comment]
One more time - code splitting code __should not__ be on a "library side". 

It could, but you have to configure `.babelrc` to skip modules transformation (`modules:false`) and ask not to transform `dynamic import`, using only _syntax_ plugin.

In any other case you will get or code transpiled for node (would not run in a browser), or a syntax error `import is not defined`.

Probably you run into the first case. But there is too many unknowns - starting from how you compile your library and ending how you use it.

Yet again - unless you provide an example, you are the only one who could answer these questions.

**Comment by Nasirilahi** [comment]
@theKashey  Can you please more elaborate how and what to configure in .babelrc? 
And for providing example, i have to publish a new project on npm with same use case  and then only you can check but i can't give current project.

**Comment by theKashey** [comment]
I encourage you to learn more about the thing you are using, or stop using it without proper domain knowledge. As I said - _code splitting code should not be on a "library side"_, and the problems you are facing is something you shall face.

Try to solve this puzzle without cheating from my side. Only one tip for you - `import` shall still be `import` in the _final_ library sources, you are publishing to the npm.

**Comment by Nasirilahi** [comment]
Thanks @theKashey  for encouraging and i am going in deep as much as i can. I think it is fine in my case to do code splitting as only there are two export statements not like many exports for many components.
