### ISSUE TITLE
How do I not split css style files?

### ISSUE THREAD

**Issue by blockmood** [smooth-code/loadable-components#297]
## 💬 Questions and Help

Loadable Components project is young, but please before asking your question:

- Read carefully the README of the project
- Search if your answer has already been answered in old issues

After you can submit your question and we will be happy to help you!

**Comment by theKashey** [comment]
setup a webpack css-loader of your not to split it.
In case of https://github.com/webpack-contrib/mini-css-extract-plugin - just provide a same name (style.css?) for all the chunks.

**Comment by fatemab** [comment]
I also have this issue. I have code-split my js code by making separate bundles for separate components. but loadable-components also makes css bundles. It also preloads that bundle with highest priority even if the css is not required at that time.
I get a warning 
`The resource http://../mobile.style.d2c3934beebbaf61b9cc-split.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
 `

I don't want the unnecessary css links to load. what should I do?

**Comment by blockmood** [comment]
@fatemab If the style is lost due to splitting the CSS separately, you can select the style you want to import in the main entry file.

**Comment by neoziro** [comment]
To answer the first question of this thread. If you want your CSS to not be splitted, just import it into your entry file `main.js` or `index.js`. This is a webpack and css extraction issue, it is not relative to loadable components. We read splitted modules directly from webpack configuration, we do not split modules.
