### ISSUE TITLE
Absolute node_modules paths are not getting resolved during SSR

### ISSUE THREAD

**Issue by fatemab** [smooth-code/loadable-components#301]
## 💬 Questions and Help

I am not sure if this issue is similar to #293.
I am importing a component from node_modules. 
`const ComponentName = loadable(() =>
        import("@nodeModuleName/[path-to-component]")
);`

This import runs on client side. (i.e., when I run using { ssr: false }, the component gets load). But it does not load on server side. Throws error 
`Cannot find module '/Users/[my-project]/@nodeModuleName/[path-to-component]'`

the import gets resolved to
```
var ComponentName = (0, _component.default)({
  chunkName: function chunkName() {
    return "ComponentName";
  },
  isReady: function isReady(props) {
    if (typeof __webpack_modules__ !== 'undefined') {
      return !!__webpack_modules__[this.resolve(props)];
    }

    return false;
  },
  requireAsync: function requireAsync() {
    return import(
    "@nodeModuleName/[path-to-component]");
  },
  requireSync: function requireSync(props) {
    var id = this.resolve(props);

    if (typeof __webpack_require__ !== 'undefined') {
      return __webpack_require__(id);
    }

    return eval('module.require')(id);
  },
  resolve: function resolve() {
    if (require.resolveWeak) {
      return require.resolveWeak("@nodeModuleName/[path-to-component]");
    }

    return require('path').resolve(__dirname, "@nodeModuleName/[path-to-component]");
  }
});
```
Issue #293 mentioned that he is not using webpack but I do use webpack, then also getting error.
Any help is appreciated

**Comment by theKashey** [comment]
so - does `/Users/[my-project]/@nodeModuleName/[path-to-component]` exists, or path is a bit different?

**Comment by fatemab** [comment]
The path should be `/Users/@nodeModuleName/[path-to-component]` i.e., pointing the absolute path of node_modules. but instead the resolve function considers this node_modules absolute path, a relative path and appends it to `path/_dirname`. How should I inform the loadable components that this is an absolute path to node_modules?

**Comment by neoziro** [comment]
I think the problem is here:

```js
return require('path').resolve(__dirname, "@nodeModuleName/[path-to-component]");
```

We should replace it by:

```js
return eval('require.resolve')("@nodeModuleName/[path-to-component]");
```

What do you think @theKashey?

**Comment by theKashey** [comment]
Yes, `require.resolve` is a more proper way especially for this case, where a module is defined above the project.
In the same time, I urge you to reconsider this, as long any module imported by `@nodeModuleName` would also be resolved to a module "above" the project root. That may cause a bundle size increase or a __complete failure__, as long as some packages(react, styled-components) has to present in a single variant.

**Comment by neoziro** [comment]
I don't get the last point, could you explain more?

**Comment by theKashey** [comment]
- `/Users/[my-project]/App.js` - our "root"
- `/Users/[my-project]/node_modules/react` - could be resolved from the current root
- `/Users/@nodeModuleName/[path-to-component]` - it's "above"
- `/Users/react` - would use this one
- `/Users/node_modules/react` - or this one

During module resolution, it goes "up" and trying to find a module in the nested _well known paths_, like `node_modules`.

So - in this example something very bad would happen, if `@nodeModuleName` got resolved properly and no _lerna_, _workspaces_ or _aliases_ were set. And were not, as long as have an exception.

**Comment by fatemab** [comment]
I think I might have not clearly written the paths. My node_modules are not above the project.

The path is getting resolved to:
`/Users/[id]/[projectName]/src/client/components/[folder_where_component_is_imported]/[componentName]` Which is wrong

It should get resolved to
`/Users/[id]/[projectName]/node_modules/[componentName]` 

And My import statement is
`const ComponentName = loadable(() => import("node_modules/[componentName]") );`

**Comment by theKashey** [comment]
Then `require.resolve` would save the day.

**Comment by fatemab** [comment]
Yes, When I changed the buildStatements in resolve.js to require.resolve it worked. I would like to raise a PR for this in loadable-components repo.

**Comment by neoziro** [comment]
@theKashey, I think it is not our problem. I will switch to require.resolve strategy.

**Comment by geekf** [comment]
@neoziro Any particular reason why are you using eval? I see the same pattern in requireSync and was just curious. 
So why - `return eval('require.resolve')(ID)`
Why not - `return require.resolve(ID)`

**Comment by neoziro** [comment]
Because webpack emits warning about it, it tries to parse it to know which modules are required. Without eval it will warn about a full dynamic require that can’t be resolved. In our case this code will not be reaches by webpack, so we just avoid warning using eval.

**Comment by fatemab** [comment]
@neoziro Thank you so much for such a prompt release!
