### ISSUE TITLE
could getScriptTags() returns a JSON

### ISSUE THREAD

**Issue by Wallaka** [smooth-code/loadable-components#304]
Hi,

I would like to know if there is anyway to get a JSON instead of a string with the function `getScriptTags()`

My use case is that i would like to alter chunk's path in the script, filter them or whatever and for now i only get a string directly.

I read the README but could not find something that helps me.

**Comment by neoziro** [comment]
Hello @Wallaka, even if it is not documented, you could use [`getMainAssets`](https://github.com/smooth-code/loadable-components/blob/master/packages/server/src/ChunkExtractor.js#L309). It should be what you are looking for.
