### ISSUE TITLE
Absolute paths in public/dist/web/loadable-stats.json

### ISSUE THREAD

**Issue by valorloff** [smooth-code/loadable-components#306]
## 💬 Questions and Help

- Search if your answer has already been answered in old issues

> done

First of all thanks for your job!
On local comp, app based on your package works, but if i deploy it to production, in loadable-stats.json remain absolute "outputPath": "/home/myuser/projects/lc0/public/dist/web", and prod app dont work as expected
`UnhandledPromiseRejectionWarning: Error: Cannot find module '/home/xxxxxx/projects/lc0/public/dist/node/main-bundle-4fcad2fb.js'
`
what can be done with it? Thanks.

**Comment by neoziro** [comment]
Hello @valorloff, you have to specify the `outputPath` in the ChunkExtractor, this way it will override it. https://www.smooth-code.com/open-source/loadable-components/docs/api-loadable-server/#chunkextractor

**Comment by valorloff** [comment]
But this is the default resolving outputPath to absolute path like:
`/home/xxxxxx/projects/lc0/public/dist/node/`
which correct on local comp only!
in stats.json file paths should look like /public/dist/...,  not /home/user/...., 
no?

**Comment by valorloff** [comment]
after I changed by this way:
```
const nodeExtractor = new ChunkExtractor({
            statsFile: nodeStats,
            outputPath: path.resolve('public/dist/node')
        });
```
and
```
        const webExtractor = new ChunkExtractor({
            statsFile: webStats,
            outputPath: path.resolve('public/dist/web')
        });
```
works as expected! Thanks!
