### ISSUE TITLE
Unnecessary chunk is being created for the test files.

### ISSUE THREAD

**Issue by q2870030** [smooth-code/loadable-components#308]
I have jest test files located in the same location as the component. For instance, the Header directory contains HeaderComponent.tsx, Header.test.js, and the __snapshots__ sub directory. Unfortunately, @loadable/babel-plugin is generating views-Header-Header-test.js and views-Header-__snapshots__-Header-test-js-snap.js, which are not necessary. The relevant part from by webpack config is below.  

``` javascript
// .js, .ts, .tsx loader
      {
        exclude: /node_modules/,
        test: /\.(js|ts|tsx)$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              plugins: [
                '@babel/plugin-proposal-class-properties',
                '@babel/plugin-syntax-dynamic-import',
                '@loadable/babel-plugin',
              ],
              presets: [
                [
                  '@babel/preset-env',
                  {
                    modules: false,
                    targets: {
                      browsers: ['>0.2%', 'not dead', 'not ie <= 11', 'not op_mini all'],
                    },
                  },
                ],
                '@babel/preset-react',
                '@babel/preset-typescript',
              ],
            },
          },
        ],
      },
```

I have tried other exclude patterns too, but @loadable/babel-plugin is still including test files.

Please help. Thanks.

**Comment by neoziro** [comment]
Hello @q2870030, your issue is not relative to loadable components but a webpack issue. I suggest you to move your tests in another folder. I don't have any workaround for you.

**Comment by q2870030** [comment]
@neoziro Hi Greg, thanks for your help here. Could you please explain me how/why it's a webpack bug? I am sure I am missing something, but if I don't use '@loadable/babel-plugin' in the plugin section in above code, then there are no extra files for the test files. 

```javascript
plugins: [
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-syntax-dynamic-import',
],
```

Please guide me to understand how it's a webpack issue, and I'll create a bug there. Thanks again for your help.

**Comment by neoziro** [comment]
Webpack dynamic import parses all available files. They are not generated by loadable, in fact it is not even a bug. It’s a feature.
