### ISSUE TITLE
The module number appears in the package. How do I remove the module number? This module was added when I was routing and loading, and it is specified as a file name similar to 31ffad51-2.chunk

### ISSUE THREAD

**Issue by blockmood** [smooth-code/loadable-components#309]
## 💬 Questions and Help

Loadable Components project is young, but please before asking your question:

- Read carefully the README of the project
- Search if your answer has already been answered in old issues

After you can submit your question and we will be happy to help you!

The routing configuration

![22](https://user-images.githubusercontent.com/22879524/56183164-dc829280-6047-11e9-85a7-a1007cf74ab4.jpg)

compiled

![1555390016141](https://user-images.githubusercontent.com/22879524/56183132-a9400380-6047-11e9-97ca-6731ef9ae7c7.jpg)

How to remove module number ？

**Comment by neoziro** [comment]
I think it is automatically generated by webpack isn’t it?
