### ISSUE TITLE
Flash of unstyled content (FOUC) issue

### ISSUE THREAD

**Issue by joserocha3** [smooth-code/loadable-components#31]
I get the the component without styles for a split second before the page fully loads. Using `react-router` v4, `styled-components` and `create-react-app` (unejected). The FOUC only happens on initial component mounts, subsequent mounts are either not affected or it happens too fast to see.

``` javascript
const Home = Loadable(() => import('./pages/Home'))

// ~~~ //

<Router>
  <Route exact path='/' component={Home}/>
</Router>
```

**Comment by neoziro** [comment]
It is expected if you defer your component loading, three solutions:

- Adding a loader
- Remove code splitting on Home
- Server-side rendering
