### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

### ISSUE THREAD

**Issue by FuncWei** [smooth-code/loadable-components#310]
## 💬 Questions and Help

Loadable Components project is young, but please before asking your question:

- Read carefully the README of the project
- Search if your answer has already been answered in old issues

After you can submit your question and we will be happy to help you!

![image](https://user-images.githubusercontent.com/16984724/56203457-e1f7d100-6077-11e9-8271-6c27fc156bb6.png)

**Comment by neoziro** [comment]
Hello @FuncWei, submitting a screenshot is not very respectful. But I deduce you are using a old version of react-router in wich, prop types were not correct.
