### ISSUE TITLE
__LOADABLE_REQUIRED_CHUNKS__ is always empty.

### ISSUE THREAD

**Issue by xkguq007** [smooth-code/loadable-components#312]
## 💬 Questions and Help

Loadable Components project is young, but please before asking your question:

- Read carefully the README of the project
- Search if your answer has already been answered in old issues

After you can submit your question and we will be happy to help you!

Sorry for bad English.
I try to implements chunking in ssr projects for production.
Example of this ssr, it works well with expected __LOADABLE_REQUIRED_CHUNKS__.
However, In my projects, It never seen. it always '[]'.
I copied your Webpack, Babel config in my project.

With little more detail,
In Your sample, I've been downloaded and executed.
```
<script id="__LOADABLE..." type="application/json">[0, 1, 2, 8]</script>
<script async data-chunk="main" src="..."></script>
<script async data-chunk="letters-A" src="..."></script>
...
```
This works well.

However, In my project, It always has only main.
```
<script id="__LOADABLE..." type="application/json">[]</script>
<script async data-chunk="main" src="..."></script>
```
IMPORTANT THING is, In head tags, I'm NOT INSERTING IT, it automatically insert this line which is must insert chunked js file. so my project works that I expected. but it feels not properly.
```
<script charset="utf-8" src="..."></script>
<script charset="utf-8" src="..."></script>
```

I don't know where am I doing wrong. I've been 5 working days to solve this weird thing....
Please help me.
**Conclusion is basically my project copied your example of ssr and converted typescript and added redux, redux-saga.
It works I expected, without this wierd problem. Of course this wierd problem does not makes any error, or malfunctioning. I'm just curious that why script does not insert properly.**

p.s.
I dig in bundled file, I think that automatically inserted line seemed did by Webpack. (I don't know which plugin did it.)

**Comment by neoziro** [comment]
Hello @xkguq007, we would be happy to help you. For that the best is to submit a public repository to be able to investigate and reproduce the problem. Thanks!

**Comment by xkguq007** [comment]
okay, This repo should be considered that public able or not. Because part of company work. Please do not close this issue, I'll ask and reply within 3days.

**Comment by xkguq007** [comment]
I've been late because company doesn't allow this codes to outside. I'll make similar codes in my personal repo. thx.

**Comment by neoziro** [comment]
I close it, it is outdated. Feel free to open another issue if you experience a problem.
