### ISSUE TITLE
chunkName BUG

### ISSUE THREAD

**Issue by tianzewen** [smooth-code/loadable-components#316]
loadable-components/packages/babel-plugin/src/properties/chunkName.js
56 row

`function replaceQuasi(str, stripLeftHyphen) {
  if (!str) return ''
  const result = str.replace(WEBPACK_PATH_NAME_NORMALIZE_REPLACE_REGEX, '-')
  if (!stripLeftHyphen) return result
  return result.replace(MATCH_LEFT_HYPHENS_REPLACE_REGEX, '')
}`

should

`function replaceQuasi(str, stripLeftHyphen) {
  if (!str) return ''
  const result = str.replace(WEBPACK_PATH_NAME_NORMALIZE_REPLACE_REGEX, '-')
.replace(WEBPACK_MATCH_PADDED_HYPHENS_REPLACE_REGEX, '')
  if (!stripLeftHyphen) return result
  return result.replace(MATCH_LEFT_HYPHENS_REPLACE_REGEX, '')
}`

**Comment by neoziro** [comment]
Hello @tianzewen, could you submit another issue with a correct template please? I don't see the bug and I don't see what you are trying to fix.
