### ISSUE TITLE
image not working after build with cra and server side rendering

### ISSUE THREAD

**Issue by fadiquader** [smooth-code/loadable-components#32]
i have integrated loadable-components with create react app and server side rendering, but the problem has appeared, invalid path like capture below ! 
[object Object]
![image](https://user-images.githubusercontent.com/23264052/35681505-3d9b75f0-0766-11e8-8406-93254139b372.png)

**Comment by neoziro** [comment]
I don't understand the link between loadable-components and your screenshot, can you please give more context?

**Comment by fadiquader** [comment]
suppose you have project with cra, and you  import image like the following
```
// App component 
import logo from './logo.svg';
....
<img src={logo} alt="logo" />
```

I think the problem with url loader, when component is rendering in server side, it doesn't resolve the path, and return empty object.
src="[object Object]"

**Comment by neoziro** [comment]
Yeah probably, this is not relative to `loadable-components`. Your problem is a current server-side rendering issue. You are trying to use a Webpack loader server-side.

**Comment by xFloooo** [comment]
I have a similar problem, the server and the client generate different paths to the picture.

in component file
```javascript
import gift from "../../icons/gift@2x.png";
...
render(){
    ...
    return <img alt={"gift"} className={classes.image} src={gift} />
}
```
After starting the application, I get `Warning: Prop `src` did not match. Server: "/dist/node/application/icons/gift@2x.png" Client: "/dist/web/application/icons/gift@2x.png"`

**webpack.config** - taken from your example for **SSR** with the addition **url-loader**

```javascript
            {
                test: /\.(pdf|png|jpg|ttf|eot|svg|woff|woff2)(\?[a-z0-9#=&.]+)?$/,
                use: [
                    {
                        loader: "url-loader",
                        options: {
                            limit: 8192,
                            name: "[path][name].[ext]"
                        }
                    }
                ]
            }
```
could you help me with this?

**Comment by xFloooo** [comment]
solved a problem in **webpack.config** set **publicPath**

```javascript
//publicPath: `/dist/${target}/`,
publicPath: `/dist/web/`,
```

**Comment by neoziro** [comment]
I think your fix is right, but be careful hash could diverge. Another fix would be to expose node directory client side.
