### ISSUE TITLE
Control ssr via props ?

### ISSUE THREAD

**Issue by revskill10** [smooth-code/loadable-components#324]
Currently, `{ ssr: true}` or `{ ssr: false}` must be set beforehand.

My question is, is it possible to dynamically set ssr property via component props ?

```js
const Parent = (props) => {
  const Child = loadable(() => import('./some-component'), { ssr: props.ssr });
  return <Child />
};
```

**Comment by theKashey** [comment]
That's not possible, but you can render/not render something basing on your own logic.
