### ISSUE TITLE
getStyleTags only returns main CSS

### ISSUE THREAD

**Issue by thoughtbyte** [smooth-code/loadable-components#325]
## 💬 Questions and Help

Hi, I am using this package with a SSR setup. `getStyleTags` appears to only return the main chunk. When a page is first loaded, its specific CSS is loaded via javascript. I would have though that `getStyleTags` would return the main CSS along with the page specific CSS chunks.

Is this behavior I'm seeing the intended behavior? I saw some issues about this in the context of streaming rendering, but we aren't doing that.

**Comment by neoziro** [comment]
Hello @thoughtbyte, to be honest I don't know if it is the correct behaviour or not. On my side, I don't use the `getStyleTags` method, I use styled-components or emotion so it is not necessary.

I think the best to solve this, is to exchange with other users of `getStyleTags` to see what are the problematics and what is the real need.

**Comment by thoughtbyte** [comment]
it looks like it is not the correct behavior, `getStyleTags` should be collecting the main chunk, and other referenced chunks for the route. at least according to this test:

https://github.com/smooth-code/loadable-components/blob/master/packages/server/src/ChunkExtractor.test.js#L329

Does anyone else know of any gotchas that could cause a bug here? My setup is almost the same as the example repo but we are using css modules.

**Comment by thoughtbyte** [comment]
I have found a work-around for now, and it's the same thing mentioned in the issues regarding stream rendering: [used-styles](https://github.com/theKashey/used-styles). After `chunkExtractor` does its work I can use this package to get a list of css files needed, and I concat these to whatever `getStyleTags` returned. It still seems like unintended behavior, but it works fine this way. Thanks again!

**Comment by neoziro** [comment]
I close it for now, we will fix it if it comes again.
