### ISSUE TITLE
Is there a way to control code split chunk names ?

### ISSUE THREAD

**Issue by xtroncode** [smooth-code/loadable-components#334]
## 💬 Questions and Help

Hi,
Thanks for this awesome repository. 
Automatic chunk names are great but is there a way to control the chunk names generated by loadable-components ?

**Comment by theKashey** [comment]
🤷‍♂️ https://webpack.js.org/api/module-methods#magic-comments

**Comment by neoziro** [comment]
@theKashey has the good answer. Note that the chunkName is overrided by Babel plugin for full dynamic import, else they are respected.

**Comment by xtroncode** [comment]
@theKashey  Thanks. I was placing the magic comments before the import statement. Sorry for the trouble.
