### ISSUE TITLE
Confused about the default built target 'Node'

### ISSUE THREAD

**Issue by luqimin** [smooth-code/loadable-components#335]
Babel will not transform any ES 2015+ code now, and this brings me some trouble..

**Comment by neoziro** [comment]
Glup, I am sorry, I think the @babel/preset-env is not applied. I will submit a fix today, sorry.

**Comment by luqimin** [comment]
sry, it seems like `packages/component/rollup.config.js` caused this problem. 
`['@babel/preset-env', { loose: true }]` is missing in the `presets` config

**Comment by luqimin** [comment]
> Glup, I am sorry, I think the @babel/preset-env is not applied. I will submit a fix today, sorry.

thanks a lot

**Comment by neoziro** [comment]
I publish a new version, thank you.
