### ISSUE TITLE
Docs app responding `503`

### ISSUE THREAD

**Issue by marcdavi-es** [smooth-code/loadable-components#338]
## 💬 Questions and Help

I've been trying for a little while to get to your docs app but I'm getting a `503`...

![Screenshot 2019-05-16 at 12 20 20](https://user-images.githubusercontent.com/8591501/57846792-4623c700-77d5-11e9-81b0-3d328b8926cc.png)

Heroku is ok https://status.heroku.com/ 

I'm sure it's something straightforward. Thanks for all your work on this great project :)

In the meantime I'll refer to https://github.com/smooth-code/loadable-components/tree/master/website/src/pages/docs

**Comment by neoziro** [comment]
Hello @marcdavi-es, we are working on this, thank you!

**Comment by neoziro** [comment]
It is fixed.
