### ISSUE TITLE
How do I build a loadable/components using webpack?

### ISSUE THREAD

**Issue by konojunya** [smooth-code/loadable-components#339]
## 💬 Questions and Help

The typescript is compiled via webpack's `babel-loader` . At this time, `@loadable/babel-plugin` is described in plugins in `.babelrc` , but the following error is output at execution time.

`Invariant Violation: loadable: SSR requires @loadable/babel-plugin, please install it`

<img width="1552" alt="スクリーンショット 2019-05-17 9 26 10" src="https://user-images.githubusercontent.com/12035578/57895284-d28dc280-7885-11e9-9003-30d49bcebc4f.png">

## procedure

1. git clone https://github.com/konojunya/universal-react-application-sample.git
2. cd universal-react-application-sample
3. yarn
4. yarn dev

You can now reproduce the above error.

**Comment by clodal** [comment]
See #263 for more info on your error

**Comment by neoziro** [comment]
Close as duplicate.
