### ISSUE TITLE
Why is this a problem ?

### ISSUE THREAD

**Issue by blockmood** [smooth-code/loadable-components#340]
## 💬 Questions and Help

Loadable Components project is young, but please before asking your question:

Refused to execute script from 'https://www.xxx.cn/static/8-124.chunk.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

Uncaught (in promise) Error: Loading chunk 57 failed.

**Comment by theKashey** [comment]
What is inside that file? It is the script you expected to see, or something else, like 404 page?

**Comment by blockmood** [comment]
@theKashey  The request is 404

**Comment by theKashey** [comment]
That's the reason. Now you have to figure out the right name for a chunk and then it would be more clear what is wrong.

**Comment by codeandgraphics** [comment]
Faced the same problem, it happens when app already running, publish new one version, then try to go to some chunked component. So this old one chunk missed. It's obvious behavior, but how to avoid this issue?

**Comment by neoziro** [comment]
You are facing a problem of rolling deploy, nothing related to this library. You have to keep old assets when deploying and to remove them a few days later.
