### ISSUE TITLE
Doc Links don't work sometimes

### ISSUE THREAD

**Issue by aseem2625** [smooth-code/loadable-components#341]
Following links are not working in documentation doesn't work sometimes (consistently).

https://www.smooth-code.com/open-source/loadable-components/docs/error-boundaries/
https://www.smooth-code.com/open-source/loadable-components/docs/delay/
https://www.smooth-code.com/open-source/loadable-components/docs/suspense/

![image](https://user-images.githubusercontent.com/6055628/57910583-3c689500-78a3-11e9-83a9-abbf4d67ae02.png)

It's probably with all links when trying to open directly in the new tab by clicking on right NAV
![image](https://user-images.githubusercontent.com/6055628/57910605-51452880-78a3-11e9-881e-37bfdf16c240.png)

**Comment by neoziro** [comment]
Hello, we are working on this, thank you!

**Comment by neoziro** [comment]
It is fixed.
