### ISSUE TITLE
Get CSS and JS for requested chunk at server itself

### ISSUE THREAD

**Issue by aseem2625** [smooth-code/loadable-components#343]
When a route is requested from server, I need to find all the required style and bundle required for that route.

```
import { ChunkExtractor, ChunkExtractorManager } from '@loadable/server';
const statsFile = path.resolve('./loadable-stats-web.json');

const extractor = new ChunkExtractor({ statsFile }); // Do I need to pass more params here to get my case working?
const scriptTags = extractor.getScriptTags();
const styleTags = extractor.getStyleTags();

extractor.getRequiredChunksScriptContent() // . This is giving empty array.
```
This gives me script and style tags for `base` and `vendor` bundle. **BUT the requested chunk's JS and CSS are not included here**. It's this `base.js` bundle when loaded on browser makes request to corresponding chunk.

**How we can achieve that** in such a way that loadableReady includes that chunk's JS and CSS as well for that loadableReady( ofcourse on client)?
```
import { loadableReady } from '@loadable/component';
```

---

I can do the same in `react-loadable`

```
import { getBundles } from "react-loadable/webpack";
const stats = require("./react-loadable-web.json");

getBundles(stats, modules);
```
This gives me the required chunk's JS and CSS but the limitation is it doesn't include `base` and `vendor` bundle's JS/CSS

and hence, opposite to `loadable-components`, Loadable.preloadReady won't include `main` and `vendor` bundle's CSS and JS to load.
```
import Loadable from "react-loadable";
Loadable.preloadReady()
```
So, for `react-loadable`, I've to implement loading vendor and base bundle before chunk's JS/CSS. But not sure how to know the chunk in case of `loadable-components` while at server

**Note:** I'm having only one entry point for JS `base`. style for base's CSS are extracted using `mini-css-extract` plugin. And vendor is split using webpack's `Splitchunks`.

**Comment by aseem2625** [comment]
**I'll simplify my query.** I'm able to make SSR work using "loadable-components". 

When the app loads in the browser, it's the main bundle which inserts the requested route's chunk in DOM, as I'm not able to get the requested chunk on server. 

This works fine but I need to get requested route's chunk's JS+CSS file on server side itself. **How can we do that?**

```
const scriptTags = extractor.getScriptTags();
const styleTags = extractor.getStyleTags();
```
This only gives me `vendor.js` and `main.js` and `main.css`

**Comment by aseem2625** [comment]
@Rid
Would have take 4-5min to read my query. I said **chunking is working**. 

Anyways, ignore. I found in some article saying that this lib behaves in same manner as in my post. So, using react-loadable for my purpose.

**Comment by neoziro** [comment]
@aseem2625 you should not use react-loadable, but anyway if it fits your needs, stick with it.

**Comment by Rid** [comment]
@aseem2625 did you tag me in by a mistake? I'm not the maintainer of this project. We're using it in https://github.com/wellyshen/react-cool-starter

**Comment by aseem2625** [comment]
Yeh, right @Rid. Actually, you referenced it to the wrong issue, so I tagged you.

@neoziro I'm not sure why shouldn't use `react-loadable`? I also actually noticed that it's having slightly lesser size than `loadable-components`. 

My requirement was to have chunk JS/CSS info available at the server only. But it's being available at browser side. So, wanted to reduce the latency. I could make chunking perfectly working with `loadable-components` but couldn't find way to do that part.

**Comment by neoziro** [comment]
@aseem2625 react-loadable have issue tab closed and only merge PR that modifies docs. The project is literally dead. It is not compatible with new features coming into React and not compatible with last versions of webpack. But yeah you could use it if you want.

**Comment by eseQ** [comment]
@neoziro Hi there! Thanks for this package.
I have the same issue. All work fine on client and load chunks correctly. But on ssr I have only
scriptTags
```javascript
<script id="__LOADABLE_REQUIRED_CHUNKS__" type="application/json">[]</script>
<script async data-chunk="main" src="/build/main.js"></script>
```
linkTags
```javascript
<link data-chunk="main" rel="preload" as="style" href="/build/main-30348124b.css">
<link data-chunk="main" rel="preload" as="script" href="/build/main.js">
```
styleTags
```javascript
<link data-chunk="main" rel="stylesheet" href="/build/main-30348124b.css">
```

**Comment by theKashey** [comment]
You have to use `clientStats` for the `SSR`. `nodeExtractor`(which does not contain `css` files) is not required at all - try to remove it and repeat.

**Comment by eseQ** [comment]
@theKashey thanks for a quick answer. I use nodeExtractor only to get App component. But without it, I have the same issue.
Where I should search the problem? On webpack side or in server code?

**Comment by theKashey** [comment]
Server code emits "chunk-name" of the used component and `ChunkExtractor` them maps those "reported chunks" to the assets, listed in "stats.json"
1 - double check that `.css` assets are listed in your `stats.json`
2 - next to the `js` assets for a specific chunk
3 - chunk names are the same for client and server. Ie chunk names which SSR would report are exists in clientside bundle, so one could load them.

**Comment by eseQ** [comment]
All my chunks has `webpackChunkName`.
For example, at the start, I render the `react-eq-posts-list` chunk and both `stats.json` has it.
Both build folders (ssr and client) has `react-eq-posts-list-chunk.js` and `react-eq-posts-list.css` files.
```javascript
...
    "react-eq-posts-list": [
      "react-eq-posts-list.css",
      "react-eq-posts-list-chunk.js"
    ],
...
"assets": [
...

    {
      "name": "react-eq-posts-list-chunk.js",
      "size": 78703,
      "chunks": [
        "react-eq-posts-list"
      ],
      "chunkNames": [
        "react-eq-posts-list"
      ]
    },
    {
      "name": "react-eq-posts-list.css",
      "size": 8635,
      "chunks": [
        "react-eq-posts-list"
      ],
      "chunkNames": [
        "react-eq-posts-list"
      ]
    },
...
]
...
```
But I have no one chunk.

**Comment by theKashey** [comment]
🤷‍♂️ I'm afraid it's not solvable without example.
However - try to add some `console.log` [here](https://github.com/smooth-code/loadable-components/blob/master/packages/server/src/ChunkExtractor.js#L301) to understand which chunks were reported to the extractor.

**Comment by eseQ** [comment]
Thanks for the idea.

<details>
  <summary>Result:</summary>

```javascript
[
  'react-eq-shape-overlay',
  'react-eq-menu',
  'react-eq-gallery',
  'react-eq-notifications-notify',
  'react-eq-notifications',
  'react-eq-theme-paper',
  'react-eq-posts-filter-calendar',
  'react-eq-cart-button',
  'react-eq-theme-paper-header-large',
  'react-eq-weather',
  'react-eq-tags',
  'react-eq-ui-feature',
  'react-eq-theme-paper-footer-content',
  'react-eq-theme-paper-auth-info',
  'react-eq-posts-list',
  'react-eq-social-share',
  'react-eq-card',
  'react-eq-special-block',
  'react-eq-comments'
]
```
</details>

<details>
  <summary>usedStyles can find that: </summary>

```javascript
[
  "app.css"
  "react-eq-card.css"
  "react-eq-comments.css"
  "react-eq-events~react-eq-events-form.css"
  "react-eq-gallery.css"
  "react-eq-notifications.css"
  "react-eq-places~react-eq-places-form.css"
  "react-eq-posts-list.css"
  "react-eq-posts-list~react-eq-posts-preview.css"
  "react-eq-posts-list~react-eq-posts-single.css"
  "react-eq-posts-list~react-eq-posts-single~react-eq-posts-theme-form.css"
  "react-eq-posts-preview.css"
  "react-eq-shape-overlay.css"
  "react-eq-shop-routes.css"
  "react-eq-social-share.css"
  "react-eq-tags.css"
  "react-eq-theme-paper-header-default~react-eq-theme-paper-header-large.css"
  "react-eq-theme-paper-header-large.css"
  "react-eq-theme-paper-news-aside.css"
  "react-eq-theme-paper.css"
  "react-eq-ui-feature.css"
]
```
</details>

I will try to understand how this package work and what happens with `this.chunks`.

**Comment by eseQ** [comment]
I found it!
Just `getMainAssets` exact before `addChunk`. Because I used it like:
<details>
  <summary>Wrong way</summary>


```javascript
const getExt = (url, { routerContext: RC, ...data }, routerContext, req) => {
  const extractor = new ChunkExtractor({ statsFile, entrypoints: ['app'] });
  const nodeExtractor = new ChunkExtractor({ statsFile: nodeStatsFile, entrypoints: ['node'] });
  const App = nodeExtractor.requireEntrypoint('node');
  const jsx = extractor.collectChunks(React.createElement(App, params));

  const scriptTags = extractor.getScriptTags();
  const linkTags = extractor.getLinkTags();
  const styleTags = extractor.getStyleTags();
  return { jsx, scriptTags, linkTags, styleTags };
};

const renderWithStream = (params) => {
  const { jsx, ...ext } = getExt(params);
  const htmlStream = ReactDOMServer.renderToNodeStream(jsx);
  ...
  return { htmlStream, ...ext };
};

const render = (params) => {
  const { jsx, ...ext } = getExt(params);
  const html = ReactDOMServer.renderToString(jsx);
  ...
  return { html, ...ext };
}
```
</details>

**IMPORTANT** use `renderToString` or `renderToNodeStream` before get scripts and styles with `extractor`.

```javascript
const renderStatic = (params) => {
  const { jsx, extractor } = getExt(params);
  const html = ReactDOMServer.renderToString(jsx); // <--- IMPORTANT before use extractor.get
  const scriptTags = extractor.getScriptTags();
  const linkTags = extractor.getLinkTags();
  const styleTags = extractor.getStyleTags();
  return { html, scriptTags, linkTags, styleTags };
}
```

Can I ask why it is so important? How `extractor` works with `ReactDOMServer`?

**Comment by theKashey** [comment]
Ok. So `renderToNodeStream` was the problem? That's understandable - by the time you are asking for `getScriptTags` - they are not yet rendered. See [the docs](https://www.smooth-code.com/open-source/loadable-components/docs/server-side-rendering/#streaming-rendering) for the proper setup.

**Comment by eseQ** [comment]
No `renderToNodeStream` just for example. In my case, I use simple `renderToString`. Now all right.

**Comment by place-tuan** [comment]
Wow i ran into the same issue that is fixed by https://github.com/smooth-code/loadable-components/issues/343#issuecomment-542523420. Never thought that `ReactDOMServer.renderToString` must be called before pulling the tags 🤯

**Comment by vickygaogao** [comment]
> 

i am still wondering how extractor works with ReactDOMServer?
