### ISSUE TITLE
I get an error. Check the render method of `InnerLoadable`

### ISSUE THREAD

**Issue by pavliha** [smooth-code/loadable-components#347]
When I try to navigate to other async component in react router I get
![image](https://user-images.githubusercontent.com/10353006/58401693-2909b680-8067-11e9-9aec-a9ba4fc8aca1.png)
And when I reload the page everything  works again
Issue reproduced here https://github.com/pavliha/ssr-app.

**Comment by neoziro** [comment]
Hello @pavliha, I gave a quick look in your code and everything looks fine for me. Maybe someone else could give a look and help you!

**Comment by pavliha** [comment]
Thanks for checking out this case @neoziro. For some reason await import('./TestScene') returns empty object 
![image](https://user-images.githubusercontent.com/10353006/58481355-e75f3580-8164-11e9-9376-6508a04c19b0.png)

**Comment by theKashey** [comment]
Double checked - `loadable` and `RHL` are not playing well together (no automatic reload), but no error is present.

**Comment by pavliha** [comment]
@theKashey. I've updated the repo maybe something was missing. Hmm maybe I could write some steps to reproduce an issue.  Just in case
1) yarn install 
2) rename .env.example to .env
3) yarn start
4) open http://localhost:2000
5) click on test link

In the updated repo. I have disabled source maps and connected sources of the @loadable/component  via webpack aliases

![image](https://user-images.githubusercontent.com/10353006/58540043-47a3b500-8201-11e9-986b-03b302ac31c2.png)

After trying to reproduce an issue multiple time. Sometimes everything start to work. But then again fails

**Comment by pavliha** [comment]
I have a similar setup but with webpack-dev-server and loadable works with react-hot-loader. It is webpack-dev-middleware that causing the problems. Official documentation for react-hot-loader says it's not yet supported

![image](https://user-images.githubusercontent.com/10353006/58540948-17f5ac80-8203-11e9-8291-d232349c78b8.png)

**Comment by theKashey** [comment]
That's now "official" documentation, as long as we dropped a ball on it a bit, but it's supported - the problem is more about proper configuration.
I will try to fill this gap in the documentation.

**Comment by pavliha** [comment]
@theKashey thank you a lot. Have you tried to find core problem in this particular case?

**Comment by theKashey** [comment]
Not yet.

**Comment by theKashey** [comment]
Long story short - everything is very bad:
- RHL thinks that HMR is "active"
- RHL does not sees `Index` and `Test` as a "registered" variables
- RHL does a false positive merge of `Index` and `Test`, thinking that `Index` "isReady"(exists in the cache), and then calling `requireSync` for `Test`. Don't ask.

**Comment by theKashey** [comment]
- HMR is open after `importing` a new code block. That's expected behavior
- False positive for `forwardRef`. Something to be fixed.

**Comment by theKashey** [comment]
- fix created. Will release a new version of RHL in an hour. No changes from `loadable-component` are required.

**Comment by Anatoool** [comment]
I have the same issue. I am using react-router-dom.

`
const HomePage = loadable(() => import(/* webpackPrefetch: true */ '../pages/AuthPages/HomePage'));
const RepresentativeRegistrationPage = loadable(() =>
  import(/* webpackPrefetch: true */ '../pages/AuthPages/RepresentativeRegistrationPage')
);

        <Route
          exact
          path={ROUTES.HOME_PAGE}
          render={(props) =>
             (!isAuthentificated ? <Redirect to={ROUTES.LOGIN} /> : <HomePage {...props} />)}
        />

        <Route
          exact
          path={ROUTES.REPRESENTATIVE_REGISTRATION}
          render={(props) => !isAuthentificated ? <Redirect to={ROUTES.LOGIN} /> : 
          <RepresentativeRegistrationPage {...props} />}
        />
`

When I have Redirect outside loadable It works fine. 

But when I am trying return <Redirect to={ROUTES.REPRESENTATIVE_REGISTRATION} /> inside Loadable component from <HomePage /> to <RepresentativeRegistrationPage /> a have error.

![image](https://user-images.githubusercontent.com/34212937/58632590-339aa900-8310-11e9-85f8-e5799418273a.png)

**Comment by theKashey** [comment]
I am on it. Just cant merge and deploy anything at 00:06

**Comment by theKashey** [comment]
React-Hot-Loader v4.9.0 should fix the issue.

**Comment by pavliha** [comment]
@theKashey man you are THE BEST!!!. Thank you

**Comment by theKashey** [comment]
I should say - sorry for affecting you all by this issue for a few months...
