### ISSUE TITLE
Dynamic publicPath in extractor and client side JS chunk loading

### ISSUE THREAD

**Issue by peeter-tomberg** [smooth-code/loadable-components#348]
## 💬 Questions and Help

#269 added support for publicPath to the extractor, so server side rendering works as expected, but if I try to load more bundles on the client side, this isn't taken into account and the hardcoded path is used instead. 

I'm building a product that will be split up into multiple single page applications, separated by routes. I've got an nginx proxy that directs traffic between these applications. 

* /app1/ -> goes into standalone SSRed+Codesplitted (on APP routes) SPA called app1
* /app2/ -> goes into standalone SSRed+Codesplitted (on APP routes) SPA called app2

I've set the publicPath so SSRing produces the correct link/script tags, but navigating from 
/app1/route1/ to /app1/route2/ loads more bundles and these seem to be ignoring the publicPath option I've set on the extractor.

Is this expected behavior? Should I simply hardcode the /app1/ and /app2/ publicPaths in webpack build time?

**Comment by neoziro** [comment]
Hello @peeter-tomberg, unfortunately I don't use the publicPath feature, so I am not sure of the right behaviour, I need to investigate it before. Any help is welcome!

**Comment by neoziro** [comment]
Loadable is only 2.29kb, and probably even less with tree shaking, so no I think it is not bigger than react-loadable. React-loadable does not expose ES modules so tree shaking is not effective.

**Comment by theKashey** [comment]
- loadable-component are working on a server side
- on the client side usage of `import` statement would be handled by your bundler (webpack) in the same way it would be handled by `React.lazy`.
- server and client side are working differently.

**Comment by peeter-tomberg** [comment]
Correct, the issue was I need to configure it in my bundler as well, this comment worked wonders: https://github.com/webpack/webpack/issues/443#issuecomment-54113862

Basically I have to write the dynamic path as a global variable inside my HTML template, then inside my client side entry point at the top define that and it works.
