### ISSUE TITLE
SSR not working on AWS Lamda 😬

### ISSUE THREAD

**Issue by bitttttten** [smooth-code/loadable-components#349]
## 🐛 Bug Report

Hey guys, first time I am using SSR with loadable-components. So perhaps it's something on my side? However, when rendering on the server it does not seem to load the component that I have code split. It will just render the app as if nothing was mounted `<div id="root></div>`. If I remove code splitting, then it renders fine.

## To Reproduce

Change my `route.tsx` file:

```js
import Index from '.'

const route = {
    path: '/',
    name: 'home',
    view: Index,
}

export default route
```

to this:

```js
import loadable from '@loadable/component'

const route = {
    path: '/',
    name: 'home',
    view: loadable(() => import('.')),
}

export default route
```

## Expected behavior

SSR will still render the pages.

## Link to repl or repo (highly encouraged)

Webpack server config: https://gist.github.com/bitttttten/e56e76fb63a90803c731b13b6a85964e

Server: https://gist.github.com/bitttttten/c3205671488c47558a5f8ced4c148d29

## Info

```bash

## System:
 - OS: macOS 10.14.4
 - CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 284.34 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.15.2 - ~/.nvm/versions/node/v10.15.2/bin/node
 - Yarn: 1.15.2 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v10.15.2/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - @loadable/babel-plugin: ^5.7.2 => 5.7.2 
 - @loadable/component: ^5.7.0 => 5.7.0 
 - @loadable/server: 5.8.0 => 5.8.0 
```

**Comment by revskill10** [comment]
If your `Index` component is in `www/index` component, i suggest to change to this
```js
import loadable from '@loadable/component'

const route = {
    path: '/',
    name: 'home',
    view: loadable(() => import('www/index')),
}

export default route
```

**Comment by bitttttten** [comment]
The component is actually in the same directory as the file. The files I previewed are called `route.tsx` and the entry is called `index.tsx`:

```bash
ls -la src/pages/Home/
total 40
drwxr-xr-x   9 bitttttten  staff   288 28 May 11:25 .
drwxr-xr-x   8 bitttttten  staff   256 16 May 11:51 ..
-rw-r--r--@  1 bitttttten  staff  6148  7 May 17:18 .DS_Store
drwxr-xr-x  40 bitttttten  staff  1280 28 May 11:24 assets
drwxr-xr-x   3 bitttttten  staff    96 23 Apr 17:31 atoms
-rw-r--r--   1 bitttttten  staff  7423 28 May 11:25 index.tsx
drwxr-xr-x   3 bitttttten  staff    96 23 Apr 17:31 molecules
-rw-r--r--   1 bitttttten  staff   258 28 May 11:24 route.tsx
drwxr-xr-x   8 bitttttten  staff   256 23 Apr 17:31 templates
````

**Comment by bitttttten** [comment]
What is odd is that is that is works locally, I am only having the problem when deploying my app to a lambda.

**Comment by theKashey** [comment]
Is there a babel plugin? It's needed to make server side rendering synchronous.

**Comment by bitttttten** [comment]
Yes, the babel plugin has been applied.

I actually found the cloudwatch log related to my lambda, the cloudfront UI was hiding it since it doesn't sort by time.

I get an error of `Cannot find module './vendors~index.js'`

```sh
Error: Cannot find module './vendors~index.js' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
at Function.Module._load (internal/modules/cjs/loader.js:508:25)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:22:18)
at Function.requireEnsure [as e] (/var/task/build/server/main.js:46:25)
at Object.requireAsync (/var/task/build/server/main.js:12458:352)
at new InnerLoadable (/var/task/node_modules/@loadable/component/dist/loadable.cjs.js:126:16)
at c (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:323)
at Sa (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:1)
at a.render (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:467) code: 'MODULE_NOT_FOUND' }
```

I think there was an error uploading the client modules to lambda. So I don't think it's a problem with loadable components..

**Comment by bitttttten** [comment]
I fixed the above issue, my files were not being uploaded correctly. So `vendors~index` was missing.

Although, sadly, I have another issue. I will make a new issue for this.

Thanks!
