### ISSUE TITLE
__LOADABLE_REQUIRED_CHUNKS__ is undefined

### ISSUE THREAD

**Issue by bitttttten** [smooth-code/loadable-components#350]
## 🐛 Bug Report

When I render my app, I do not get the script with id `__LOADBLE_REQUIRED_CHUNKS__`. Instead I get the following:

`<script id="undefined" type="application/json">[4,0]</script>`

I also get `[4,0]` on every one of my pages. I have 6 code splitted routes.

It also seems to be sending down a lot of chunks too.. and it seems to be sending down all the same JS bundles on all the pages. The pages themselves work, which makes me think the code splitting is not working. 

For example, on every page:

```html
<script async data-chunk="main" src="/static/js/runtime~main.17f4fe36.js"></script>
<script async data-chunk="main" src="/static/js/3.2d465c11.chunk.js"></script>
<script async data-chunk="main" src="/static/js/main.07502024.chunk.js"></script>
<script async data-chunk="index" src="/static/js/4.6225bc41.chunk.js"></script>
<script async data-chunk="index" src="/static/js/index.48bc2b50.chunk.js"></script>
```

## Link to repl or repo (highly encouraged)

Webpack server config: https://gist.github.com/bitttttten/e56e76fb63a90803c731b13b6a85964e

Server: https://gist.github.com/bitttttten/c3205671488c47558a5f8ced4c148d29

## Info

```bash
## System:
 - OS: macOS 10.14.4
 - CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 39.20 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.15.2 - ~/.nvm/versions/node/v10.15.2/bin/node
 - Yarn: 1.15.2 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v10.15.2/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - @loadable/babel-plugin: ^5.7.2 => 5.7.2 
 - @loadable/component: ^5.10.1 => 5.10.1 
 - @loadable/server: 5.8.0 => 5.8.0 
```

**Comment by bitttttten** [comment]
Is this not a bug @neoziro and not a question? 😅

**Comment by bitttttten** [comment]
Upgrading the server library seems to have fixed it.

```sh
--- a/package.json
+++ b/package.json
     "dependencies": {
         "@loadable/component": "^5.10.1",
-        "@loadable/server": "5.8.0",
+        "@loadable/server": "^5.9.0",
         "@soulpicks/normalizer": "^1.1.2",
         "react": "^16.8.4",
```

**Comment by neoziro** [comment]
Hello @bitttttten, I put "question" if it is just an "help", as you can see it was not a bug ;). The library is quite stable and does not have "real bug".

**Comment by bitttttten** [comment]
I didn't want to open a new issue, but I am still getting some strange behaviour.

Even though I am only rendering a route with the home chunk, I still get unused chunks in the `preload` scripts and the required chunks:

```<script id="__LOADABLE_REQUIRED_CHUNKS__" type="application/json">[0,"home",3,"festival","badger",1,"invite","places"]</script>```

And it's still including them in the initial JS too:

```html
...
<script async data-chunk="main" src="/main.a004f2fa.chunk.js"></script>
<script async data-chunk="home" src="/0.25b26057.chunk.js"></script>
<script async data-chunk="home" src="/home.5616dcb6.chunk.js"></script>
<script async data-chunk="festival" src="/3.26216eae.chunk.js"></script>
<script async data-chunk="festival" src="/festival.faa984a4.chunk.js"></script>
<script async data-chunk="badger" src="/badger.0caf7949.chunk.js"></script>
<script async data-chunk="invite" src="/1.a91ab3d2.chunk.js"></script>
<script async data-chunk="invite" src="/invite.bfc599f7.chunk.js"></script>
<script async data-chunk="places" src="/places.7321b2dd.chunk.js"></script>
</body></html>
```

I am splitting all my routes like so:

```js
    view: loadable(() =>
        import(/* webpackPreload: true, webpackChunkName: "home" */ './index'),
    ),
```

And here is the festival route:

```js
    view: loadable(() => import(/* webpackChunkName: "festival" */ './index')),
```

and invite:

```js
    view: loadable(() => import(/* webpackChunkName: "invite" */ './index')),
```

So it seems weird that they are included, even though they have not been rendered.
