### ISSUE TITLE
Preload for links and Async/Defer for scripts

### ISSUE THREAD

**Issue by TchernyavskyDaniil** [smooth-code/loadable-components#352]
Hi, can you explain me, how can I preload links and async/defer scripts your chunks? Maybe some example.
Also, I have SSR. But SSR duplicated some chunks.  
I am missed some in docs?

**Comment by neoziro** [comment]
Hello @TchernyavskyDaniil,

For preload, you can use the `LoadableComponent.preload` method or use magic comments from webpack. For now there is no other option.

Can you describe what is exactly your problem with these two methods?

**Comment by TchernyavskyDaniil** [comment]
@neoziro I mean that: https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

**Comment by neoziro** [comment]
You have to use webpack magic comments https://www.smooth-code.com/open-source/loadable-components/docs/prefetching/
