### ISSUE TITLE
Error: loadable-components state not found

### ISSUE THREAD

**Issue by kikoanis** [smooth-code/loadable-components#36]
I commented on a closed issue and I thought you may not notice it so I am repeating myself here

Not sure if this [change](https://github.com/smooth-code/loadable-components/blob/09ca8516aa42afa06f4ce9f05b5fb7a4a7a57cd4/src/loadComponents.js#L53) was necessary
```if (!state || !state.children)```

You may not have a component that needs to be lazy loaded

**Comment by antonybudianto** [comment]
Same issue, route with lazy-loaded components is working while the one without it, is not working.

**Comment by neoziro** [comment]
Yes you are right, sorry for this!

**Comment by antonybudianto** [comment]
Thanks, now it works
