### ISSUE TITLE
Customise chunk output name?

### ISSUE THREAD

**Issue by davidfloegel** [smooth-code/loadable-components#362]
Hey there,

I've been using @loadable/components for quite a while now and I've always wondered whether it's possible to customise the chunk output name?

At the moment, the chunk filename looks like this: `Users-davidfloegel-Dev-project-src-app-pages-Home.js`

So it takes the whole absolute path to the file and stringifies it.
Just wondering if there's a way to change that, can't seem to find anything in the docs.

Thanks!

**Comment by theKashey** [comment]
You can do it - in __webpack configuration__.

**Comment by davidfloegel** [comment]
Can you quickly show me how by any chance? I just couldn’t figure it out 🙄

**Comment by theKashey** [comment]
https://webpack.js.org/configuration/output#outputchunkfilename

**Comment by davidfloegel** [comment]
That doesn't work unfortunately it still contains the whole path.
The only option to get rid of that is to use a chunkhash - which might be a better option anyways?

**Comment by neoziro** [comment]
Why closed?
