### ISSUE TITLE
IE11 support for loadable

### ISSUE THREAD

**Issue by fatemab** [smooth-code/loadable-components#363]
## 💬 Questions and Help

I am doing Server side bundle splitting using Loadable. And when I look in DOM loadable attaches link tags in head with preload property to load bundles at higher priority. Loadable docs says that it supports IE11 But Preload is not supported in IE11. 
<img width="1261" alt="Screen Shot 2019-05-28 at 9 53 46 PM" src="https://user-images.githubusercontent.com/16335740/59527518-a66b5e80-8e90-11e9-9feb-c02fe7e0074d.png">

So does Loadable uses some polyfills for supporting server side splitting in IE11?

**Comment by neoziro** [comment]
Hello @fatemab, yes preload links does not work on IE11. Preload links are just here to enhanced the user experience, so Loadable Components will work even if they don't.
