### ISSUE TITLE
react-loadable compatibility component 

### ISSUE THREAD

**Issue by mohsen1** [smooth-code/loadable-components#369]
## 🚀 Feature Proposal

For easier migrating from react-loadable this library can offer a `Loadable` HoC that wraps error handling, timeout and retries automatically. This component should conform to react-loadable API so users can easily switch to this component by simply aliasing the dependencies. 

## Motivation

To migrate our large repo we had to do a large refactoring change. We also lost automatic handling of timeouts and retry functionality. We had a global `<Loading />` component that was consuming react-loadable props. 
## Pitch

This will make adopting the component framework super easy

**Comment by neoziro** [comment]
Hello, yes it is a good idea!

**Comment by mohsen1** [comment]
I am playing with this idea:

⚠️ TypeScript! 

```tsx
import React from "react";
import ReactLoadable from "react-loadable";
import loadable from "@loadable/component";
import pMinDelay from "p-min-delay";
import { timeout, TimeoutError } from "promise-timeout";

/**
 * Error boundary component
 */
class ErrorBoundary extends React.Component<
  { onError: (error: Error) => void },
  { error?: Error }
> {
  static getDerivedStateFromError(error: Error) {
    return { error };
  }

  componentDidCatch(error: Error, info: React.ErrorInfo) {
    this.props.onError(error);
  }

  render() {
    if (this.state.error) {
      return null;
    }

    return this.props.children;
  }
}

/**
 * react-loadable compatibility layer
 *
 * The options.loader prop is required, the rest is optional
 */
export default function Loadable<
  Props,
  Exports extends React.FunctionComponent<Props>
>(
  options: Partial<ReactLoadable.Options<Props, Exports>> &
    Pick<ReactLoadable.Options<Props, Exports>, "loader">
): React.ComponentType<Props> & ReactLoadable.LoadableComponent {
  /**
   * General component for handling errors and loading state
   */
  const Fallback: React.FC<ReactLoadable.LoadingComponentProps> = props => {
    if (options.loading) {
      return React.createElement(options.loading, props);
    }
    return null;
  };

  /**
   * Component we return
   */
  class InnerLoadable extends React.Component<
    Props & ReactLoadable.LoadableComponent,
    { error?: Error }
  > {
    static preload() {
      // not implemented
    }

    onError = error => {
      this.setState({ error });
    };

    retry = () => {
      this.setState({ error: undefined }, () => this.forceUpdate());
    };

    render() {
      const { error } = this.state;
      const { delay = 200, timeout } = options;
      if (error) {
        if (error instanceof TimeoutError) {
          return (
            <Fallback
              error={undefined}
              isLoading={false}
              timedOut={true}
              pastDelay={false}
              retry={this.retry}
            />
          );
        }
        return (
          <Fallback
            error={error}
            isLoading={false}
            timedOut={false}
            pastDelay={false}
            retry={this.retry}
          />
        );
      }
      return (
        <ErrorBoundary onError={this.onError}>
          {React.createElement(
            loadable(
              timeout(
                pMinDelay(options.loader, delay === false ? 0 : delay),
                timeout === false ? 0 : timeout
              ),
              {
                fallback: (
                  <Fallback
                    isLoading
                    timedOut={false}
                    pastDelay={false}
                    retry={this.retry}
                    error={undefined}
                  />
                )
              }
            )
          )}
        </ErrorBoundary>
      );
    }
  }

  return InnerLoadable;
}
```

**Comment by mohsen1** [comment]
is the Babel plugin looking for specific syntax? should the call to `loadable()` not get abstracted for it to work?

**Comment by theKashey** [comment]
Yes - it's looking for loadable imported from loadable. Then - looking for the import inside it.

**Comment by pvenegasg** [comment]
@mohsen1 Im getting the same error as @theKashey and it happens when im trying to navigate directly into a loadable route. This not happens if I navigate using the UI of my app.

**Comment by mohsen1** [comment]
ok I think this is a bigger task then. The Babel transform should also account for importing the react-loadable `Loadable` compatibility component from `@loadable/component` module. It's not too bad though, I might hack on it today.

on a somehow related note: I think putting all of related packages into a monorepo makes doing work like this easier.

**Comment by theKashey** [comment]
`loadable-components` has one implementation - it transforms imports only inside `loadable`. To solve a problem of this issue all `imports` has to be transformed.
And thus result of the transformation should be still compatible with the original `import` - that would solve the problem, letting you pass `import` from anywhere.

**Comment by mohsen1** [comment]
@theKashey can we make it detect import()s inside the parameters of a `Loadable` component as well?

```ts
import { Loadable } from '@loadable/component'

export default Loadable({ loader: () => import('./Component') });
```

Can you explain what the Babel transform actually does? I am reading the tests but can't exactly follow what's going on

**Comment by theKashey** [comment]
> can we make it detect import()s inside the parameters of a Loadable component as well?

Yes, but I dont like this approach. Honestly the current solution is very fragile - for example you could not move loading logic anywhere or wrap it somehow (like with Loadable).

> Can you explain what the Babel transform actually does?

It converts `import` into a "record" with:
- async import
- sync (and weak) require
- cache name
- and visa versa

50% of that info is used for the clientside loadable, 50% - for the serverside one.

However - sync requires might be removed, and the rest could be added to the import function as a static parameters. Then - you will not need any extra logic to use lodable-components via any compatibility wrapper.

**Comment by neoziro** [comment]
Maybe the complexity does not worth it. Also the API provided by React Loadable is not in the philosophy of React. For example, errors should be handled with Error Boundaries (as React.lazy), so it does not encourages good practices.

After thinking, I am not 100% against a react-loadable compat library but I will not maintain it. Feel free to create another project.
