### ISSUE TITLE
@loadable/babel-plugin doesn't work with dynamic imports

### ISSUE THREAD

**Issue by Confetti7** [smooth-code/loadable-components#372]
## 🐛 Bug Report

    function loadable(chunkName) {
        return require('@loadable/component').default(() => import(/* webpackChunkName: " 
       [request]" */ `../pages/${chunkName}`));
    }

## To Reproduce

    UnhandledPromiseRejectionWarning: Invariant Violation: loadable: SSR requires 
    `@loadable/babel`, please install it

**Comment by neoziro** [comment]
Hello @Confetti7, can you please submit a new issue with more detail and a repro example. I am sorry but with this one I can't help you.
