### ISSUE TITLE
Multiple chunks for same component when paths different

### ISSUE THREAD

**Issue by debugpai** [smooth-code/loadable-components#373]
## 🐛 Bug Report

When we call `loadable` and import the same component from different places using different paths then 2 different chunks are created. 

## To Reproduce

Example consider the folder structure like this
- index.js
- src/
---- LazyComponent.js
---- Simple.js

In `index.js`
```js
  const LoadableLazy = loadable(() => import('./src/LazyComponent'));
  return (
     </div>
       <LoadableLazy />
        <Simple />
    </div>
```
In `Simple.js`
```js
  const LoadableLazy = loadable(() => import('./LazyComponent'));
  return <LoadableLazy />;
```

Here 2 different chunks namely `src-LazyComponent` and `LazyComponent`

## Expected behavior
Only 1 chunk should be created

I would like to pick this issue up. I think changing [this](https://github.com/smooth-code/loadable-components/blob/master/packages/babel-plugin/src/properties/chunkName.js#L76) function to generate chunk names based on either content hash or relative path with respect to project root would solve this issue.

Would like some guidance to fix this.

**Comment by neoziro** [comment]
We can't solve it because of webpack aliases. If you experience this kind of issue I suggest you to manually add `webpackChunkName` comment in order to make it consistent.

**Comment by debugpai** [comment]
I expect this can be quite a common issue since files can be located in different places when relative paths are used. And we need to make sure chunks are not duplicated. So can you think of any other way to do this? Else shouldn't `webpackChunkName` be mandatory?

**Comment by neoziro** [comment]
In fact no, it is not a common issue, most code splitting are very simple by routes. It is an advanced use-case and yes it requires to specify the `webpackChunkName`. If you want to avoid problem you should always specify it.
