### ISSUE TITLE
Loadable Components SSR with React Router v3

### ISSUE THREAD

**Issue by fender** [smooth-code/loadable-components#374]
## 💬 Questions and Help

I've successfully set up this package with SSR and react-router v3 and it is working. However, I wanted to move away from the old `require.ensure` syntax and use `import()` so that I could dynamically load chunks the recommended way and be able to add Webpack prefetching for some of my route-based code chunks.

I'm getting an SSR error when attempting this. Please see below. Any help would be much appreciated.

Old, working code:
```es6
<Route path="/" component={App}>
  <IndexRoute
    getComponent={(nextProps, cb) =>
      require.ensure([], require =>
        cb(null, require('./HomePage/HomePage').default)
      )
    }
  />
</Route>
```

Attempt at using dynamic imports:
```es6
const HomePage = loadable(() => import('./HomePage/HomePage'));
<Route path="/" component={App}>
  <IndexRoute component={HomePage} />
</Route>
```

Error on SSR:
```
Warning: Failed prop type: Invalid prop `component` supplied to `IndexRoute`.
```

Apparently the contents of `HomePage` is:
```
{ '$$typeof': Symbol(react.forward_ref),
  render: [Function],
  preload: [Function],
  load: [Function] }
```

Side note: I had to add [babel-plugin-dynamic-import-node](url) to my `.babelrc` in order to stop my Node server complaining that `import()` wasn't supported. 🤷‍♂

**Comment by theKashey** [comment]
Probably v3 has no idea about `forwardRef`, and, probably, you dont need it.
```js
const RealHomePage = loadable(() => import('./HomePage/HomePage'));
const HomePage = (props) => <RealHomePage {...props} />;

<Route path="/" component={App}>
  <IndexRoute component={HomePage} />
</Route>
```

**Comment by fender** [comment]
@theKashey Thanks for the tip. Whilst that fixed the error and let my page render, it seems to have caused the `HomePage` component to be included within the main entry bundle that Webpack creates instead of its own chunk. It used to be its own chunk when using `require.ensure`.

**Comment by theKashey** [comment]
With default settings, webpack might not create a real chunk if it is, for example, too small. You can tune it in a various ways.
See:
- https://webpack.js.org/configuration/optimization/#optimizationsplitchunks
- https://webpack.js.org/plugins/split-chunks-plugin/

**Comment by fender** [comment]
@theKashey Yeah, I had thought that too but that doesn't seem to be the case either. I tried with the minSize all the way down to 1kb without luck. Here is my webpack config..

```es6
const path = require('path');
const webpack = require('webpack');
const config = require('config');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const LoadablePlugin = require('@loadable/webpack-plugin')
const packageJson = require('./package.json');

const appName = config.get('machineTitle');

module.exports = {
  entry: {
    main: './applications/responsive/browser.js',
  },
  output: {
    path: path.resolve(__dirname, 'static'),
    publicPath: config.get('app.assetPath'),
    filename: path.join('generated', `${appName}-responsive.js`),
    chunkFilename: path.join(
      'generated',
      'chunks',
      `${appName}-[name]-${packageJson.version}.js`
    ),
  },
  plugins: [
    new LoadablePlugin(),
    new CleanWebpackPlugin(['static/generated']),
    new MiniCssExtractPlugin({
      filename: path.join('generated', `generetic.css`),
    }),
    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
    // Use condensed list of timezones from moment-timezone-with-data-2012-2022
    new webpack.NormalModuleReplacementPlugin(
      /moment-timezone\/data\/packed\/latest\.json/,
      path.join(__dirname, '/static/scripts/timezones.json')
    ),
    new webpack.HotModuleReplacementPlugin(),
  ],
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: [/node_modules/, /NBCD_AppMeasurement/],
        use: {
          loader: 'babel-loader',
          options: {
            cacheDirectory: true,
          },
        },
      },
      {
        test: /\.css$/,
        use: [MiniCssExtractPlugin.loader, 'css-loader', 'postcss-loader'],
      },
      {
        test: /\.(woff|woff2|ttf|svg)$/,
        exclude: [/images/],
        use: [
          {
            loader: 'file-loader',
            options: {
              name: '[name].[ext]',
              outputPath: 'generated/fonts/',
            },
          },
        ],
      },
      {
        test: /\.(gif|png|jpe?g|svg)$/i,
        exclude: [/fonts/],
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 2000,
              outputPath: 'generated/images/',
            },
          },
          'image-webpack-loader',
        ],
      },
    ],
  },
  resolve: {
    alias: {
      config: path.join(__dirname, '/webpack-alias/config.js'),
      'park-logger': path.join(__dirname, '/webpack-alias/park-logger.js'),
    },
  },
  optimization: {
    splitChunks: {
      minSize: 1000,
    },
  },
};
```

**Comment by theKashey** [comment]
```
splitChunks: {
      chunks: 'all',
},
```

**Comment by fender** [comment]
@theKashey That did cause a different chunking strategy, with `node_modules` going into a `vendors` chunk but it still kept the `HomePage` within the initial entry bundle. 🤔 

I tried bumping `maxInitialRequests` and `maxAsyncRequests` to make sure it wasn't that too. No luck.

**Comment by fender** [comment]
So it turns out that having [babel-plugin-dynamic-import-node](https://github.com/smooth-code/loadable-components/issues/url) in my `.babelrc` was causing the issue. I removed it from there, and instead made sure it only ran as part of my SSR build, e.g:
```es6
require('@babel/register')({
  plugins: [
    'dynamic-import-node'
  ]
});
```

Yay 🎆

**Comment by theKashey** [comment]
JFYI: A new babel (7.4?) was released today, with a "proper" dynamic import support.

**Comment by fender** [comment]
@theKashey Amazing, thanks for the heads up.
https://babeljs.io/blog/2019/07/03/7.5.0
