### ISSUE TITLE
How to avoid load the same component twice?

### ISSUE THREAD

**Issue by sibelius** [smooth-code/loadable-components#376]
This is related to this react-router issue:

https://github.com/ReactTraining/react-router/issues/6561#issuecomment-471482350

```jsx
function Loadable({ fallback = null, loader, ...props }: Props) {
  const lazyRef = useRef(lazy(loader));
  useEffect(() => {
    lazyRef.current = lazy(loader);
  }, [loader]);

  const LazyComponent = lazyRef.current;
  return <Suspense fallback={fallback}>{LazyComponent && <LazyComponent {...props} />}</Suspense>;
})
```

When using react-router-config, component will be a loadable causing more than one loading behavior

https://github.com/ReactTraining/react-router/blob/master/packages/react-router-config/modules/renderRoutes.js#L17

my component in this config is like this:

component: loadable(() => import('Component'),

How can we use the same idea of `useRef` to avoid loading the component over and over?

**Comment by theKashey** [comment]
Honestly - I don't get the problem. 
- doing `lazy` twice seems to be wrong
- doing `lazy` even once - also wrong - it should be extracted from the function - lazy should be created ONLY ONCE!, so - you have to track `loader`

Even more - `React.lazy` is not a pure function - it will _inspect_ if Promise is already resolved, and change it's behaviour if so.

```js
const loaderMap = new WeakMap();
function getLazyComponent(loader) {
  if(loaderMap.has(loader)) {
    return loaderMap.get(loader)
  }
 
  loaderMap.set(lazy(loader));

  return getLazyComponent(loader);
}

function Loadable({ fallback = null, loader, ...props }: Props) {
  const LazyComponent = getLazyComponent(loader);
  return <Suspense fallback={fallback}><LazyComponent {...props} /></Suspense>;
}
```

**Comment by sibelius** [comment]
gonna debug more and bring more info, tks
