### ISSUE TITLE
how to hide SSRendered html while waiting for chunks to be laoded?

### ISSUE THREAD

**Issue by vesparny** [smooth-code/loadable-components#378]
Hello everybody,
I am using this library with success in a pretty big project and now I reached a point where I do not know precisely what to do :)

I basically have few components that implement some async data loading using a static method define on the outermost component called `getInitialProps`

Everything works great but I do not know precisely how should I treat server side rendered HTML while waiting for all the necessary chunks to be loaded.

**So the steps are the following:**

1. an express server loads the page by asynchronously fetching data declared within the outermost component (i implemented something similar to what Next.js does)
2. the server rendered HTML is then served and rendered by the browser
3. on `loadableReady` I hydrate the component

The problem:
In some screen the visual effect is very bad because, especially on slow connections, the html is rendered of course before the JS code is bound to it. I have some carousels and stuff that for a fraction of second look completely messed until the hydration process kicks in.

Any clue on how to deal with such scenarios?

thank you everybody

**Comment by neoziro** [comment]
Hello @vesparny,

I see the problem you are facing. In fact you can't avoid the "time to interactive" that occurs after the time to display. I suggest you to remove carousel from the page if they are not ready. You can easily render a `display: none` on the server, then displays it in a `useEffect` that will be run only server-side when the "time to interactive" is complete.

Even with Next you would have the same problem. I think @oliviertassinari has a good experience in this. Any advice?

**Comment by oliviertassinari** [comment]
On the application side, I have been using the [NoSsr](https://material-ui.com/components/no-ssr/) component to defer work to when the client is ready.
On the components side, you could write it so it works great even without JavaScript available.

**Comment by theKashey** [comment]
>  I have some carousels and stuff that for a fraction of second look completely messed until the hydration process kicks in.

Actually - why they are looking completely messed?

PS: Loadable also supports `ssr:false` prop - https://github.com/smooth-code/loadable-components/blob/9731e9c5f450f0c732c46d4dfdbbc6057a0f4d6a/website/src/pages/docs/server-side-rendering.mdx#disable-ssr-on-a-specific-loadable

**Comment by vesparny** [comment]
thank you everybody for the support
