### ISSUE TITLE
babel-preset-env 7.5 breaks loadable

### ISSUE THREAD

**Issue by DragonFire353** [smooth-code/loadable-components#379]
Been messing with babel settings trying to get this to work with the latest version but alas no luck. Here is a link to the latest release and I believe it has to particularly do with the dynamic imports section: https://babeljs.io/blog/2019/07/03/7.5.0#dynamic-import-9552-https-githubcom-babel-babel-pull-9552-and-10109-https-githubcom-babel-babel-pull-10109

When using this version, webpack does not spit out files for dynamic import (perhaps something to also do with @loadable/webpack-plugin?) and there are no mentions of the files in loadable-stats.json

Any help or guidance would be appreciated :)

**Comment by theKashey** [comment]
__DO NOT__ use any module system transpilation, including `"@babel/plugin-proposal-dynamic-import"`. Only `@babel/plugin-syntax-dynamic-import` could be used.

This is not bound it webpack or loadable - this is babel "hiding" all the expected language constructs.

**Comment by DragonFire353** [comment]
Sorry, should've shared my .babelrc file, I'm only using the syntax plugin regarding imports:

> {
	"presets": [
		[ "@babel/preset-env", {
			"modules": "commonjs",
			"useBuiltIns": "usage",
    	"corejs": 3
		} ],
		"@babel/preset-react"
	],
	"plugins": [
		"@babel/plugin-syntax-dynamic-import",
		"transform-class-properties",
		"transform-object-rest-spread",
		"@loadable/babel-plugin",
		// "@babel/plugin-transform-runtime",
	],
	"env": {
		"production": {
			"only": [
				"src"
			],
			"plugins": [
				"transform-react-remove-prop-types",
				"@babel/plugin-transform-react-constant-elements"
			]
		},
		"development": {
			"plugins": ["react-hot-loader/babel"]
		}
	}
}

**Comment by neoziro** [comment]
Hello, your issue is about Babel and webpack, nothing related to Loadable. Code splitting works in webpack if `import` are not transpiled. From Babel v7.5, Babel takes care of transpiling dynamic import for you. 

You should set `"modules": false` in the configuration for webpack.
