### ISSUE TITLE
You may need an additional loader to handle the result of these loaders.

### ISSUE THREAD

**Issue by wagnerjsilva** [smooth-code/loadable-components#380]
I've been trying to implement loadable-components, and getting the error: 

You may need an additional loader to handle the result of these loaders.

Any ideas?

**Comment by bitttttten** [comment]
It could be a few things, although it sounds like your webpack configuration is not set up correctly.

Share your webpack config or make a reproducable demo and it'll be easier to help.

**Comment by theKashey** [comment]
Or, at least, the real error

**Comment by neoziro** [comment]
Not related to Loadable Components, it looks like a pure webpack issue.
