### ISSUE TITLE
Theres a way to preload a font in ssr?

### ISSUE THREAD

**Issue by SorEduard** [smooth-code/loadable-components#381]
## 💬 Questions and Help

I want to preload material icons woff font, theres a way to do this? I'm using file-loader and css-loader and I import the font file in a scss file . The comment used by webpack to handle this only works on dynamic imports, can I use loadable.lazy or loadable.lib to do this?

```html
<link rel="preload" href="somefile.woff" as="font" />
```

Thank's for the package, save a lot of time to bundle ssr apps with code splitting!

**Comment by theKashey** [comment]
No. You don't have to use __code__ splitting for __resource__ splitting.

But your code might be incorrect, it depends on the "location" of this code. At long as you are using file loader - you have to "import" a resource to get it's "true name". Should be something like:
```
import someFile from './somefile.woff';

const HeadComponent = () => (
    <link rel="preload" href="{somefile}" as="font" />
)
```

**Comment by SorEduard** [comment]
Thank's for the reply, yesterday i've imagined how to use this feature with the extractor.getLinkTags or Elements to provide the link tag directly in my render function on server, a malformmated question i think. But thank's, I'll provide this link tag with react-helmet in ssr to better performance, have a good day!
