### ISSUE TITLE
[Feature Request] Integrating Delay and Timeout features with this library

### ISSUE THREAD

**Issue by wellyshen** [smooth-code/loadable-components#39]
Thank you for this great library. I have integrated it with my React [starter](https://github.com/wellyshen/react-cool-starter) with painless. I like your design philosophy. If you can integrate **Delay** and **Timeout** into this library I think it would be great. These features are basic necessary for async component 👍

**Comment by neoziro** [comment]
Thanks! delay and timeout are already supported. I prefer to make it optional and to keep it as small as possible. It is documented in the readme for [delay](https://github.com/smooth-code/loadable-components#delay) and for [timeout](https://github.com/smooth-code/loadable-components#timeout).

**Comment by wellyshen** [comment]
@neoziro If user can use delay and timeout without external dependency it would be great.

**Comment by neoziro** [comment]
I understand but I prefer to keep it separated, if you want to avoid additional dependencies, you can code it quickly:

```js
const delay = ms => new Promise(resolve => setTimeout(resolve), ms)

const pTimeout = async (promise, ms) =>
  Promise.race([
    promise,
    async () => {
      await delay(ms)
      throw new Error('Timeout')
    },
  ])

const pDelay = async (promise, ms) => {
  await wait(ms)
  return promise
}

const DelayedComponent = loadable(pDelay(() => import('./MyComponent'), 200))
const TimeoutComponent = loadable(pTimeout(() => import('./MyComponent'), 3000))
```

**Comment by wellyshen** [comment]
@neoziro Thank you for your response. Should we need to handle the case of delay + timeout?

**Comment by neoziro** [comment]
```js
const TimeoutComponent = loadable(pDelay(pTimeout(() => import('./MyComponent'), 3000), 200))
```

😉

If you like functional programming and composition you can slightly change it.

```js
const delay = ms => new Promise(resolve => setTimeout(resolve), ms)

const pTimeout = ms => async promise =>
  Promise.race([
    promise,
    async () => {
      await delay(ms)
      throw new Error('Timeout')
    },
  ])

const pDelay = ms => async promise => {
  await wait(ms)
  return promise
}

const DelayedComponent = loadable(compose(
  pDelay(200),
  pTimeout(200),
)(() => import('./MyComponent')))
```

**Comment by wellyshen** [comment]
@neoziro Thanks. It really helpful ;)

**Comment by wellyshen** [comment]
@neoziro If you can add the "timeout + delay" as a part of your README. It would be great 👍
