### ISSUE TITLE
TS + create-react-app + react-router: error "You may need an appropriate loader to handle this file type."

### ISSUE THREAD

**Issue by MikelArnaiz** [smooth-code/loadable-components#394]
## 🐛 Bug Report

I'm unable to make `loadable-components` work in a `typescript` + `create-react-app` + `react-router` project. I get the error `You may need an appropriate loader to handle this file type`

## Code

Component:

```tsx
import React from 'react'
const UsersOverview = () => <div>Lorem ipsum dolor sit amet.</div>
export default UsersOverview
```

Loading route:

```tsx
import loadable from '@loadable/component'
import { Route } from 'react-router'

const AsyncUsers = loadable(() => import('../../components/Users/UsersOverview'), {
  fallback: <div>Loading...</div>
})

// ...

<Route path={PAGES.USERS} component={() =<AsyncUsers />} />
```

## Error

```
./src/modules/App/App.container.tsx 28:9
Module parse failed: Unexpected token (28:9)
You may need an appropriate loader to handle this file type.
| var AsyncUsers = loadable(function () {
>   return import('../../components/Users/UsersOverview');
| }, {
|   fallback: React.createElement("div", {
```

I have the feeling that this is a `webpack` or `babel` related issue. But as this is a [CRA](https://github.com/facebook/create-react-app) based project I can't modify the configs (unless I eject which I don't consider).

Is there any workaround to make it work?

## Dependencies

```
"@loadable/component": "^5.10.2",
"react": "16.8.4",
"react-router": "4.2.0",
"react-scripts": "3.0.1",
```

**Comment by neoziro** [comment]
Hello @MikelArnaiz, you are missing the https://babeljs.io/docs/en/babel-plugin-syntax-dynamic-import. It is not related to Loadable Components, please ask help on CRA / TypeScript.
