### ISSUE TITLE
IE11: Object doesn't support property or method 'includes'

### ISSUE THREAD

**Issue by c1aphas** [smooth-code/loadable-components#397]
## 🐛 Bug Report

Hi!
According to docs browser support is:
> v5.x (React v16.3+): IE11, IE 9+ (with Map + Set polyfills), all evergreen browsers

But my project fails on this line https://github.com/smooth-code/loadable-components/blob/d7c3f58059a798dc1d38f95da79f374e998977ad/packages/component/src/loadableReady.js#L44

`includes` doesn't supported in IE up to ie11

Am i doing something wrong? My project uses `razzle` boilerplate with `loadable-components` example: https://github.com/smooth-code/loadable-components/tree/master/examples/razzle

**Comment by neoziro** [comment]
Hmm yes you are right, for now you can just include the polyfill. Could you submit a PR to fix it?

**Comment by neoziro** [comment]
By fixing it I mean using `indexOf` instead of `includes`.
