### ISSUE TITLE
Example with ruzzle doesn't work

### ISSUE THREAD

**Issue by dimensi** [smooth-code/loadable-components#398]
## 🐛 Bug Report

I tried to do the same thing with loadable integration, but I get 2 problems.
1. Getting the wrong paths to the files
2. Somehow the code tries to get to the client side for the server
```
Uncaught Error: Cannot find module 'fs'
    at webpackMissingModule (ChunkExtractor.js:8)
    at Object../node_modules/@loadable/server/lib/ChunkExtractor.js (ChunkExtractor.js:8)
    at __webpack_require__ (bootstrap:790)
```

## To Reproduce

Try example yourself

## Link to repl or repo (highly encouraged)
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/6949b8e9-e5f8-453b-bcc4-6af6f7328314)

## System

```bash
## System:
 - OS: macOS 10.14.5
 - CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
 - Memory: 724.96 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
 - Yarn: 1.15.2 - /usr/local/bin/yarn
 - npm: 6.10.2 - ~/.nvm/versions/node/v11.15.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - @loadable/babel-plugin: ^5.10.0 => 5.10.0 
 - @loadable/component: ^5.10.2 => 5.10.2 
 - @loadable/server: ^5.10.2 => 5.10.2 
 - @loadable/webpack-plugin: ^5.7.1 => 5.7.1 
```

**Comment by dimensi** [comment]
Found answer. Need add to client webpack config this line
```
config.node = { fs: 'empty' }
```

**Comment by dimensi** [comment]
@neoziro example anyway not working. Why you close issue?

**Comment by neoziro** [comment]
Sorry I though your bug was solved.

**Comment by neoziro** [comment]
Could you submit a PR?

**Comment by dimensi** [comment]
I'm trying to use loadable components from rr5, but this is the first time that components are not loaded. If you fix the razze configuration, your example starts working, but you have @reach/router, not react-router. Do I need to create a new issue for my react-router 5 problem? 
Here is my repository where I try to use loadable components.
https://github.com/dimensi/razzle-ssr

**Comment by neoziro** [comment]
rr5 ?

**Comment by neoziro** [comment]
A lot of issue are relative to Razzle, you should probably look for existing issue or submit a new one on Razzle.

**Comment by dimensi** [comment]
ok, close it
