### ISSUE TITLE
without babel - how to use fallback and other options

### ISSUE THREAD

**Issue by ScriptedAlchemy** [smooth-code/loadable-components#401]
Im stuck on babel 6, so ive been manually implementing loadable. However im not sure how to utilize the options that you usually use when babel plugin works. 

How can i add a fallback: <LoadingComponent> when using the following implementation:

```
const HomeContainer = loadable({
  chunkName() {
    return 'Home';
  },
  isReady(props) {
    if (typeof __webpack_modules__ !== 'undefined') {
      return !!__webpack_modules__[this.resolve(props)];
    }
    return false;
  },
  requireAsync: () => import(/* webpackChunkName: "Home" */'./containers/home/home-container'),
  requireSync(props) {
    const id = this.resolve(props);
    if (typeof __webpack_require__ !== 'undefined') {
      return __webpack_require__(id);
    }
    return eval('module.require')(id);
  },
  resolve() {
    if (require.resolveWeak) {
      return require.resolveWeak('./containers/home/home-container');
    }
    return require('path').resolve(__dirname, './containers/home/home-container');
  },
});
```

We then implement the HomeContainer component:
```
export default [
  {
    ...paths.home,
    component: HomeContainer,
    loadData: (routeParams, queryString, dispatch) => Promise.all([
      HomeContainer.load().then(({ HomeContainer: HomeContainerSync }) => HomeContainerSync.loadData(routeParams, queryString, dispatch)),
      Footer.loadData(dispatch, queryString),
    ]),
  },]
```

To clarify, how would i add the fallback option listed here to my code:
![image](https://user-images.githubusercontent.com/25274700/62499445-86249580-b797-11e9-8684-c8186db9e986.png)

**Comment by theKashey** [comment]
loadable __lib__ is not loadable component. Failback here is a __mock__ you will display while "lib" is loading. In some cases you even don't need it.

**Comment by ScriptedAlchemy** [comment]
Ahhh, well how do I display a loading react component with my current config ?

Like in React-universal I can specify a loading component that’s shown till my code-split one is downloaded and rendered

**Comment by theKashey** [comment]
Are you considering `Suspense`?

**Comment by ScriptedAlchemy** [comment]
If that’s the solution, sure. I just wanted to see if there was a non-suspense solution that was baked into this lib. I’m used to universal, so still learning. Is suspense the best or only solution to display a loader message while the chunk gets loaded?

**Comment by ScriptedAlchemy** [comment]
@theKashey @neoziro Howd i use the following?

```
const OtherComponent = loadable(() => import('./OtherComponent'), {
  fallback: <div>Loading...</div>,
})
function MyComponent() {
  return (
    <div>
      <OtherComponent />
    </div>
  )
}```

But without the babel plugin, like mentioned in the issue above?

**Comment by neoziro** [comment]
Hello @ScriptedAlchemy, I am sorry I don't understand the question. Can you give more context please?

**Comment by minhtranite** [comment]
@ScriptedAlchemy Maybe you need this:

```
import React from 'react';
import loadable from '@loadable/component';
import { Loader } from 'xxx';

const withLoadable = getComponent =>
  loadable(getComponent, {
    fallback: <Loader isLoading fullScreen label="hang on while we get this page ready!" />,
  });

export default withLoadable;

```

**Comment by neoziro** [comment]
I am sorry I have no idea, using it without the Babel plugin is very tricky. You should probably try to upgrade Babel or create something from scratch.
