### ISSUE TITLE
Inline manifest in server response

### ISSUE THREAD

**Issue by hinok** [smooth-code/loadable-components#403]
## 💬 Questions and Help

Hey,
Is it "safe" to inline webpack manifest (runtime) into response returned from server?

At the moment calling `extractor.getScriptTags()` returns string like below (in my project):

```
<script id="__LOADABLE_REQUIRED_CHUNKS__" type="application/json">["common","home"]</script>
<script async data-chunk="app" src="/manifest.ee1e8b7204e502630df9.js"></script>
<script async data-chunk="app" src="/vendors.b9a9b237302050074db1.chunk.js"></script>
<script async data-chunk="app" src="/app.94794ad735d401cb95f1.chunk.js"></script>
<script async data-chunk="home" src="/common.8c2c2c2a247daa069ef3.chunk.js"></script>
<script async data-chunk="home" src="/home.9415d906e66e963f526f.chunk.js"></script>
```

I'd like to get rid of extra call to `manifest.[hash].js` and inline it in HTML returned from server.
I did some string/array manipulation and removed `<script src="/manifest...`.

Everything seems working correctly but before I proceed with such solution, I need to be sure that such manipulation won't break `loadable-components`.

**Comment by neoziro** [comment]
Hello @hinok, in Loadable Components it would not break anything, but webpack will probably load it if it is not already loaded. I suggest you to inline it and to not include it in dynamic import.

**Comment by hinok** [comment]
@neoziro Thanks for quick response. I don't see any extra request for manifest after inlining.

**Comment by hinok** [comment]
It seems that it's working correctly after inlining. Thanks!
