### ISSUE TITLE
SSR with remote stats and assets

### ISSUE THREAD

**Issue by flosch-hb** [smooth-code/loadable-components#405]
## 💬 Questions and Help

Hello, I have a question regarding SSR architecture.

I work with a serverless stack backed by microservices (mainly with Amaon Web Services), and I was wondering if this package could be used in such a pattern?

Mainly, I was thinking of a few things:
- static webpack assets (chunks) hosted in AWS S3
- CloudFront distribution backed by this origin for the static files
- Lambda@Edge functions associated to this distribution, doing SSR

Following this pattern, the assets would be hosted in S3 and therefore cannot be accessed inline doing something like `fs.readFile()`, which is what ChunkExtractor seems to do if I am correct?

I have found [this issue about filesystem override](https://github.com/smooth-code/loadable-components/issues/315), but not sure how to use it to be honest?

Also, since files in S3 are supposed to be publicly accessible through CloudFront, I would prefer not to host the webpack stats in there.

Is it possible to host stats and actual assets separately?

**Comment by flosch-hb** [comment]
I actually managed to get it working thanks to the `publicPath` option that I missed from the doc initially!

Instead of overriding the fileSystem, setting that setting with the CloudFront URL (well actually a custom domain) will makes the assets being loaded from CloudFront (under the hood, from S3).

I just had to:
- make sure that both the stats files and the compiled node (server-side) chunks are also accessible locally from the function (I used copy-webpack-plugin to copy them into the execution folder)

Compiled lambda structure: (I use serverless-webpack)

```
/package.json
/yarn.lock
/server-side-rendering.js // the lambda function
/stats // webpack stats files
  /loadable-stats.node.json
  /loadable-stats.web.json
/app // server-side chunks
  /chunk1.js
  /chunk2.js
  /chunk3.js
```

And this is a simplified example of implementation:

```
const STATS_FOLDER = path.resolve(process.cwd(), 'stats');

const nodeExtractor = new ChunkExtractor({
  outputPath: path.resolve(process.cwd(), 'app'),
  statsFile: path.join(STATS_FOLDER, 'loadable-stats.node.json')
}};
const { default: App } = nodeExtractor.requireEntrypoint();

const webExtractor = new ChunkExtractor({
  publicPath: 'https://domain.tld', // the CloudFront distribution domain (either xxx.cloudfront.net or a custom domain if you associate it)
  statsFile: path.join(STATS_FOLDER, 'loadable-stats.web.json')
}};

// The rest is the same as shown in:
// https://github.com/smooth-code/loadable-components/blob/v5.10.2/examples/server-side-rendering/src/server/main.js#L44
```

**Comment by neoziro** [comment]
Good if you make it work! If you have time and if you want to contribute, feel free to write a guide on the website! @flosch-hb

**Comment by flosch-hb** [comment]
Hey @neoziro, sure, I have one way to do it, probably not the absolute best architectural way to do so, but I can still document it as a starter :)
Is it here? https://github.com/smooth-code/loadable-components/tree/master/website/src/pages/docs

**Comment by neoziro** [comment]
Yes it is ☺️
