### ISSUE TITLE
Cant run the server side code example.

### ISSUE THREAD

**Issue by andrevenancio** [smooth-code/loadable-components#406]
I'm having trouble understanding the logic of the `examples/server-side-rendering` since the example isn't working.

I've downloaded the loadable-components source code and jump into the server-side-rendering example and run `npm install` I then run `npm start` which does not compile properly.

After some trial and error, I managed to get it working, but I still don't understand some things.

1. Why do we compile the source to the `lib` folder I don't see any reference to the `lib/` folder.
2. On the SSR none of the Async components are being included on the SSR.
3. I don't understand why we're compiling `web` and `node`.
4. After all is compiled how do we create a serve function? `babel-node src/server/index.js` ?
5. Running `npm run dev` run in a loop
6. Running `npm start && npm run serve` seems to work, but SSR doesn't render components wrapped with `loadable`.

Below is an url for my version of test project:

https://github.com/andrevenancio/test-loadable-components

**Comment by neoziro** [comment]
Hello @andrevenancio, to start the server-side rendering example you have to:

1. Add `@loadable/component`, `@loadable/server`, etc..
2. Run `npm run build`
3. Run `npm run dev` or `npm start`

It should work properly.
