### ISSUE TITLE
Razzle example local server start fails

### ISSUE THREAD

**Issue by vbutani** [smooth-code/loadable-components#407]
## 🐛 Bug Report

Razzle example local server fails to start
## To Reproduce

npm install
npm start
## Expected behavior

Local server should start normally without error.

## Link to repl or repo (highly encouraged)

https://github.com/smooth-code/loadable-components/tree/master/examples/razzle
Issues without a reproduction link are likely to stall.

Paste the results here:

```

## System:
 - OS: macOS 10.14.6
 - CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
 - Memory: 7.07 GB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.10.0 - /usr/local/bin/node
 - npm: 5.7.1 - /usr/local/bin/npm
## npmPackages:
 - @loadable/babel-plugin: ^5.10.0 => 5.10.0 
 - @loadable/webpack-plugin: ^5.7.1 => 5.7.1 

npm start error as follows:-

/Users/vb/workspace/loadable-components-master/examples/razzle/build/server.js:1775
  var extractor = new !(function webpackMissingModule() { var e = new Error("Cannot find module '@loadable/server'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())({
                      ^

SyntaxError: Unexpected token !
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by vbutani** [comment]
I got the issue, I think ```@loadable/server``` and ```@loadable/component``` are not included as dependencies in ```package.json``` file. I am able to start the server successfully, by installing them separately. Thanks.

**Comment by neoziro** [comment]
Yeah they are not included by default, we should include them. Could someone submit a PR to add missing `@loadable/xxx` packages in all examples?
