### ISSUE TITLE
Does @loadable works with React Hooks? 

### ISSUE THREAD

**Issue by marcialca** [smooth-code/loadable-components#414]
It's just that simple question really, does @loadable/components works with React Hooks? Is there any example available in the repo that uses hooks?

Thanks!

**Comment by theKashey** [comment]
Q: Could you use hooks inside loadable components? 
A: Sure you can

Q: Is there any hook API to load "something" using hooks?
A: No there isn't any.

Q: What is your use case @marcialca?
A: ...

**Comment by marcialca** [comment]
Thanks for the answer @theKashey! That's great news, is there any example on the code base for hooks? 

My use case is basically that I need to wrap @loadable/components inside an Express-like app (it uses [Kraken.js ](http://krakenjs.com/)) and I keep getting errors when trying to use hooks, it's the same type of error of this issue: https://github.com/smooth-code/loadable-components/issues/327
but I already verified for async/defer stuff, double script tags, etc and I'm not using any other library besides react and loadable, so I wanted to know if there was something that I was missing

**Comment by theKashey** [comment]
This problem could be caused by only two reasons:
- two bundles with two reacts
- two reacts in one bundle

Which is one problem, just made more severe by code splitting. Try to use Webpack alias to pin single version of React.

**Comment by marcialca** [comment]
Thanks for the answer, I think in our case, We might be having two reacts in two bundles, since the "renderer" code for React on the Kraken (server) side is being bundled and then loaded by React itself, and could be creating the first issue you mention. Anyway is good to know that there's no limitation from loadable and that the causes are limited.

I'll keep digging on our codebase. For the mean time, I think we are good to close the issue.

Thanks again for the answers.
