### ISSUE TITLE
componentWillMount is deprecated in react 16.9

### ISSUE THREAD

**Issue by macrozone** [smooth-code/loadable-components#415]
## 🐛 Bug Report

componentWillMount will be removed in the next react version. We should either switch to UNSAFE_componentWillMount or better: try to use another lifecycle method (or hooks)

## To Reproduce

install react 16.9 and use this library

**Comment by neoziro** [comment]
We don't use `componentWillMount` in any of file in this project.

**Comment by macrozone** [comment]
ok, so probably false alarm, React told me that loadable component uses componentWillMount, so maybe it was a component that was lazy loaded that used componentWillMount.
