### ISSUE TITLE
does not support 'webpack-hot-middleware' ?

### ISSUE THREAD

**Issue by DylanJu** [smooth-code/loadable-components#418]
Hi. I'm trying to make server-side-rendring with @loadable compoenent.
Your example server-side-rendering works well except that with 'webpack-hot-middleware'.

I added 'webpack-hot-middleware' to webpack entry following an official guide: https://github.com/webpack-contrib/webpack-hot-middleware
(webpack config part 2)

webpack compile was success but 'webapck-dev-server' can't load 'webpack-hot-middleware'. An error is "Error: Cannot find module 'webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000"

is there any solution?
Do I have to use webpack-dev-server instead of webpack-dev-middleware & webpack-hot-middleware for hot-loading?

If you want to see, visit my example repo.
https://github.com/DylanJu/loadable-components/tree/hot/examples/server-side-rendering

I forked your repo and added just 'webpack-hot-middleware' config

````
yarn build:webapck && yarn dev
````

thanks

**Comment by neoziro** [comment]
Hello @DylanJu, I think you are missing something in your `webpack-hot-middleware` setup. Anyway it is not relative to loadable-components.
