### ISSUE TITLE
Custom public path on the fly for assets

### ISSUE THREAD

**Issue by srigar** [smooth-code/loadable-components#427]
Hey, I'm using loadable components in my application. I want to change the asset path in server side at the runtime. So used the below code snippet to achieve that. But it is not working, still it is referring old asset path. Added the below lines in serverRenderer.jsx(the final html construction file) or do i need to add this in any specific place?. Looking for your help.

> const statsFile = __non_webpack_require__('./loadable-stats.json'); 
> new ChunkExtractor({
>       stats: statsFile,
>       publicPath: '/cdn/assets/',
>       entrypoints: 'client'
> });

**Comment by neoziro** [comment]
Hello @srigar, it should work: https://github.com/smooth-code/loadable-components/blob/master/packages/server/src/ChunkExtractor.js#L169

Did you find the solution?

**Comment by srigar** [comment]
No it is not working. Did some work around for that.

**Comment by lkaratun** [comment]
@srigar Do you mind sharing your solution to others?
