### ISSUE TITLE
Loadable + SSR + NON Ejected CRA

### ISSUE THREAD

**Issue by vinceprofeta** [smooth-code/loadable-components#428]
Are there any guides to using loadable with server side rendering in a non ejected create-react-app project? 

It seems fine, except for @loadable/webpack-plugin. Any direction would be great

**Comment by neoziro** [comment]
Hello @vinceprofeta, SSR is not possible without an ejected CRA.

**Comment by camposcristianeze** [comment]
Hey guys, I'm looking to do the same so any direction would be much appreaciated!

**Comment by theKashey** [comment]
CRA has two limitations: no babel plugins and no webpack plugins.
- the first one is avoidable via `babel macros`
- however, there is no solution for the second, except eject, craco or rewired.

As long as `loadable-components` rely on the integration with webpack to provide the best experience - there is no way they would work. CRA tries to as a black box. Well, that's the idea.

For now, the only solution for CRA is [imported-component](https://github.com/theKashey/react-imported-component), but still - you will lose the ability to preload scripts and it would work, but not as good as with a little rewired CRA.

Personally I see no harm in changing the default configuration, as long as migration from one CRA version to another always was a pain, so if it would be just a bit harder - 🤷‍♂️who cares.

**Comment by zsh77** [comment]
@theKashey thank you for your answer .i'm gonna try it right away
