### ISSUE TITLE
[ASK] Will this library support hot reloading?

### ISSUE THREAD

**Issue by wellyshen** [smooth-code/loadable-components#43]
I use this library with react-hot-loader beta.21. But it seems not support hot reloading yet? Will this library support it?

**Comment by neoziro** [comment]
In my last tests it was supported out of the box. But if not, follow this guide https://github.com/gaearon/react-hot-loader/tree/next#code-splitting.

**Comment by wellyshen** [comment]
@neoziro Thanks a lot. It works !
