### ISSUE TITLE
How to handle `cannot find module`

### ISSUE THREAD

**Issue by haxxxton** [smooth-code/loadable-components#432]
I am using string literals to dynamically import components based off text entered into my CMS. In the case that the user enters text for a component that does not exist, id love to be able to fallback.

In the below code i have tried using an ErrorBoundary, fallback of `null`, _and_ a try/catch block, but i still get the 'Error: Cannot find module' error.

```
const ActualIcon = ({ icon }) => {
	try {
		const Icon = loadable(() => import(`../Icons/elements/${icon}`), {
			fallback: null,
		});
		return <Icon />;
	} catch (e) {
		return null;
	}
};

const FeatureIcon = ({ icon }) => (
	<ErrorBoundary>
		<ActualIcon icon={icon} />
	</ErrorBoundary>
);
```

Is there some other way i can prevent this error when trying to use loadable on a component that doesnt exist?

**Comment by foglerek** [comment]
Have you tried a `.catch` on the `import()` call?

**Comment by haxxxton** [comment]
@foglerek what should `catch` return or do? i get the following error when i either `return null` or just `window.console.log(error)`

```
Uncaught TypeError: Cannot read property '__esModule' of undefined
    at resolveComponent (loadable.esm.js:325)
    at loadable.esm.js:215
```

**Comment by foglerek** [comment]
You could do something like this, maybe even make a helper out of it if it's a pattern you use often?
```
import(`../${dynamicValue}`)
  .catch(err => console.error(err))
  .then(() => require('../fallbackComponent'));
```

**Comment by haxxxton** [comment]
@foglerek thanks for your help. The solution appears to be:
```
import(`../${dynamicValue}`)
  .catch(=> import('../fallbackComponent'));
```
otherwise the fallbackComponent is always rendered even if there is a successful import :)

**Comment by iamdcj** [comment]
Hey @haxxxton,

I'm having the same issue, did you manage to find a solid solution? If so, could you please share.

Thanks,
David
