### ISSUE TITLE
Is that available to compress the and reference gzip file in server side rendering?

### ISSUE THREAD

**Issue by pinebrook** [smooth-code/loadable-components#437]
Hello, 
I've read the Docs of this package, didn't find anything about compression. I tried using compression-webpack-plugin to compress all the chunk files to gzip files, but in server side rendering, the scriptTags cannot get these gzip files, so just wanna ask is this package available to compress? Thank you.

**Comment by neoziro** [comment]
Hello @pinebrook, compression has nothing to do with loadable-components. It is webserver business. I mean if you upload a `asset.js.gz`, your webserver should automatically serve it as `asset.js` with `gzip` compression. Example: https://medium.com/@selvaganesh93/how-to-serve-webpack-gzipped-file-in-production-using-nginx-692eadbb9f1c

**Comment by pinebrook** [comment]
It helps! Thank you.
