### ISSUE TITLE
[Error] Server and Client modules are not sync

### ISSUE THREAD

**Issue by wellyshen** [smooth-code/loadable-components#44]
Hi, I setup this library with SSR and currently I'm doing code-splitting for redux reducer based on this [solution](https://stackoverflow.com/questions/32968016/how-to-dynamically-load-reducers-for-code-splitting-in-a-redux-application). But I encounter an error as following:

<img width="1280" alt="2018-02-11 2 47 56" src="https://user-images.githubusercontent.com/21308003/36065523-1727773e-0ed7-11e8-96b6-047d4d07b3e1.png">

BTW, if I remove the `loadComponents().then( ... )` from my `client.js` the error gone but another error occurs as following:
 
<img width="1280" alt="2018-02-11 2 59 16" src="https://user-images.githubusercontent.com/21308003/36065563-a3b005c2-0ed7-11e8-993d-fc489a73555f.png">

Any suggestion for it?

**Comment by neoziro** [comment]
You can compare client modules and server modules and see what's going on.

**Comment by wellyshen** [comment]
@neoziro 

If I export my routes config as a function, it not work:
```javascript
import loadable from 'loadable-components';

import type { Dispatch } from './types';
import { fetchUsersIfNeeded } from './actions/users';
import { fetchUserIfNeeded } from './actions/user';
import { Loading, Error } from './components/index';

export default () => [
  {
    path: '/',
    exact: true,
    component: loadable(() => import('./containers/Home'), {
      LoadingComponent: Loading,
      ErrorComponent: Error
    }), // Add your route here
    loadData: (dispatch: Dispatch) =>
      Promise.all([
        dispatch(fetchUsersIfNeeded()) // Register your server-side call action(s) here
      ])
  },
  {
    path: '/UserInfo/:id',
    component: loadable(() => import('./containers/UserInfo'), {
      LoadingComponent: Loading,
      ErrorComponent: Error
    }),
    loadData: (dispatch: Dispatch, params: Object) =>
      Promise.all([dispatch(fetchUserIfNeeded(params.id))])
  },
  {
    component: loadable(() => import('./containers/NotFound'), {
      LoadingComponent: Loading,
      ErrorComponent: Error
    })
  }
];
```

If I export my routes config as an array, it works:
```javascript
import loadable from 'loadable-components';

import type { Dispatch } from './types';
import { fetchUsersIfNeeded } from './actions/users';
import { fetchUserIfNeeded } from './actions/user';
import { Loading, Error } from './components/index';

export default [
  {
    path: '/',
    exact: true,
    component: loadable(() => import('./containers/Home'), {
      LoadingComponent: Loading,
      ErrorComponent: Error
    }), // Add your route here
    loadData: (dispatch: Dispatch) =>
      Promise.all([
        dispatch(fetchUsersIfNeeded()) // Register your server-side call action(s) here
      ])
  },
  {
    path: '/UserInfo/:id',
    component: loadable(() => import('./containers/UserInfo'), {
      LoadingComponent: Loading,
      ErrorComponent: Error
    }),
    loadData: (dispatch: Dispatch, params: Object) =>
      Promise.all([dispatch(fetchUserIfNeeded(params.id))])
  },
  {
    component: loadable(() => import('./containers/NotFound'), {
      LoadingComponent: Loading,
      ErrorComponent: Error
    })
  }
];
```

Very wired!

**Comment by wellyshen** [comment]
@neoziro 
The problem is the loadable-component can't be a return function:
```javascript
// It'll not work
const HomePage = () =>
  lodable(() => import('./containers/Home'), {
    LoadingComponent: Loading,
    ErrorComponent: Error
  });

// It works
const HomePage =
  lodable(() => import('./containers/Home'), {
    LoadingComponent: Loading,
    ErrorComponent: Error
  });
```

**Comment by neoziro** [comment]
Hmm it could be an issue in the [tree traverser](https://github.com/smooth-code/loadable-components/blob/master/src/server/index.js) can you give a reproducible example on CodeSandbox?

**Comment by wellyshen** [comment]
@neoziro 

Sure, you can reproduce it through [here](https://github.com/wellyshen/react-cool-starter/blob/error-reproduce-loadable-components/src/routes.js).

And here's the error that I encounter:
<img width="1280" alt="2018-02-11 4 38 38" src="https://user-images.githubusercontent.com/21308003/36071564-c58fa0b2-0f4a-11e8-8cb4-9910a2f3604f.png">

**Comment by max-mykhailenko** [comment]
Can I hope that this problem will be fixed in a nearest few days?

**Comment by wellyshen** [comment]
@max-mykhailenko Did you also encounter this problem?

**Comment by max-mykhailenko** [comment]
Not yet, I always look at issues before start using any lib and my case is more complex: I want to write something like this

```js
const What = loadable(async () => {
  const [{ default: Books }, { default: books }] = await Promise.all([
    import('./Books'),
    ...getCalledActionsAndGetPromisesArrayBack(store),
  ])

  return props => <Books {...props} books={books} />
})
```

**Comment by max-mykhailenko** [comment]
@wellyshen I recommend to change structure and export routes without function. After big workaround with many `loadable` components and `react-hot-loader` I can say that it's only one possible way to do that.

**Comment by wellyshen** [comment]
@neoziro Any update for this issue?

**Comment by neoziro** [comment]
Not on my side.

**Comment by wellyshen** [comment]
@neoziro Did you mean the issue isn't caused by this library?

**Comment by neoziro** [comment]
No I mean I haven’t time to investigate it yet. I think that the tree traversal is not working for your specific case. Do you have a complete example so I could try to see exactly the source of the problem?

**Comment by wellyshen** [comment]
@neoziro Sure, you can see my error reproduce [here](https://github.com/wellyshen/react-cool-starter/blob/error-reproduce-loadable-components/src/routes.js).

**Comment by neoziro** [comment]
Your static route configuration looks a bit tricky. I will try to run your project probably this week end, I keep you up to date!

**Comment by wellyshen** [comment]
Yea I use the [route config](https://reacttraining.com/react-router/web/example/route-config) of react-router for SSR

**Comment by JulienPradet** [comment]
I thought I had the same issue so I looked at it a bit.

In order to build the client modules object (the ones in the warning), the library needs to run all the `loadable` calls.

Therefore when you call `loadComponents` you must have created all your `loadable` Components beforehand. In your specific case @wellyshen you defer them later when you render your AppContainer. That's why it fails to register the loadable components since no render has been done yet. And that's also why the version without a function works fine.

So in my opinion, that's not a bug, it's by design :)

(For my issue, it was because I had several instances of `loadable-components` bundled in my code.)

**Comment by neoziro** [comment]
Seems fixed https://github.com/wellyshen/react-cool-starter/blob/error-reproduce-loadable-components/src/routes.js#L16

**Comment by neoziro** [comment]
@JulienPradet you are right, the issue was that loadable components were created lazily.

**Comment by wellyshen** [comment]
@neoziro My use case is to wrap `loadable-components` in a function as [this](https://github.com/wellyshen/react-cool-starter/blob/error-reproduce-loadable-components/src/routes.js#L7) for implementing async reducers.

**Comment by wellyshen** [comment]
Alright, I got it. Thanks 👍

**Comment by neoziro** [comment]
I think I could make it possible by adding a `require.resolveWeak('./Bar')` like React Loadable does. But right now I do not want to couple it with Webpack.

I will give you a solution, you can do it if you want:

The `loadableState` you get has a `tree` properties, the solution for you is to walk the tree and try to get the full path of the module.

If you got the full path of the module, you can easily load it client side.

The actual problem is that you only get the relative path of the module, so you can't tell to Webpack "Load my module". Do you see the problem?

**Comment by wellyshen** [comment]
Okay, I will survey it when I have time and ask you questions about it man 👍
