### ISSUE TITLE
<script crossOrigin="anonymous" ... /> possible ??

### ISSUE THREAD

**Issue by tomtom94** [smooth-code/loadable-components#441]
I just wanna have a script like this in my React Server Side Rendering html page 

`<script crossorigin="anonymous" ...` Are we able to do so with the ChunkExtractor `const scriptTags = extractor.getScriptTags();` ?

How can I do that ? I already tried with the Webpack options in Output
`crossOriginLoading: 'anonymous'`

But it doesn't work because this is `loadable-component` which has the hand to insert bundles in the html when you are in SSR.

Thanks.

**Comment by cw-VishNu** [comment]
Hi @tomtom94  , were you able to figure this out  ?

**Comment by rtymchyk** [comment]
@cw-VishNu You can specify attributes you'd like, e.g. `const js = webExtractor.getScriptTags({ crossOrigin: '' })`
