### ISSUE TITLE
Load page assets on server as required

### ISSUE THREAD

**Issue by markrzen** [smooth-code/loadable-components#443]
I have a project structured around page components. When webpack builds the assets, I end up with a vendor.js, main.js and then a number of page assets, e.g. home.js, about-us.js, etc.

Each of these page assets are loadable imports with a chunkName.

After following the guide, I have found that the page assets are not found by `getScriptTags`, and thus require the main.js to load before they are requested.

Is there a supported way to force this behavior?

I was attempting to get the components chunkName from react-router, then pass that into the `entrypoints` of `ChunkExtractor`, but I haven't been lucky in finding an easy way to get the page chunkName.

Thanks in advance.

**Comment by theKashey** [comment]
Could you clarify what you are doing because you are not expected to do almost anything - "used" chunks should be reported automatically without any "help" from your side, except `extractor.collectChunks`

And `entrypoint` should be always "main" in your case, and you are expected to load it even if you are loading a page chunk -> you have to load `main` AND the `page` chunk.

**Comment by markrzen** [comment]
@theKashey Thanks for the response and your second statement is what I expected.

What I am doing is a fairly wide open question, so excuse me if I ramble a bit. I have three parts to my application, server, application (shared) and client.

- Client and application are packaged by webpack, outputting the loadable-stats.json file.
- Server and application are transpiled by babel, using the loadable-stats.json from the client build output.

Below is rough pseudo code for the server side rendering process:
```js
// render.js
const statsFile = path.join(__dirname, '..', 'loadable-stats.json');

function render() {

     const app = (
      <StaticRouter location={location} context={context}>
          <App />
      </StaticRouter>
    );

    const extractor = new ChunkExtractor({
      statsFile,
      entrypoints: ['main']
    });

    const jsx = extractor.collectChunks(app);
    
    const reactStream = renderToNodeStream(jsx);

    // inject the scripts, links, style into the html template
    // split apart template into above and below
    // combine three streams and return to client.

    reply.type('text/html').send(stream);
}
```

```
// app.js
```
return (
        <React.Fragment>
            <Header />
            <Switch>
                <Route exact=true path="/" component="Home" />
                <Route exact=true path="/about" component="About" />
                <Redirect to="/" />
            </Switch>
        </React.Fragment>
    );
```

**Comment by markrzen** [comment]
How does the chunkExtractor know what page asset needs to be loaded? I scanned over the code, but didn't see anything diving into the routing or what components were invoked.

**Comment by markrzen** [comment]
Ah, I think my streaming setup is incorrect. The stream must be sent before the extractor has the scripts?

**Comment by markrzen** [comment]
Yep, that was it. Once I finish this up, I can add some flavor to the documentation if that would be helpful?
