### ISSUE TITLE
Cache style file content to improve ssr performance

### ISSUE THREAD

**Issue by yanghuabei** [smooth-code/loadable-components#451]
```
getInlineStyleTags(extraProps = {}) {
    const mainAssets = this.getMainAssets('style')
    const promises = mainAssets.map(asset =>
      assetToStyleTagInline(asset, extraProps, this).then(data => data),
    )
    return Promise.all(promises).then(results => joinTags(results))
  }


```

## 🚀 Feature Proposal

`getInlineStyleTags` use node `fs.readFile` to get style file content every time a request comes. Can we cache style file content to improve ssr performance?

## Motivation

Improve server render performance.

## Example

Cache style file content into memory.

## Pitch

Why does this feature belong in the Loadable Component ecosystem?

User of loadable component has no way to customize or rewrite `getInlineStyleTags` logic.

**Comment by theKashey** [comment]
OS level file cache should work as well.
