### ISSUE TITLE
Support custom ChunkName when using "Full dynamic import"

### ISSUE THREAD

**Issue by billykwok** [smooth-code/loadable-components#453]
## 🚀 Feature Proposal

Support custom ChunkName when using "Full dynamic import".

## Motivation

Some of the auto-generated chunk names are really long if the relative path is long, for example, `content-blog-post-50-reasons-why-x-is-y-z.48be16f8.js`. It not only increases bundle size but also reveals info about the internal path.

## Example

```javascript
// code
loadable.lib(
  ({ postId }) => import(
    /* webpackChunkName: somePrefix.[request] */
    `../../content/blog/post/${postId}`
  ),
  { chunkName: ({ postId }) => postId }
);

// webpack.config.js
{
  ...,
  plugins: [ new webpack.HashedModuleIdsPlugin() ],
  ...
}
```
generates something like `somePrefix.f4aj13.js`, `somePrefix.k19f1i.js`, etc

## Pitch

Why does this feature belong in the Loadable Component ecosystem?
> There is no way to implement it without change Loadable Component codebase

**Comment by theKashey** [comment]
Chunks, as well as chunk names are generated by `webpack`. Loadable components just consumes information _from_ a build, not changing the process.

**Comment by billykwok** [comment]
To my understanding, Loadable Component always overrides the chunkName setting to “[request]” when using fully dynamic import.
And there is no way to change this behavior.

**Comment by theKashey** [comment]
But babel plugin cannot do it, and webpack plugin is not doing it.
How loadable could change webpackChunkName?

**Comment by billykwok** [comment]
I found that the chunk name option doesn't work for me because I used Webpack magic comment in a comma-separated format, instead of independent format.
i.e.
/* webpackInclude: /\.mdx$/i, webpackChunkName: somePrefix.[request] */
instead of
/* webpackInclude: /\.mdx$/i */
/* webpackChunkName: somePrefix.[request] */

After changing the format, I'm now able to generate the correct chunkName that I want.
