### ISSUE TITLE
marking the scripts as `async`

### ISSUE THREAD

**Issue by uzumaki-narut0** [smooth-code/loadable-components#461]
for [loadable server side rendering](https://www.smooth-code.com/open-source/loadable-components/docs/server-side-rendering/), The extractor.getScriptTags() returns a string of multiple <script> tags marked as `async`. Can someone tell me why (if it is) better than marking the scripts as `defer` here?

**Comment by theKashey** [comment]
Does not make any real difference as `defer` controls the execution order of chunks and in case of webpack - it's controlled by webpack, not by the browser.
