### ISSUE TITLE
How to preload chanks before going to page ?

### ISSUE THREAD

**Issue by golubvladimir** [smooth-code/loadable-components#462]
Currently loading occurs after going to pages.

**Comment by theKashey** [comment]
Could you be more concrete please?

**Comment by golubvladimir** [comment]
@theKashey 
My server.js

```
            jsx = extractor.collectChunks(<Provider store={ store }>
                <StaticRouter context={ context } location={ req.url }>
                    <JssProvider registry={sheets}>
                        <AppMain />
                    </JssProvider>
                </StaticRouter>
            </Provider>);

            ....
            const reactDom = async jsx => {
              const element = createElement(jsx);
              await ssrPrepass(element);

              return renderToString(element);
           };
```

I open the Google Chrome console, on the Network tab.
I'm starting to click on the links on the site.
I see in the console that the loading of chunks for the page occurs after going to the page.

How to fix it ?

**Comment by golubvladimir** [comment]
@theKashey How to make preload by chunk being on the previous page?

**Comment by theKashey** [comment]
this is the root idea around code-splitting - NOT load something initially, however:
- use webpack `magic comments` to preload or prefetch chunks. See - https://www.smooth-code.com/open-source/loadable-components/docs/prefetching/
- call `.preload` or `.load` on loadable, as you want to preload new chunk. So people do it on mouse hover.
- you might find many other advises online
- it's up to how to implement.

**Comment by golubvladimir** [comment]
@theKashey After the transition, the page is faded, and then the content is displayed.

I try use <Suspense> around <Router> and react-ssr-prepass for ssr, but loading in fallback only works after the transition, and not before.

**Comment by theKashey** [comment]
Well, there is no `ssr` after you sent your page to the browser, so don't try to find the answer there.
I would recommend starting from scratch. Remove all code-splitting first and then reintroduce it. Do you actually need it, if you don't understand it? Is it making the user experience better? Does it worth it?

**Comment by golubvladimir** [comment]
@theKashey 
My decision, in function load page.
```
    if (typeof window !== 'undefined') {
        if (action.route) {
            if (action.route.indexOf('/all') !== -1) {
               Component1.preload();
               Component2.preload();
               ....
            }
        }
    }
```
I have not yet figured out how to do this automatically.

**Comment by theKashey** [comment]
You __cannot__ do it automatically. However, you might "scan" your routing table (if it exists) and act depending on it.

**Comment by golubvladimir** [comment]
@theKashey What is meant by the table routing table ? What page are the components on? Is it possible to compose it automatically, and not enter it each time manually ?

**Comment by theKashey** [comment]
In short - no, it is not possible.
A bit longer version - of course, it possible, but you have to find your own way first.
