### ISSUE TITLE
Retry lazy loading

### ISSUE THREAD

**Issue by Tarvald** [smooth-code/loadable-components#467]
Hi,
At this moment we are using React.lazy, however, it is a time for SSR that is obviously not supported in React itself.

However, we are using this approach:
https://dev.to/goenning/how-to-retry-when-react-lazy-fails-mb5
If chunks load will fail. 

I cannot adopt this function to @loadable/component. 

This:
`import {lazy} from '@loadable/component';`
It does not return promise somehow. I am not sure but "loadable" function will return promise however, it does not support suspense. 

Do you have any idea how to connect it together?

Best regards

**Comment by theKashey** [comment]
That would not work with `loadable-components` __by design__. Wrapping `import function` with any third-party code would be:
1) ignored on SSR
2) might be ignored on the client side

such logic should be implemented using React __Error Boundaries__ - `lazy` would throw on chunk failure, and you might just render it again (better in timeout) "retrying" loading.
