### ISSUE TITLE
getLoadableState return empty object on development

### ISSUE THREAD

**Issue by wellyshen** [smooth-code/loadable-components#48]
@neoziro I'm using this library with **SSR + react-hot-loader@4.0.0-beta.22**. And I found the `getLoadableState` return empty object like as `window.__LOADABLE_STATE__ = {};` on development but on production it return the correct path of async component like as `window.__LOADABLE_STATE__={children:[{id:"./Home"}]}`. Does this behavior meet expectation? It can be reproduce on the last commit of [here](https://github.com/wellyshen/react-cool-starter)

**Comment by wellyshen** [comment]
It may caused by **react-hot-loader**. (refer to [here](https://github.com/wellyshen/react-cool-starter/issues/153#issuecomment-366426247))

**Comment by wellyshen** [comment]
@neoziro **react-hot-loader@4.0.0-rc.0** solved this issue.

**Comment by neoziro** [comment]
@wellyshen 🎉
