### ISSUE TITLE
Error Handling not working

### ISSUE THREAD

**Issue by BlackFenix2** [smooth-code/loadable-components#52]
the loadableComponent does not resolve the errorComponent listed when the imported component throws an error or fails to resolve. it is just stuck in the loadingComponent.

![image](https://user-images.githubusercontent.com/15244006/37681758-f3a75fa0-2c5d-11e8-8a59-05004624c1f8.png)

here is the code in question

```
const config = {
  LoadingComponent: () => <Loading />,
  ErrorComponent: () => <Error />
};

function setPageRoute(Name) {
  return loadable(() => import(`../Pages${Name}`), {
    ...config
  });
}

const Home = setPageRoute('/Home');
```

**Comment by neoziro** [comment]
I think it is a Webpack related error, I do not know if you can use complete dynamic import, they are still parsed by Webpack. In your example it is not possible.

To see if it is a loadable components issue, it is simple, try to catch the error yourself:

```js
const config = {
  LoadingComponent: () => <Loading />,
  ErrorComponent: () => <Error />,
}

function setPageRoute(Name) {
  return loadable(
    () =>
      import(`../Pages${Name}`).catch(error => {
        console.log('error catched')
        return null
      }),
    {
      ...config,
    },
  )
}

const Home = setPageRoute('/Home')
```

**Comment by neoziro** [comment]
Good!
