### ISSUE TITLE
Attach static methods of wrapped component to loadable component

### ISSUE THREAD

**Issue by artemxgruden** [smooth-code/loadable-components#58]
Attach static methods of wrapped component to loadable component

**c1.mjs**
```javascript
import * as React from 'react'
const createElement = React.default.createElement
const Component = React.default.Component

export default class c1 extends Component {
  constructor( props ){
    super( props )
  }
  render(){
    return createElement( 'p', {}, 'hello' )
  }
  static async preloadDataState( parameters ){
    debugger
  }
}
```

**main.mjs**
```javascript
import * as React from 'react'
const createElement = React.default.createElement

import * as LoadableComponents from 'loadable-components'
const loadable = LoadableComponents.default.default

import * as LoadableComponentsServer from 'loadable-components/server'
const getLoadableState = LoadableComponentsServer.default.getLoadableState

const c1 = loadable( () => import( /* webpackChunkName: "main.c1" */ './c1.mjs' ), {
  modules: [ './c1.mjs' ],
} )

const composition = createElement( c1 )

getLoadableState( composition ).then( ls => {
  console.log( c1.Component.preloadDataState )
} )
```
output: 
```
[AsyncFunction: preloadDataState]
```

**Suggestion:** 
attach static methods or fields directly to loadable component ( c1 ):
preloadDataState method available by c1.**preloadDataState** instead of c1.**Component.preloadDataState**

**Comment by mrasoahaingo** [comment]
Is this feature available on the latest version?

**Comment by neoziro** [comment]
Yes!

**Comment by mrasoahaingo** [comment]
Actually i can't get the statics methods of the component nor the component it self :(

Test.js
```
import React from 'react';

const Test = () => <h1>Test</h1>;
Test.staticMethod = () => console.log('test');

export default Test;
```

Main.js
```
import loadable from '@loadable/component';

const Live = loadable(() => import('./components/live/Live'));
console.log(Live);
console.log(Live.Component);
console.log(Live.staticMethod);
```
// { '$$typeof': Symbol(react.forward_ref),
  render: [Function],
  preload: [Function] }
// undefined
// undefined

**Comment by neoziro** [comment]
Methods can't be added before the module is loaded. How could we know the methods? After the component being loaded, methods will be accessible.

**Comment by mrasoahaingo** [comment]
Hum, so i need to resolve all loadable modules first before trying to access to static method?

**Comment by neoziro** [comment]
Yes.

**Comment by mrasoahaingo** [comment]
I get it now, thanks!

**Comment by windFollower29** [comment]
in ssr, how I can know that a loadable module has been loaded? `loadableReady()` must be called in browser only .

> Methods can't be added before the module is loaded. How could we know the methods? After the component being loaded, methods will be accessible.

**Comment by neoziro** [comment]
The only way to know if a component is rendered is in the component itself. The easiest method is to pass a function called when the component is mount.

```js
import loadable from '@loadable/component';
const Test = loadable(() => import('./Test'));

<Test onLoad={() => console.log('loaded')} />
```

```js
// Test.js
import React, { useEffect } from 'react'

export default function Test({ onLoad }) {
  useEffect(() => { onLoad() }, [])
  return null
}

**Comment by jsonchou** [comment]
@neoziro 

## client side:

router config:
```
{
    path: `/index`,
    exact: true,
    page: 'Index',
    meta: {
        title: 'aaaaa'
    },
    component: loadable(props => {
        return import(/* webpackChunkName: "Index" */
        `../pages/Index/Index`)
    })
},
```

### index page:
../pages/Index/Index
```
IndexPage.serverApiNames = "indexApi,commonApi"  //static properties,
```

## server side:
```
let currentRoute = routes[0].routes.find(router =>
    matchPath(ctx.request.path, {
        path: router.path,
        exact: router.exact
    })
)
let { exact, page, meta, component } = currentRoute
```

## my question:
how can i get my static component.**serverApiNames**

**Comment by neoziro** [comment]
Loadable Components is not design to work with "statical" approach. I recommend you to use "react-navi" for this kind of approach.

**Comment by jsonchou** [comment]
thanks , i'll have a try.

**Comment by davidfurlong** [comment]
> how can i get my static component.**serverApiNames** in server side.

this seems to be possible now - if you know which component is loading via a route match (react router or otherwise)

you can do 

```js
        const loadedComponent = await (component as LoadableComponent<any>).load();
        loadedComponent?.default?.accessYourStaticPropName
...
```
