### ISSUE TITLE
window[LOADABLE_STATE] is not working

### ISSUE THREAD

**Issue by KrustyC** [smooth-code/loadable-components#67]
I'm trying to use this lubrary with SSR, but I keep receiving this error ` loadable-components state not found. You have a problem server-side. Please verify that you have called `loadableState.getScriptTag()` server-side`. I dive into the module and I put a `console.log(window)` in the `loadComponents()` function, the result contains this: 
![image](https://user-images.githubusercontent.com/20644593/39447178-e309f006-4cb8-11e8-9829-52765eaf7e85.png)

but if I do  `console.log(window[LOADABLE_STATE]);` is returning `undefined`.

Do you have any clue about what is happening?

**Comment by KrustyC** [comment]
@neoziro  I think I found a possible solution:
basically I change the `loadComponents()` to this:
`function loadComponents() {
  if (typeof window === 'undefined') {
    throw new Error('loadable-components: `loadComponents` must be called client-side: `window` is undefined');
  }   
  return new Promise(function (resolve, reject) {
    window.onload = function() {
      var state = window[LOADABLE_STATE];
      if (!state) {
        throw new Error('loadable-components state not found. ' + 'You have a problem server-side. ' + 'Please verify that you have called `loadableState.getScriptTag()` server-side.');
      }
   
      resolve(loadState(state));
    }
  });
}
`

The function has to wait for the window to be fully loaded and then I have to wrap it in a Promise, in order to return only when the window is loaded.

Do you think this is a bug or do you think I  might missing something somewhere?

**Comment by neoziro** [comment]
Ah good workaround. In fact `loadableState.getScriptTag()` must be called before your `loadComponents()` and it should work without having to rewrite the `loadComponents` method.

**Comment by KrustyC** [comment]
Thanks for the reply, I moved the `loadableState.getScriptTag()` before importing my main js file and it is working now. By the way, I'm not 100% sure the window is gonna be loaded every time, do you think might be useful to wrap it on a promise and wait for `onload` event before resolving the promise?

**Comment by neoziro** [comment]
No I don't think so. You should add scripts at the end of the body, this is the way to setup all React stuff so I think it is OK like that.
