### ISSUE TITLE
Question: Load all component from client begins

### ISSUE THREAD

**Issue by rwu823** [smooth-code/loadable-components#68]
Hi I like this solution for SSR code splitting, but I have a question about load all component from client begins:

```js
// Load all components needed before starting rendering
loadComponents().then(() => {
  ReactDOM.render(
    <BrowserRouter>
      <App />
    </BrowserRouter>,
    document.getElementById('main'),
  )
})
```

So the client also load unneeded code, didn't have code splitting benefit?

**Comment by neoziro** [comment]
The client loads only components required to display the current page, so you have all code splitting benefits.

Server-side, required components are collected and dumped in a global. This function uses this global and loads all required components.

**Comment by rwu823** [comment]
Hmm, but I saw network panel loading all components. Waht's wrong?

**Comment by neoziro** [comment]
Maybe you are preloading all routes?
