### ISSUE TITLE
dynamic import not work ?

### ISSUE THREAD

**Issue by MrZhang123** [smooth-code/loadable-components#71]
## Description
Hi, I use webpack4 and loadable-components for code splitting and dynamic import , I see the webpack code splitting success , but dynamic import not work , here is my code
```js
// router.js
import loadable from 'loadable-components'
export const Home = loadable(() => import('./Home'))
export const About = loadable(() => import('./About'))
export const Topics = loadable(() => import('./Topics'))

// RouterLink.js
<BrowserRouter>
    <Route exact path="/" component={Routes.Home} />
    <Route path="/about" component={Routes.About} />
    <Route path="/topics" component={Routes.Topics} />
</BrowserRouter>

// App.js
class App extends Component {
    render(){
      <RouterLink />
    }
}
```
DId the loadable-components need config babel ? I try to config `loadable-components/babel`  in .babelrc ,  but it not work , here is my .barbelrc

```js
{
  "presets": [
    [
      "env",
      {
        "loose" : true,
        "modules": false
      }
    ],
    "stage-0",
    "react"
  ],
  "plugins": [
    "loadable-components/babel",
    "react-hot-loader/babel"
  ]
}
```
## Environment
node: 8.9.0
react-hot-loader: 4.1.1
webpack :4.6.0
webpack-dev-server: 3.1.3
loadable-components: 1.4.0

**Comment by neoziro** [comment]
You don't need Babel plugin if you are not doing server-side rendering. What is the error?

**Comment by MrZhang123** [comment]
@neoziro not error , just dynamic import not work. I just config like Get Start in README. Do I need config other ?

**Comment by neoziro** [comment]
If you are using `react-hot-loader` this is the expected behaviour.

**Comment by MrZhang123** [comment]
@neoziro Sorry for a delay . I use `react-hot-loader` for hot reload ,  it means if I use this , all components are loaded , i need add `.load()`?  
I use `react-router-config` to Static Routes , [code like this](https://github.com/MrZhang123/Web_Project_Build/blob/dev/react-webpack/src/views/Content/router.js) , how to configure to implementation dynamic import ?
