### ISSUE TITLE
Loaded all chunks in development mode

### ISSUE THREAD

**Issue by romanlex** [smooth-code/loadable-components#72]
Hello, I'm use webpack 3 and loadable-components
In development mode when I'm trying open page of application I see what all async chunks loaded immediately. Why?
![image](https://user-images.githubusercontent.com/3369304/39662505-d0c8f4e0-506a-11e8-8459-84a344fe8b04.png)

I'm use routing based code-splitting
```js
export default (
  <Switch>
    <Route path='/' exact component={userIsNotAuthenticated(IndexContainer)} />
    <Route path='/main/:anchorSectionId' component={IndexContainer} />
    <Route exact path='/:type(oge|ege)' component={EgeOgeContainer} />
    <Route exact path='/olymp-courses' component={OlympCoursesContainer} />
    ...
  </Switch>
)
```

In production build I see only what I need for currently route
![image](https://user-images.githubusercontent.com/3369304/39662555-ee6900ca-506b-11e8-9ecd-9dfa3e1cfeb5.png)

**Comment by neoziro** [comment]
It is because of Hot Reloading mode. https://github.com/smooth-code/loadable-components#hot-reloading
