### ISSUE TITLE
Preload scripts

### ISSUE THREAD

**Issue by olegreznichenko** [smooth-code/loadable-components#77]
Can I some hove get the path to chunk for creating preload scripts on the server side?
```
const chunks = ['output/chunk/path/chunkname.js', ...]
chunks.map(file => <link rel='preload' href={file}' />)
```
For example https://github.com/jamiebuilds/react-loadable#getbundles
P.S. I`m migrating to your loadable-components from react-loadable 👍

**Comment by neoziro** [comment]
This is not possible at this time. To do it we need to couple it with Webpack. I will probably do it soon.

**Comment by rajatpharmeasy** [comment]
This is necessary if you are splitting your CSS, otherwise there will be FOUC. The <link> tag needs to be included in the server html.

**Comment by dgieselaar** [comment]
@neoziro I've got it working with a fork, this is enough: https://github.com/dgieselaar/loadable-components/blob/65ee245f1166a8ed0ab46760821748ce93cba79e/src/loadable.js#L116. Does it make sense?

**Comment by dmitru** [comment]
+1. This feature would be VERY useful to have.

**Comment by dgieselaar** [comment]
FYI, here's a (gross) snippet that is working *w/ my fork* (use/edit at your own peril):

```javascript
import fs from 'fs';
import {
  uniq,
  flattenDeep,
  pickBy,
} from 'lodash';
import getRenderedComponents from './getRenderedComponents';

const records = fs.readFileSync('records.json'); // from webpack's recordsOutputPath

const components = getRenderedComponents();

const chunks = uniq(flattenDeep(
  components.map((component) => {
    return component.modules.map((m) => {
      if (!records.chunks) {
        return [];
      }
      const chunkIds = values(pickBy(records.chunks.bySource, (value, key) => key.endsWith(` ${m}`)));
      const chunkNames =
        Object.keys(pickBy(records.chunks.byName, value => chunkIds.includes(value)));
      return chunkNames;
    });
  })
)).filter(identity);
```

I get the components I need to load from the route definition (I have a top-down route configuration), but once you have that, you can use this to get the assets from Webpack. Again, gross, and only works with my fork (which I would not recommend using in production unless you're me).

**Comment by neoziro** [comment]
@dgieselaar thanks for this! It looks great!

**Comment by neoziro** [comment]
Loadable Components v3 has been released 🎉, and it supports `<link rel="preload">`!

👉 https://github.com/smooth-code/loadable-components
