### ISSUE TITLE
Webpack magic comments not supported?

### ISSUE THREAD

**Issue by cloud-walker** [smooth-code/loadable-components#8]
First of all, thanks for your effort on this topic!

I've rapidly tried your solution on my project, and seems to work fine, here my observations (with a console.log on the loadable component render):

- render seems to be fired 3 times: 1 on the client side, 2 on the server side.
- the application broke if you try to import the component using [webpack magic comments](https://webpack.js.org/guides/code-splitting/#dynamic-imports)

The fact that you render only one time on the client side its awesome (would be perfect one time on the server side too), but I'd like to use magic comments, any plan on this?

**Comment by neoziro** [comment]
Yes of course, I plan to support that as soon as possible.

Concerning the two rendering server-side : first we walk threw the React tree (it is less consumer than a rendering), then we render. So there is no two renderings even if it looks like.

Can you give me precision about what is broken using webpack magic comments?

**Comment by neoziro** [comment]
@cloud-walker I just tested it and it does not seem to be a problem using magic comment. Can you please give me more details?

**Comment by cloud-walker** [comment]
It was just a quick try! 

I will do a more focused and clean experiment, so if something will go wrong I will publish it to you :)

**Comment by neoziro** [comment]
OK thanks!
