### ISSUE TITLE
Support for context (variables) in import()?

### ISSUE THREAD

**Issue by swernerx** [smooth-code/loadable-components#82]
Hi! Thanks for the great work. Seems like a very good contender on the field of making SSR nice and round.

Comparing with some other solutions I was wondering whether the solution supports context imports like ```import(`./views/${viewName}`)``` - would be somewhat nicer than wrapper each individual view/page.

The reason I am writing an issue is because there is nothing officially mentioned in the docs.

**Comment by neoziro** [comment]
Currently context imports are not supported.

**Comment by swernerx** [comment]
It's doing a directory lookup and just imports all the files matched.

**Comment by theKashey** [comment]
Not exactly - it bundles all the files possible matching the mask, loads that bundle and then picks the "right" file from it.
That might be changed in future, but webpack 3 and 4 will transfer to client("load") all the files you might match. This is not the thing you actually need, unless you want to repeat _moment.js_'s fate.

**Comment by neoziro** [comment]
I think this is not a good approach, views are already known because they are actually real files. I suggest you to generate the whole possibilities, you can do it using a custom script or maybe [Prepack](https://prepack.io/).

**Comment by neoziro** [comment]
So you will have one Loadable component for each possible view.
