### ISSUE TITLE
Server initial render

### ISSUE THREAD

**Issue by thomasdigby** [smooth-code/loadable-components#90]
We're having an issue where any Loadable Components within the first server render of the page are empty, however if you refresh the page the server response will include them.

Has this been logged before? Is it a known issue? Or something to do with bundling the server in Webpack?

Could you point me towards the place that renders the Loadable Components on the server so I can attempt to debug it?

Thanks

**Comment by neoziro** [comment]
[`getLoadableState`](https://github.com/smooth-code/loadable-components#getloadablestate) waits for all component to be loaded, so if you use this method it should work.

Can you provide a reproducing example?

**Comment by thomasdigby** [comment]
Ok great, let me get one together for you today!

**Comment by thomasdigby** [comment]
I hadn't had a chance to look at this till today and I think I figured out the issue, although I don't understand why it would make any difference.

I was calling `getLoadableState` after `renderToString`, like below, however if you call `getLoadableState` _before_ `renderToString` it works perfectly. I'd be interested to know why this might be the case as the two seem unrelated? Full repo test case [here](https://github.com/thomasdigby/loadable-components-test)

```
import React from 'react'
import express from 'express'
import { renderToString } from 'react-dom/server'
import { getLoadableState } from 'loadable-components/server'

import App from './components/App'

const server = express()

server.use(express.static('public'))

server.get('/*', async (req, res) => {
  const markup = renderToString(<App />)
  const loadableState = await getLoadableState(<App />)
  res.send(`
    <!doctype html>
    <html>
      <head>
        <meta charSet='utf-8' />
        <meta name="viewport" content="width=device-width, initial-scale=1">
      </head>
      <body>
        <div id="root">${markup}</div>
        ${loadableState.getScriptTag()}
        <script src="/client.js"></script>
      </body>
    </html>
  `)
})

server.listen(3000)
```
