### ISSUE TITLE
Bug in babel plugin

### ISSUE THREAD

**Issue by olegreznichenko** [smooth-code/loadable-components#99]
```js
const options = {
  LoadingComponent: <div />
}

const Hello = Loadable(() => import('./Hello'), options)
```
`Cannot read property 'push' of undefined`
![image](https://user-images.githubusercontent.com/11960153/41327419-6563f9c6-6e91-11e8-918e-6019a46467d0.png)

**Comment by GrtDev** [comment]
Seems to be an issue with the options reference? I encountered the same error but if I spread the options into a new object it seems to work.

try: `const Hello = Loadable(() => import('./Hello'), {...options})`

**Comment by neoziro** [comment]
Loadable Components v3 has been released 🎉, please give a try.

👉 https://github.com/smooth-code/loadable-components
